Bailiff...
Bubberstation/Bubberstation pull request #1056
Opened 2024-01-23 16:01 UTC by tf-4

## About The Pull Request

Adds the ability to crack nuts. The nutcracker.

The effect is very powerful, but I don't think that's an issue given that it only works if you remove your underwear which is both a conscious choice and cannot be done by anyone or anything except you.

## Why It's Good For The Game

Gives an IC reason not to walk around playing basketball in the public hallways.

## Proof Of Testing

![image](https://github.com/Bubberstation/Bubberstation/assets/8881105/063d0473-b303-47d1-9adb-8c0641d04f84)

## Changelog
:cl:
add: Added the ability to punch people in the nuts.
/:cl:

2024-01-23 16:31 UTC, ReturnToZender commented
I'm disappointed that this doesn't involve an actual nutcracker item, this should involve a physical item called a nutcracker that cracks someone's nuts

2024-01-24 09:30 UTC, Majkl-J requested changes
Code looks otherwise solid, and is a funny way to enforce the law of not walking around naked if you ask me

2024-01-24 09:30 UTC, Majkl-J commented on code/modules/mob/living/carbon/human/_species.dm
> +		target.nut_shot(user) // BUBBERSTATION EDIT ADD
```suggestion
		target.try_nut_shot(user) // BUBBERSTATION EDIT ADD
```

2024-01-24 09:30 UTC, Majkl-J commented on modular_zubbers/code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/proc/nut_shot(mob/living/attacker)
```suggestion
/mob/living/carbon/human/proc/try_nut_shot(mob/living/attacker)
```

2024-01-24 21:39 UTC, closed without merging