Non-Modular I was forced to state laws by a jaunting miner
Bubberstation/Bubberstation pull request #1088
Opened 2024-01-30 13:58 UTC by Odairu

## About The Pull Request
Removes bloodcrawl from bubblegums loot pool

## Why It's Good For The Game
Miners shouldn't have a jaunt that lets them be invulnerable forever and go wherever they please before manifesting somewhere with blood

## Proof Of Testing
I loaded the game up and killed bubblegum a few times, only got the soul scythe

## Changelog

:cl:
Deletes bloodcrawl from bubblegums loot pool
/:cl:

2024-01-30 14:14 UTC, Erol509 commented on code/modules/mining/lavaland/necropolis_chests.dm
>  	new /obj/item/clothing/suit/hooded/hostile_environment(src)
Dont remove it, comment it out. Use /* */ block comment and name it Bubberstation removal start at the begining and END at the end

2024-01-30 14:16 UTC, Erol509 requested changes

2024-01-30 14:16 UTC, Erol509 commented on code/modules/mining/lavaland/necropolis_chests.dm
> -	var/loot = rand(1,2)
Dont remove it, comment it out. Use /* */ block comment and name it Bubberstation removal start at the begining and at the end

2024-01-30 14:35 UTC, ReturnToZender commented
![Won the court case](https://github.com/Bubberstation/Bubberstation/assets/110273561/9bebe9db-baf8-4907-936b-ad4bd04aa7da)

After the PR is merged

2024-01-30 16:16 UTC, MLGTASTICa commented
Could put a little bit more effort and make it be a shittier blood-jaunt which is interrupted when the blood poll they are sitting in is cleaned and that cant teleport to other blood polls.

2024-01-31 05:52 UTC, Odairu commented
> Could put a little bit more effort and make it be a shittier blood-jaunt which is interrupted when the blood poll they are sitting in is cleaned and that cant teleport to other blood polls.

No, the spell is toxic and miners shouldn't be the literal gods of the station. This was originally a skyrat addition because they don't know what balance in a video game is. Miners shouldn't get to play dota 2 and come back on station an hour into the game and be able to do whatever the fuck they want to whoever they want with zero recourse.

2024-01-31 11:43 UTC, MLGTASTICa commented
> > Could put a little bit more effort and make it be a shittier blood-jaunt which is interrupted when the blood poll they are sitting in is cleaned and that cant teleport to other blood polls.
> 
> No, the spell is toxic and miners shouldn't be the literal gods of the station. This was originally a skyrat addition because they don't know what balance in a video game is. Miners shouldn't get to play dota 2 and come back on station an hour into the game and be able to do whatever the fuck they want to whoever they want with zero recourse.

If you'd actually code the iteration i mentioned it wouldn't be good at all. Blood jaunt is coded with wizards in mind so of course it isn't balanced with miners having it , but why just remove it when it does fit the bubblegum theme and when it can be rewritten to be actually balanced

2024-01-31 16:08 UTC, StrangeWeirdKitten approved these changes

2024-01-31 16:12 UTC, StrangeWeirdKitten commented
I like blood crawl specifically for kinky ERP. But that's my own personal preference for it. While I credit skyrat for making a better alternative to the mayhem bottle, this thing needs to go. Someone is free to rework it if they have a good idea on how to do such

2024-01-31 21:18 UTC, merged