Stop spamming logs when engineers lovingly feed the supermatter pipes by the hundreds.
Bubberstation/Bubberstation pull request #1116
Opened 2024-02-06 18:27 UTC by Swiftfeather

## About The Pull Request

Title 

Also the method I went about this adds a flag to the game, which means in the future if people find another way to spew even more items into the supermatter that spam the log, we can just add the flag to those items.

## Why It's Good For The Game

I got bwoinked this one time because I was spamming the admin log and I told them I'd look for a solution.

This might not be _the_ solution but it is **a** solution. 

## Proof Of Testing

this is what my IC chat tab looked like
![image](https://github.com/Bubberstation/Bubberstation/assets/26744576/bf7e5b9e-daf5-451c-b839-3232ae0a6317)

This is what my logs tab looked like

![image](https://github.com/Bubberstation/Bubberstation/assets/26744576/5c820074-a16e-47d1-83cc-606fe6874eb0)

I also verified that other items still set off the log function as expected and desired. No pipe items will, though.

## Changelog

:cl:
admin: Will no longer receive supermatter ate a pipe spam in the log.
/:cl:

2024-02-06 20:16 UTC, Majkl-J requested changes

2024-02-06 20:16 UTC, Majkl-J commented on code/datums/components/supermatter_crystal.dm
>  			var/suspicion = ""
```suggestion
	
	else if(consumed_object.flags_1 & SUPERMATTER_NOLOGS_1)

	else if(isobj(consumed_object))
		if(!iseffect(consumed_object) && !(consumed_object.flags_1 & SUPERMATTER_NOLOGS_1)) //BUBBER EDIT | NOLOGS flag Addition to ignore items engineers like to feed the SM :3
			var/suspicion = ""
```

2024-02-06 20:16 UTC, Majkl-J commented on code/__DEFINES/_flags.dm
> +
Always make some room for any future defines

```suggestion
//BUBBER EDIT START - Flags
//Does item send log notices to admin log when consumed by supermatter?
#define SUPERMATTER_NOLOGS_1 (1<<20)

//BUBBER EDIT END
```

2024-02-06 20:16 UTC, Majkl-J commented on code/game/machinery/pipe/construction.dm
> +	//BUBBER ADDITION END
This one should be made modular with

```
/obj/item/pipe/Initialize(mapload)
	flags_1 |= SUPERMATTER_NOLOGS_1
	. = ..()
```

2024-02-06 21:50 UTC, lessthnthree commented
Was this rejected upstream? It seems like a no brainer. (It spams admin logs too)

2024-02-07 00:37 UTC, ReturnToZender commented
So full of pipes yum

2024-02-07 02:11 UTC, Swiftfeather commented
> Was this rejected upstream? It seems like a no brainer.

![Screenshot_20240206_200835_Discord](https://github.com/Bubberstation/Bubberstation/assets/26744576/102e9cee-1040-46ae-8bc0-4d0637803a53)

2024-02-07 17:16 UTC, Majkl-J commented on code/game/machinery/pipe/construction.dm
> +	//BUBBER ADDITION END
`modular_zubbers/code/game/machinery/pipe/construction.dm`

2024-02-07 21:01 UTC, Arturlang commented
Better way to fix this would be to keep a counter of recent dustings, and only show the number of items sacrificed with the name of each unique name and maybe even add a click option for admins to make the SM stop adminlogging

2024-02-08 05:40 UTC, Swiftfeather commented
After putting in requested changes it no longer seems to work. hm

2024-03-04 02:54 UTC, merged