Adds wounds to the medical huds
Bubberstation/Bubberstation pull request #1123
Opened 2024-02-09 15:14 UTC by NithaIsTired

## About The Pull Request
Adds wounds to the medical huds.
Sprites by [Tamamitsune](https://github.com/Tamamitsune)

## Why It's Good For The Game
Having a way to tell that people are wounded will surely decrese the chances of medical sending people off after just doing basic healing, also making it very easy to prioritize patients.

## Proof Of Testing
![1707472030](https://github.com/Bubberstation/Bubberstation/assets/132854285/0fe81a44-901b-4f4b-a6c1-ff3b8bc97920)

## Changelog

:cl: NithaIsTired, Tamamitsune
add: Medical huds now displays the current wound severity the patient has.
/:cl:

2024-02-09 19:04 UTC, NithaIsTired commented
> would be best upstream on tg i think theyd like this

I might do that once I'm not too sick to do stuff

2024-02-09 21:20 UTC, Wolf-751 commented
This is a damn good idea as a medbay main i can tell you though the best wound you want to cover for this is bleeding,bullet holes,bones are alright but not that dire to treat instantly and usally a quick look over will tell you there broken bone area the most pressing wounds are the bleeding/rotting ones.

2024-02-09 22:30 UTC, nikothedude commented
also it might be best to instead give the wound datum a icon variable and a icon severity for better OOP practices and also to solve the issue above, so that weeping avulsions will override a compound fracture

alternatively you can have the icons cycle through the highest severity ones

2024-02-10 00:50 UTC, NithaIsTired commented
I did consider adding specific bleeding icons but I was already suffering to make this cycle with the virus icons so i decided to keep it simple for now (bleeding is easy to spot by just looking at the person anyways but the wound icon will still show)

I'll see if i can get an icon for bleeding and try to make that work too

2024-02-10 17:41 UTC, Majkl-J requested changes
Review one, very brief look. There will probably be many more

2024-02-10 17:41 UTC, Majkl-J commented on modular_zubbers/code/game/data_huds.dm
> +				highest_severity_found = TRUE
```suggestion
			if (wound.severity == WOUND_SEVERITY_CRITICAL)
				holder.icon_state = "hudcriticalwound"
				highest_severity_found = TRUE
				break
			else if (wound.severity == WOUND_SEVERITY_SEVERE && !highest_severity_found)
				holder.icon_state = "hudseverewound"
				highest_severity_found = TRUE
			else if (wound.severity == WOUND_SEVERITY_MODERATE && !highest_severity_found)
				holder.icon_state = "hudmoderatewound"
				highest_severity_found = TRUE
```

2024-02-11 07:09 UTC, nevimer commented
This is good, we will be testing it for a bit. Try to get around to reviews when you can.

2024-02-12 15:43 UTC, Tupinambis commented
Should have been a thing when wounds was originally added. Good change.

2024-04-26 07:09 UTC, Swiftfeather commented
Hey there, this has been stale for quite a while. If you decide to continue working on this please feel free to re-open this PR!

2024-04-26 07:09 UTC, closed without merging