Bunny hop walking animation
Bubberstation/Bubberstation pull request #1130
Opened 2024-02-11 02:51 UTC by ReturnToZender

## About The Pull Request

This PR makes it so that you can take an optional quirk that makes it so you bounce like a rabbit. Originally inspired by https://github.com/tgstation/tgstation/pull/79698 on TG, which was closed due to bugs.

This PR doesn't add anything to Genetics, or fix those bugs, it simply makes you bounce. :)

## Why It's Good For The Game

This will allow bunny or other characters to actually hop! Adds a little bit of personal expressions.

## Proof Of Testing

## Changelog

:cl: ReturnToZender (port), IAmGoofBall (original code)
add: Bunny hop quirk for all players to choose! :)
/:cl:

2024-02-11 11:15 UTC, Majkl-J commented
Can we make it maybe a custom option like with some quirks to avoid the bloat of hopping/waddle?

2024-02-11 11:31 UTC, ReturnToZender commented
> Can we make it maybe a custom option like with some quirks to avoid the bloat of hopping/waddle?

You mean like a character preference?

2024-02-11 12:02 UTC, Majkl-J commented
> > Can we make it maybe a custom option like with some quirks to avoid the bloat of hopping/waddle?
> 
> You mean like a character preference?

No, certain quirks can have extra settings that can be modified... lemme grab an example in a bit

2024-02-11 18:37 UTC, nikothedude commented
> > Can we make it maybe a custom option like with some quirks to avoid the bloat of hopping/waddle?
> 
> You mean like a character preference?

they mean, bundle this with waddling via quirk customization

2024-02-11 19:12 UTC, Majkl-J commented
> > > Can we make it maybe a custom option like with some quirks to avoid the bloat of hopping/waddle?
> > 
> > 
> > You mean like a character preference?
> 
> they mean, bundle this with waddling via quirk customization

Thank you I am having a stroke today

2024-03-04 02:50 UTC, nevimer requested changes

2024-03-04 02:50 UTC, nevimer commented on tgstation.dme
>  #include "modular_zubbers\modules\quirks\code\neutral_quirks\waddle.dm"
```suggestion

```

2024-04-30 09:06 UTC, Swiftfeather commented
This has been inactive for over a month. Reopen if you come back to it.

2024-04-30 09:06 UTC, closed without merging