Prison headset
Bubberstation/Bubberstation pull request #116
Opened 2023-03-19 19:01 UTC by Icarus-The-Sun

Adds basic headsets without encryption keys to the prisoner loadouts, mainly aimed to counteract times when security is unaware prisoners are present, or during times the prison is destroyed and prisoners cannot call for help. Works with both plasmamen and default loadouts.

## Changelog

:cl:
qol: Adds headsets to the roundstart prisoner outfit.
/:cl:

2023-03-19 19:29 UTC, NullDagaf commented
Modularize it. Otherwise, 👍 from me.

2023-03-20 14:55 UTC, mcmeiler commented
Same as above. I have no strong opinions on prisoners being able to talk to the rest of the crew. Could be interesting.
~~Might even see a lynchmob if they're being annoying or using it to host a radio station or something.~~

2023-03-20 17:35 UTC, Icarus-The-Sun commented
This _should_ modularize it, sorry that it took a bit, I'm unfamiliar with modularizing code!

2023-03-21 07:53 UTC, KathrinBailey requested changes

2023-03-21 07:53 UTC, KathrinBailey commented on code/modules/jobs/job_types/prisoner.dm
Revert these changes, you are overriding them in the modular code thus you have no reason to remove them.

2023-03-21 15:42 UTC, closed without merging