Blueshield station trait
Bubberstation/Bubberstation pull request #1186
Opened 2024-02-20 19:14 UTC by Swiftfeather

## About The Pull Request

Puts blueshield behind a new station trait, much like bridge assistant or cargorilla. 

List of changes I have made: 

- Blueshield can now only be played if the station trait rolls or is bussed.
- Blueshield lockers will no longer be spawned on the map. (I think, I'm not a mapper lmao)
- Blueshields will spawn with a beacon in their backpack that will supply drop a blueshield locker when used. 
- When the Blueshield trait rolls, it will be available for latejoins to choose. 

Weighting is subject to change. 

_**Also maintainers the config needs to be updated to accommodate the slot # change (I think???)**_

## Why It's Good For The Game

I have had a feeling for a while when playing this server that Blueshield is often poorly utilized. This isn't a dig at any specific players, the role just feels like it doesn't fit, especially when I'm playing command, and ESPECIALLY when there's an NT rep present. 

Originally I wanted to remove it but after playing a bit more I felt that was going a little too far. 

I think putting it behind a trait will improve the enjoyment both the people who play and the people who interact with because it will be more sought after and I believe people who see it open and pick it will try to make the most out of their shift.

Admins can bus the trait to take effect next-round if they've got plans and want to make it available or someone's been very good and redeemed their good bubber points.

## Proof Of Testing

No blueshield without the trait.
![image](https://github.com/Bubberstation/Bubberstation/assets/26744576/c81406c1-f67d-4571-b1e9-70c155cc3778)

I bussed the trait then restarted the server, blueshield available for latejoins.
![image](https://github.com/Bubberstation/Bubberstation/assets/26744576/0ff348ed-bd15-407c-b909-be8424c693ac)

Blueshield cannot be selected in the character preferences occupations tab.
![image](https://github.com/Bubberstation/Bubberstation/assets/26744576/f341d630-ccbf-4a66-a1e4-c9268db545a9)

Spawned with the beacon and used it.
![image](https://github.com/Bubberstation/Bubberstation/assets/26744576/3a5e2a79-3fec-4b3b-8eca-1d051a722696)

Pod came down and dropped the BS locker off
![image](https://github.com/Bubberstation/Bubberstation/assets/26744576/5146e66b-7db4-41ef-a943-dfef63169554)

## Changelog

:cl:
add: Added the Blueshield station trait.
del: Blueshields are no longer available every round.
del: Blueshield lockers have been removed from the maps.
add: Blueshields spawn with a beacon to supply drop their locker in.
/:cl:

2024-02-20 19:17 UTC, Majkl-J requested changes

2024-02-20 19:17 UTC, Majkl-J commented on modular_skyrat/modules/blueshield/code/blueshield.dm
> +	//BUBBER ADDITION END
This one can come in modular form

```suggestion
/datum/outfit/job/blueshield
	backpack_contents = list(
		/obj/item/choice_beacon/blueshield = 1,
	)
```

2024-02-20 19:17 UTC, Majkl-J requested changes

2024-02-20 19:17 UTC, Majkl-J commented on modular_skyrat/modules/blueshield/code/blueshield.dm
> +	spawn_positions = 0 //BUBBER EDIT Original = 1
Same here
```suggestion
/datum/job/blueshield
	total_positions = 0
	spawn_positions = 0
```

2024-02-20 19:23 UTC, Swiftfeather commented on modular_skyrat/modules/blueshield/code/blueshield.dm
> +	//BUBBER ADDITION END
committed it modularly

2024-02-20 19:23 UTC, Swiftfeather commented on modular_skyrat/modules/blueshield/code/blueshield.dm
> +	spawn_positions = 0 //BUBBER EDIT Original = 1
committed it modularly

2024-02-20 19:25 UTC, nevimer commented
not sure im sold on it

2024-02-20 19:47 UTC, Swiftfeather commented
> not sure im sold on it

It feels like most of the time blueshield is played for the extended access and better weapons and gear, not so much to be a bodyguard to the heads of staff. When they do focus on guarding it's often just the captain; one of the most well equipped people on the station, going to check on other heads only when they are hurt or don't have maxed sensors. 

This makes antag roleplaying with captains pretty much impossible because the blueshield will have their gun out before the other person has even finished typing their first message. It makes it more difficult to do stuff with the rest of the heads too. When red alerts come on I've seen BS suddenly procure an entire armory and medbay from their bag they've been stockpiling the whole shift. 

Blueshields were added at a time when heads were constantly being annihilated, mostly because Skyrat was far more hugboxy at that point. I don't see the same issues here. 

NT rep feels far better in comparison as far as roleplaying goes with command, it makes sense, while Blueshield feels stuck back in the arms race gunsec era.

2024-02-20 21:53 UTC, AllCorruptingWyrm commented
I'm against Blueshield being touched, in fact I just made new regulations for the job that need to get parsed and approved.

2024-02-21 03:04 UTC, projectkepler-ru commented
I'll look over this in the coming days.

2024-02-21 11:08 UTC, Erol509 commented
Blueshield is very popular role, and people like it. Im aginst this PR.

2024-02-22 01:03 UTC, Sylphet commented
I like blueshield, this isn't great.

2024-02-22 02:18 UTC, projectkepler-ru commented
My say is final on this, it will be addressed later with an update to the role itself in a follow up PR and blueshield oversight.

2024-02-22 02:18 UTC, closed without merging

2024-02-23 10:09 UTC, ReturnToZender commented
While I don't like this PR, I _do_ sorta like the Blueshield having a beacon to drop their locker and equipment. It's just cool.