Toxin/Oxygen tending surgeries.
Bubberstation/Bubberstation pull request #1206
Opened 2024-02-25 10:46 UTC by xXPawnStarrXx

## About The Pull Request

These surgeries are for repairing toxin damage and oxygen damage to the patients, they're pretty much reskins of the brute and burn ones for their respective damage types.

## Why It's Good For The Game
While hopefully not as effective as using meds, adds a way to purge toxins on corpses and those with severe allergies.

## Proof Of Testing

## Changelog

:cl:
add: Added new surgical methods of restoring O2 and Toxin damage.
/:cl:

2024-02-25 10:47 UTC, xXPawnStarrXx commented
Drafted for now as I try to work out why the hell it's not removing toxin/suffocation damage when it's literally reskinned code.

2024-02-25 11:34 UTC, Majkl-J requested changes
I see no reason for the oxygen one to exist, the methods to tend oxygen are everything from CPR, epinephrine (Medbay has like 200u lying around just roudstart alone), self resp, mediguns. Half of the mentioned already take absolutely no effort whatsoever.

As for toxin, sure, it tends to be a pain to fix sometime. Use `adjustToxLoss` for that, and proobably make it forced so doctors don't murder slime people?

2024-02-25 11:44 UTC, xXPawnStarrXx commented
> I see no reason for the oxygen one to exist, the methods to tend oxygen are everything from CPR, epinephrine (Medbay has like 200u lying around just roudstart alone), self resp, other chems (Half are easy to make in a rush), mediguns. Half of the mentioned already take absolutely no effort whatsoever.

I more had the oxygen one in mind for people who can't breathe (Hemophages/synths) so they can't do CRP and as a holdover if someone's lungs had failed. I honestly don't see many doctors use much for suffocation besides CPR/Epi and if someone's allergic to oxy meds, just wanted the option there.

> As for toxin, sure, it tends to be a pain to fix sometime. Use `adjustToxLoss` for that, and proobably make it forced so doctors don't murder slime people?

I could try adjustToxLoss instead, I'll let you know.

2024-02-25 11:52 UTC, xXPawnStarrXx commented
> As for toxin, sure, it tends to be a pain to fix sometime. Use `adjustToxLoss` for that, and proobably make it forced so doctors don't murder slime people?

Sadly, doesn't work. Not a blip in toxins either way

2024-02-25 12:12 UTC, Majkl-J commented
> I more had the oxygen one in mind for people who can't breathe (Hemophages/synths) so they can't do CRP and as a holdover if someone's lungs had failed. I honestly don't see many doctors use much for suffocation besides CPR/Epi and if someone's allergic to oxy meds, just wanted the option there.

This was adressed on tg about a week ago with https://github.com/tgstation/tgstation/pull/81522

As for your other points, if your lungs fail the stasis beds prevent oxyloss, allowing you to stall for more than enough time to do a lobectomy. Epinephrine is blacklisted from allergies (And in fact is used to counter allergic reactions), so it is guaranteed to always work.

2024-02-25 12:17 UTC, Majkl-J requested changes
heal_bodypart_damage only heals brute and burn

2024-02-25 12:17 UTC, Majkl-J commented on modular_zubbers/modules/surgery/healing.dm
> +	target.heal_bodypart_damage(toxin_healed,oxygen_healed)
```suggestion
	target.adjustToxLoss(toxin_healed, forced = TRUE)
	target.adjustOxyLoss(oxygen_healed)
```

2024-02-25 12:24 UTC, xXPawnStarrXx commented
> heal_bodypart_damage only heals brute and burn
I KNEW there was something I forgot.

2024-02-25 12:43 UTC, aKromatopzia commented
Surgery for toxins already exist. Stomach pumping.

2024-02-25 13:01 UTC, Majkl-J commented
> Surgery for toxins already exist. Stomach pumping

Oh yea that's true, I may have forgotten that one

https://github.com/Bubberstation/Bubberstation/blob/8e395113e855dc71e8ffa09b1d90818d682ae6c5/code/modules/mob/living/carbon/carbon.dm#L456

> why toxin damage is being repaired with a hemostat.

![image](https://github.com/Bubberstation/Bubberstation/assets/49160555/e0a7e55f-db4d-4c5e-ba57-1dbb28960402)

2024-02-25 13:15 UTC, xXPawnStarrXx commented
> Surgery for toxins already exist. Stomach pumping. If you need one for corpses, just revive them on a stasis bed then pump their guts. Alternatively, you could make the blood filtering surgery do toxin healing, so nobody has to ask why toxin damage is being repaired with a hemostat.

I have it set to bloodfilter, also I don't want to remove reagents, I want one for toxin damage.

2024-02-25 14:27 UTC, xXPawnStarrXx commented
For now, I've opened the bloodfiltering PR on TG itself, if it gets approved, I'll open a new PR to get it here quicker, if not. I will open it here as a //BUBBER EDIT//

2024-02-25 18:10 UTC, xXPawnStarrXx commented
I have no idea why the maps are failing. I've changed so little now.

2024-02-25 19:30 UTC, nevimer commented
don't worry about the maps, only meta and delta are needed to pass

2024-02-25 19:32 UTC, xXPawnStarrXx commented
> don't worry about the maps, only meta and delta are needed to pass

I'm guessing screenshots comparison doesn't matter either, since... Y'know, they're not being changed.

2024-02-25 19:33 UTC, nevimer commented
> > don't worry about the maps, only meta and delta are needed to pass
> 
> I'm guessing screenshots comparison doesn't matter either, since... Y'know, they're not being changed.

ill fix that for you

2024-02-26 06:45 UTC, Majkl-J approved these changes
Looks good for testmerging, might need to be lowered if it's too op but we can't tell without a TM.

2024-03-16 19:29 UTC, sneksnek commented
The math on this PR is wrong. It takes a little around 2 seconds for a cycle to pass, resulting in one tick of metabolization. At 100% purity and 1000K temperature, seiver will heal 5 toxin each tick. This means it would be (give or take, depending on how the server is chugging), 2.5 toxin per second.

Completing a blood filtration takes 2.22 seconds on a stasis bed in default conditions (no upgrades, clean medbay, roundstart). At -2 toxin per operation, blood filtration would be 0.9 toxin/second.

Completing a stomach pump takes a flat 2 seconds on a stasis bed under the same conditions. It causes the patient to vomit, which heals 3 toxin. Effectively this is -3 toxin per operation, or 1.5 toxin/second.

A roundstart multiver pill + epinephrine heals 1.5 toxin/tick, or 0.75 toxin/second. Cryotubes heal about 2 toxin per tick at unupgraded temperatures, or 1 toxin/second.

I'm throwing these numbers out for comparison. As it is currently suggested by the PR with -2 toxin per operation, I think it is decently balanced. It's objectively worse than simply pumping the stomach, slightly worse than cryoxadone, moderately worse than seiver at maximal efficacy, and significantly worse than a proper IV mix. It fulfills the niche of healing toxin damage from a patient that lacks a stomach either due to organ loss or species specifications. One could argue that this will expediate the process of filtering someone's bloodstream whilst reducing their toxin damage as well now, but eh. They're already on a stasis bed likely and the next step was a stomach pump or a hit of seiver anyways. At any rate, it's still superior to purge with chemicals then heal with chemicals.

I deem this a SOUND PR and you have earned my THUMBS UP.

2024-03-20 07:40 UTC, merged