Add two colourable variations of "monster mouth" body marking, greyscale variation of "Body weight"
Bubberstation/Bubberstation pull request #1234
Opened 2024-03-03 09:26 UTC by iskawhiskers

## About The Pull Request

Self-explanatory. Adds four altered versions of existing body marking sprites; two colourable variations of the "monster mouth" marking, with one adjusted to fit eyes, and a greyscale version of each gender of the "Body weight" marking.  Original versions have not been removed.

Not tested.

## Why It's Good For The Game

Sprite addition good

## Proof Of Testing

It's icons

## Changelog

:cl:
image: four new sprite sheets (monster2_head, monster3_head, weight2_body_m, weight2_body_f)
code: entries for each of the aforementioned sprite sheets
/:cl:

2024-03-05 15:34 UTC, Majkl-J requested changes

2024-03-05 15:34 UTC, Majkl-J commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/body_markings/body_markings.dm
> +
Move these to a folder under modular_zubbers, and link the icon file with `icon='filepath'`

2024-03-05 15:34 UTC, Majkl-J commented on modular_skyrat/modules/customization/modules/mob/dead/new_player/body_markings/body_markings.dm
> +
Same as above

2024-03-05 15:34 UTC, Majkl-J commented on modular_skyrat/master_files/icons/mob/body_markings/other_markings.dmi
This will end up being overriden by upstream merges. create a new icon file under modular_zubbers

2024-03-07 23:44 UTC, iskawhiskers commented
Moved to https://github.com/Bubberstation/Bubberstation/pull/1249, use that instead

2024-03-07 23:52 UTC, closed without merging