adds "Butler" Assistant alternate title
Bubberstation/Bubberstation pull request #1250
Opened 2024-03-08 00:06 UTC by Boviro

Adds Butler alt title for assistant

## About The Pull Request

Adds 1 line, 9 characters to alt_job_titles.dm, adding Butler as an assistant alt title

## Why It's Good For The Game

Adds some refined butlerly spirit to our beloved, but unrefined, Bubberstation.

## Proof Of Testing

Tested: Compiles and runs without errors and functions properly in-game
![image](https://github.com/Bubberstation/Bubberstation/assets/99471923/f0a0e2fc-9192-4213-9332-e286cdfd1571)
![image](https://github.com/Bubberstation/Bubberstation/assets/99471923/6adf38f4-ced0-42ef-8e32-4e4be4b6d05c)
![image](https://github.com/Bubberstation/Bubberstation/assets/99471923/ced7a9fa-b42b-49ce-8a49-c9920cdd0913)
![image](https://github.com/Bubberstation/Bubberstation/assets/99471923/4b2d1857-f902-4cf8-ab96-29c0407ec4a3)

## Changelog

add: new Butler alt title for assistant

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-03-08 10:34 UTC, projectkepler-ru commented on modular_skyrat/modules/alternative_job_titles/code/alt_job_titles.dm
> +		"Butler",
```suggestion
		"Butler", //Bubber Addition
```

2024-03-08 10:36 UTC, projectkepler-ru commented
Oh for fuck sake

2024-03-08 10:50 UTC, projectkepler-ru approved these changes
Honestly, you could just do this on upstream skyrat but its fine otherwise

2024-03-08 11:51 UTC, Majkl-J requested changes
Make modular with
```
/datum/job/assistant/New()
	alt_titles += list("Butler")
```

2024-03-08 23:00 UTC, Boviro commented
so adding alt titles in the modular_zubbers alt_job_titles.dm , as opposed to the modular_skyrat alt job titles module, correct?

2024-03-09 07:47 UTC, Majkl-J commented
> so adding alt titles in the modular_zubbers alt_job_titles.dm , as opposed to the modular_skyrat alt job titles module, correct?

Yup!

2024-03-09 08:07 UTC, Boviro commented
Hold please. Need to test locally first to ensure the change worked.

2024-03-09 08:41 UTC, Boviro commented
Can confirm: Functions as intended

2024-03-10 12:42 UTC, Majkl-J approved these changes
Code looks solid

2024-03-13 16:56 UTC, merged