[MODULAR] Adds height scaling
Bubberstation/Bubberstation pull request #1264
Opened 2024-03-12 02:08 UTC by nikothedude

## About The Pull Request

Title. 

You can now set your characters height using TG's height scaling. Works with size scaling.

## Why It's Good For The Game

Size scaling is ass. Its just fucking ass. Most people who use it want it as a representation of their charactyers height and have to ENTIRELY SHRINK or GROW. It SUCKS. I want to play a tall or short character that isnt SHRUNK or INFLATED.

## Proof Of Testing

![image](https://github.com/Bubberstation/Bubberstation/assets/59709059/73e055db-a6a2-4e86-bb99-4cde61375bf5)

Humans, left to right: 0.8 size scaling, shortest scaling. Shortest, short, medium, tall, taller, tallest.
Teshari, left to right: Shortest, Tallest.
The taur is a 1.2 size scaling with oversized and tallest, the absolute extreme. The weird artifating on the bottom happens on most taurs, and is avoidable by not selecting tallest.

## Changelog

:cl:
add: You can now set your characters height
/:cl:

2024-03-12 02:09 UTC, nikothedude commented
yes the tesh have weird legs, my tesh has cybernetic legs

2024-03-12 02:10 UTC, nikothedude commented
I FORGOT

2024-03-12 02:23 UTC, ReturnToZender commented
Love this!!

2024-03-12 03:11 UTC, AllCorruptingWyrm commented
THANK GOD

2024-03-12 13:30 UTC, Majkl-J requested changes
So it's together with the other pref

2024-03-12 13:30 UTC, Majkl-J commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/bubbers/height_scaling.tsx
> +  name: 'Height',
```suggestion
  name: 'Body Height',
```

2024-03-12 20:09 UTC, Majkl-J reviewed
This is cool and all but
![image](https://github.com/Bubberstation/Bubberstation/assets/49160555/17a814f7-ac13-44f4-acd0-b39e2c701ad9)
![image](https://github.com/Bubberstation/Bubberstation/assets/49160555/2ea40e7c-4fda-431b-b78a-7aa21547bb7d)

Yea the performance on these chokes a lot

2024-03-12 20:13 UTC, nikothedude commented
> This is cool and all but ![image](https://private-user-images.githubusercontent.com/49160555/312222639-17a814f7-ac13-44f4-acd0-b39e2c701ad9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzQ2MzEsIm5iZiI6MTcxMDI3NDMzMSwicGF0aCI6Ii80OTE2MDU1NS8zMTIyMjI2MzktMTdhODE0ZjctYWMxMy00NGY0LWFjZDAtYjM5ZTJjNzAxYWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDIwMTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMmU4MzRmODU5MDhjODljYjI0YjBkN2UxYWZjOTdiODEyNDIzNThhMjY5MDQ4ZTdmMzlhMDYwZDg3MjkzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UkfNULU3Ji304eJaf4a8Scdrvpq9iic7Z3QVwJVug_w) ![image](https://private-user-images.githubusercontent.com/49160555/312222725-2ea40e7c-4fda-431b-b78a-7aa21547bb7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNzQ2MzEsIm5iZiI6MTcxMDI3NDMzMSwicGF0aCI6Ii80OTE2MDU1NS8zMTIyMjI3MjUtMmVhNDBlN2MtNGZkYS00MzFiLWI3OGEtN2FhMjE1NDdiYjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDIwMTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NmU1MDljYTUyYWYwYjFjODkyOGE2MTU0NzRjMjJjNDk3MmJlNjEwYjY0ZTllZmJlMDFjODJlNzk4ZTRlMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KOBcf20duKfJ5ll8CzBKmpMiwTt0Cm4WEhdY8ADHF30)
> 
> Yea the performance on these chokes a lot

is this from live?

2024-03-12 20:14 UTC, Majkl-J commented
> is this from live?

Yup freshly profiled

2024-03-12 20:14 UTC, nikothedude commented
its worth noting that dwarfs and spacer both use the same exact framework as this

2024-03-12 20:15 UTC, nikothedude commented
ill look into this to see if it can be optimized but if not we'll have to consider if this is worth the cost

2024-03-13 07:07 UTC, Majkl-J approved these changes
Optimizations actually made this run so fast its impact is barely noticeable.

Anyhow yes approved I'll look to merging this after like a week, needs some testing period

2024-03-14 09:40 UTC, HissyNays commented
This is a pretty good attempt. However I feel like some of my characters got messed up and I don't know how to fix them. 
What needs to be actually made is two sliders, one for height, one for width of your character's sprite. That way it will be the most customizable and best. I've seen a different server do it and it was amazing.

2024-03-17 23:26 UTC, Arturlang commented
What happens if you have both the spacer quirk and increase your height?

2024-03-18 08:52 UTC, IgiariValkyr commented
Cuts off the top of your sprite if it goes over the 32 pixel limit.
![dreamseeker_2024-03-18_03-51-31](https://github.com/Bubberstation/Bubberstation/assets/5521322/4bf76a88-6480-413b-820f-d1cb3dae5b50)
![dreamseeker_2024-03-18_03-51-02](https://github.com/Bubberstation/Bubberstation/assets/5521322/c73cbcbb-18ce-4da1-9f43-a40d2fff5f54)

2024-03-21 16:51 UTC, nikothedude commented
> Cuts off the top of your sprite if it goes over the 32 pixel limit. ![dreamseeker_2024-03-18_03-51-31](https://private-user-images.githubusercontent.com/5521322/313608676-4bf76a88-6480-413b-820f-d1cb3dae5b50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDAxMjUsIm5iZiI6MTcxMTAzOTgyNSwicGF0aCI6Ii81NTIxMzIyLzMxMzYwODY3Ni00YmY3NmE4OC02NDgwLTQxM2ItODIwZi1kMWNiM2RhZTViNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTY1MDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc2Yzk1NTU2OTQxNzAwZmQ2YTM5ZTZjYjQxM2U4NjNjNzczOGQ4Mjg4NmRlYWRhZGE2ZjBkYjkxZjFjZGEyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IO5WtnTuvgO-eN-QEtX_gyhzxfyTPKUlsjUVfeOzqK4) ![dreamseeker_2024-03-18_03-51-02](https://private-user-images.githubusercontent.com/5521322/313608680-c73cbcbb-18ce-4da1-9f43-a40d2fff5f54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDAxMjUsIm5iZiI6MTcxMTAzOTgyNSwicGF0aCI6Ii81NTIxMzIyLzMxMzYwODY4MC1jNzNjYmNiYi0xOGNlLTRkYTEtOWY0My1hNDBkMmZmZjVmNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTY1MDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM5NGQ0Nzg3NzMxM2FlNzNiNDY1ZWQyMjgyMjgzMGNmYzdkODJkMzU2MzM4YzAyMjk5MjE1YTFmOWExZGFlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UEAfe9dp5TT6qeZWRRKHCazcfbaB-PVlcZIU18vZcV4)

Not sure how to fix this but I doubt I can, itd need to be a TG fix

2024-03-21 16:53 UTC, ReturnToZender commented
As a tall dude that doesn't take up a whole tile I am winning

2024-03-22 11:50 UTC, Iamgoofball commented
this causes issues for client-side performance, filters aren't cheap, please consult @MrMelbert before proceeding

2024-03-22 13:27 UTC, Majkl-J commented
> this causes issues for client-side performance, filters aren't cheap, please consult @MrMelbert before proceeding

Already did
https://github.com/Bubberstation/Bubberstation/pull/1264/commits/caab4e479a1c90f5f8c53e8c8cc8d773573cad88

2024-03-22 13:52 UTC, Iamgoofball commented
did you read the code you linked before replying to me

2024-03-22 13:56 UTC, Majkl-J commented
> did you read the code you linked before replying to me

This is specifically what melbert has given to me and niko when we asked him about the problem. So yes

2024-03-22 14:18 UTC, Iamgoofball commented
if you had read the words i wrote you would see i am talking about clientside performance, not serverside performance

2024-03-22 14:28 UTC, Majkl-J commented
> if you had read the words i wrote you would see i am talking about clientside performance, not serverside performance

This is all we were given. Stuff has been testmerged for a while now with no issues. I dunno what to tell you

2024-03-27 21:04 UTC, merged

2024-03-29 17:27 UTC, IgiariValkyr commented
> > Cuts off the top of your sprite if it goes over the 32 pixel limit. ![dreamseeker_2024-03-18_03-51-31](https://private-user-images.githubusercontent.com/5521322/313608676-4bf76a88-6480-413b-820f-d1cb3dae5b50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDAxMjUsIm5iZiI6MTcxMTAzOTgyNSwicGF0aCI6Ii81NTIxMzIyLzMxMzYwODY3Ni00YmY3NmE4OC02NDgwLTQxM2ItODIwZi1kMWNiM2RhZTViNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTY1MDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc2Yzk1NTU2OTQxNzAwZmQ2YTM5ZTZjYjQxM2U4NjNjNzczOGQ4Mjg4NmRlYWRhZGE2ZjBkYjkxZjFjZGEyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IO5WtnTuvgO-eN-QEtX_gyhzxfyTPKUlsjUVfeOzqK4) ![dreamseeker_2024-03-18_03-51-02](https://private-user-images.githubusercontent.com/5521322/313608680-c73cbcbb-18ce-4da1-9f43-a40d2fff5f54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNDAxMjUsIm5iZiI6MTcxMTAzOTgyNSwicGF0aCI6Ii81NTIxMzIyLzMxMzYwODY4MC1jNzNjYmNiYi0xOGNlLTRkYTEtOWY0My1hNDBkMmZmZjVmNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjFUMTY1MDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWM5NGQ0Nzg3NzMxM2FlNzNiNDY1ZWQyMjgyMjgzMGNmYzdkODJkMzU2MzM4YzAyMjk5MjE1YTFmOWExZGFlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UEAfe9dp5TT6qeZWRRKHCazcfbaB-PVlcZIU18vZcV4)
> 
> Not sure how to fix this but I doubt I can, itd need to be a TG fix

This issue was never fixed.

2024-03-29 17:28 UTC, nikothedude commented
I know