Two new sushis???
Bubberstation/Bubberstation pull request #129
Opened 2023-03-23 17:59 UTC by toastywaffelz

Added two new sushis, the neko roll, and the nekobara roll. Modularized I think??? Not tested at all?? I still have no idea how to format a PR??????

adds: items, icons, recipes

Why is this change beneficial? It's sushi!!!

2023-03-24 05:52 UTC, mcmeiler requested changes
The PR template is automatically written when you create a new PR - you just deleted it and wrote this, instead.

The PR contains a ton of duplicate recipes in the modular files.

Changelog, please, while you're at it.

2023-03-24 05:52 UTC, mcmeiler commented on modular_zubbers/code/modules/food_and_drinks/recipes/tablecraft/recipes_seafood.dm
> +/datum/crafting_recipe/food/cubancarp
Why'd you duplicate a bunch of code from other files here?

2023-03-24 05:52 UTC, mcmeiler commented on modular_zubbers/code/game/objects/items/food/misc.dm
> +/obj/item/food/watermelonslice
ditto

2023-03-24 06:32 UTC, toastywaffelz commented
lmao I was told to just 'copy the files and their paths' for modularization, nobody told me that I could shave off duplicate code, its done now I think??

2023-03-25 10:03 UTC, toastywaffelz commented
OKAY I HAD BRAIN DAMAGE FIXING THIS

but I tested it and can confirm it works!!!!!! YAY!!!

2023-03-25 16:07 UTC, mcmeiler approved these changes

2023-03-25 18:22 UTC, 567Turtle approved these changes
Besides the absolute abhorrent formatting I don't really see anything wrong with this, it's fine

2023-03-27 09:45 UTC, merged