[MOSTLY MODULAR] Nanotrasen Representative Additions
Bubberstation/Bubberstation pull request #1364
Opened 2024-04-09 02:00 UTC by ChromeFoxxity

## About The Pull Request

Makes some additions within a few NT Rep Offices, as well as adds the CentCom sabre to said NT Rep's locker. Does less force than the average captain's sabre. As well as an addition of a few cosmetic pieces into their garment bag.

## Why It's Good For The Game

It's purely cosmetic, and maybe a bit of a balance change with the new sword. But I'm sure it'll be fine considering you can already buy one from Cargo.

## Proof Of Testing

This is untested due to Visual Studio Code breaking every time I try to run it. I apologize, but I'm sure it is working perfectly.
![image](https://github.com/Bubberstation/Bubberstation/assets/114542226/5623092c-5d8b-4ec1-bfa5-6a3316e7c351)

## Changelog

:cl:
add: Official's suit to the Representative's garment bag.
add: CentCom sword sabre to the Representative's locker.
balance: Added a shift-start sword for the Representative.
image: Added modular icons for sword and sheath.
code: Added modular code for sword and sheath.
/:cl:

![image](https://github.com/Bubberstation/Bubberstation/assets/114542226/81e382b4-089b-47c7-afb8-90ff41505fcf)

2024-04-09 03:24 UTC, ReturnToZender commented
I think your branch is super out of date with Master, you have a bunch of map changes that don't really have anything to do with your PR

2024-04-09 03:47 UTC, ChromeFoxxity commented
> I think your branch is super out of date with Master, you have a bunch of map changes that don't really have anything to do with your PR
> 
> Also the block chance and armor penetration need to be reduced, the cargo sabre has 20 and 25, the captain's saber has 50 and 75, to give you a reference of where the values need to be at most

I'll be honest here, I also think it may be outdated. My branches got a little screwed up. Let me try fixing it.

2024-04-09 04:01 UTC, ChromeFoxxity commented
> I think your branch is super out of date with Master, you have a bunch of map changes that don't really have anything to do with your PR
> 
> Also the block chance and armor penetration need to be reduced, the cargo sabre has 20 and 25, the captain's saber has 50 and 75, to give you a reference of where the values need to be at most

Also, what do you mean several map changes? I've only changed 15 files, from what the github says.

2024-04-09 15:54 UTC, ChromeFoxxity commented
> > > I think your branch is super out of date with Master, you have a bunch of map changes that don't really have anything to do with your PR
> > > Also the block chance and armor penetration need to be reduced, the cargo sabre has 20 and 25, the captain's saber has 50 and 75, to give you a reference of where the values need to be at most
> > 
> > 
> > Also, what do you mean several map changes? I've only changed 15 files, from what the github says. And, those map changes are additions to the offices as I've said.
> 
> You misunderstood, they meant that the changes in the automapper, some of them do not line up and appear to be out of date

Ah, I see.. I think it is unfortunately broken, yes.

2024-04-09 15:56 UTC, ChromeFoxxity commented
> > > I think your branch is super out of date with Master, you have a bunch of map changes that don't really have anything to do with your PR
> > > Also the block chance and armor penetration need to be reduced, the cargo sabre has 20 and 25, the captain's saber has 50 and 75, to give you a reference of where the values need to be at most
> > 
> > 
> > Also, what do you mean several map changes? I've only changed 15 files, from what the github says. And, those map changes are additions to the offices as I've said.
> 
> You misunderstood, they meant that the changes in the automapper, some of them do not line up and appear to be out of date

Is there a way to fix this swiftly? I don't think I can do it in this same PR.

2024-04-09 16:07 UTC, ChromeFoxxity commented
> > > > I think your branch is super out of date with Master, you have a bunch of map changes that don't really have anything to do with your PR
> > > > Also the block chance and armor penetration need to be reduced, the cargo sabre has 20 and 25, the captain's saber has 50 and 75, to give you a reference of where the values need to be at most
> > > 
> > > 
> > > Also, what do you mean several map changes? I've only changed 15 files, from what the github says. And, those map changes are additions to the offices as I've said.
> > 
> > 
> > You misunderstood, they meant that the changes in the automapper, some of them do not line up and appear to be out of date
> 
> Is there a way to fix this swiftly? I don't think I can do it in this same PR.

Actually, wait. Give me a moment, I'm gonna try to rebase it.

2024-04-09 17:01 UTC, YakumoChen commented
I'm pretty skeptical why they need a sword in the first place

Sure they can buy one from cargo but we've already made a point of disarming their roundstart weaponry before.

2024-04-09 17:23 UTC, ChromeFoxxity commented
> I'm pretty skeptical why they need a sword in the first place
> 
> Sure they can buy one from cargo but we've already made a point of disarming their roundstart weaponry before.

It's for formality, it isn't THAT bad, it might be even worse than the one from cargo if it needs be.

2024-04-09 17:46 UTC, YakumoChen commented
Sabres as decoration is something usually given to military officers or similarly high authority, of which the Consultant (not rep, the NTC is not a rep) is neither

2024-04-09 17:50 UTC, ChromeFoxxity commented
> Sabres as decoration is something usually given to military officers or similarly high authority, of which the Consultant (not rep, the NTC is not a rep) is neither

They have alternate titles of "Representative", their office is also named "ntrep's office", in code. They are a representative, for all I could care.

2024-04-09 18:33 UTC, IgiariValkyr commented
Add it anyways for the admins and their admiral characters. This is a threat. Here's a piece of paper with a gun drawn on it to threaten you to adding it anyways.
![maxresdefault](https://github.com/Bubberstation/Bubberstation/assets/5521322/abf10e00-120d-43bb-83d3-16828958864a)

2024-04-09 18:59 UTC, YakumoChen commented
> > Sabres as decoration is something usually given to military officers or similarly high authority, of which the Consultant (not rep, the NTC is not a rep) is neither
> 
> They HAD alternate titles of "Representative", their office is also named "ntrep's office", in code. They are also just as luxurious as the Captain when it comes to their clothes, they might be intern-level, but this is pretty much just for luxury.

HAD is a key word. They aren't reps, they have no authority, they're corporate lawyers with bridge access.

2024-04-09 20:02 UTC, ChromeFoxxity commented
> > > Sabres as decoration is something usually given to military officers or similarly high authority, of which the Consultant (not rep, the NTC is not a rep) is neither
> > 
> > 
> > They HAD alternate titles of "Representative", their office is also named "ntrep's office", in code. They are also just as luxurious as the Captain when it comes to their clothes, they might be intern-level, but this is pretty much just for luxury.
> 
> HAD is a key word. They aren't reps, they have no authority, they're corporate lawyers with bridge access, and they don't need a sword. They shouldn't be treated like decorated officers.

They quite literally have a heavy rifle, like the Captain. Besides, they're basically treated like representatives. I don't know what your issue is with this. It's barely gonna change anything due to the fact every NTC buys a sword.

2024-04-10 05:50 UTC, projectkepler-ru commented
> > Sabres as decoration is something usually given to military officers or similarly high authority, of which the Consultant (not rep, the NTC is not a rep) is neither
> 
> They HAD alternate titles of "Representative", their office is also named "ntrep's office", in code. They are also just as luxurious as the Captain when it comes to their clothes, they might be intern-level, but this is pretty much just for luxury.

this point is moot, file name for things are usually there for convenient sake rather than to be taken literally

2024-04-10 05:54 UTC, projectkepler-ru commented on modular_zubbers/code/game/objects/items/storage/belt.dm
> +	worn_icon_state = "cc_sheath"
This is failing the worn icon test please re-check that your file are working correctly

2024-04-10 05:55 UTC, projectkepler-ru commented
> > > Sabres as decoration is something usually given to military officers or similarly high authority, of which the Consultant (not rep, the NTC is not a rep) is neither
> > 
> > 
> > They HAD alternate titles of "Representative", their office is also named "ntrep's office", in code. They are also just as luxurious as the Captain when it comes to their clothes, they might be intern-level, but this is pretty much just for luxury.
> 
> HAD is a key word. They aren't reps, they have no authority, they're corporate lawyers with bridge access, and they don't need a sword. They shouldn't be treated like decorated officers.



they can have it, not a huge loss, the sword stats quite weak anyway

2024-04-10 05:56 UTC, projectkepler-ru requested changes
If the failing unit test can be resolved It'll get merged

2024-05-22 15:37 UTC, closed without merging