[MODULAR] Dauntless map tweaks and bounty pad
Bubberstation/Bubberstation pull request #1374
Opened 2024-04-10 01:50 UTC by tmyqlfpir

## About The Pull Request

This PR tweaks the following things for dauntless lava ruins:
* Removes improperly copied decals under hull tiles
* Adjusts the recreational area for the brig
* Adds many exterior cameras to the dauntless, and removes many interior ones (except for those in brig & interrogation)
* Adds a maxcap of 1MW to the powerator
* Adds a modified pirate bounty pad that allows the Dauntless crew to sell off goods for credits
* Adds a produce order console to the kitchen which is linked to the Interdyne budget account
* Adds a new area variable called `ignore_weather_sfx` which bypasses weather sfx (this is applied to the Dauntless)

## Why It's Good For The Game

This PR removes the possibility for the AI to go snooping in the Dauntless super sekret base, and can only view the exterior. It also tweaks areas such as dorms and brig to be easier on both the eyes and for movement.

The new bounty pad will allow players to use alterative forms of money, be it selling off the ore from netrunner gaming den, or other making goods for credits. This means they are not relying on using the powerator (which has been capped at 1MW).

## Proof Of Testing

I have ran this map on my local server and confirm it works.

The bounty pad works and I have ensured that there are enough sanity checks for it to not crash or break anything. It should not affect on station cargo prices.

https://github.com/Bubberstation/Bubberstation/assets/80724828/f8b5210a-4664-4c4b-8c6e-be17385f41c2

## Changelog

:cl:
add: Dauntless - Add exterior cameras to dauntless, removed many interior ones
fix: Dauntless - Removed incorrectly placed decals under hull objects and tweaked brig/dorms
balance: Interdyne powerator is now maxcapped to 1MW
add: Dauntless - Added new bounty pad and bounty console
add: Dauntless - Added new produce order console
/:cl:

2024-04-12 03:18 UTC, Mewchild commented
I can't support the pAI being in the prison, as it gives access to both PDA messaging, comms, and a doorjack.

2024-04-15 03:36 UTC, shellspeed1 commented
One request from me, could we look at a produce console?

2024-04-15 03:58 UTC, shellspeed1 commented
Pardon, its specifically the service order console, I'll throw a screenshot up in a bit here.

2024-04-15 06:11 UTC, shellspeed1 commented
![Tram Station Example](https://github.com/Bubberstation/Bubberstation/assets/46614774/984bee5c-b192-4d75-b94d-b72be9351ddf)

2024-04-17 05:55 UTC, Majkl-J requested changes

2024-04-17 05:55 UTC, Majkl-J commented on modular_zubbers/code/game/machinery/computer/orders/order_computer/cook_order_interdyne.dm
> +	)
This is inherited from parent iirc

```suggestion
```

2024-04-17 05:55 UTC, Majkl-J commented on modular_zubbers/code/game/machinery/computer/orders/order_computer/cook_order_interdyne.dm
> + */
So I am curious, would just giving all of the crew links to the account on their IDs be easier than rewriting all this? I suggest you give it a shot, could make a lot of this code more elegant.

Probably has to be showed into a post_equip on the loadouts.

2024-04-17 06:44 UTC, Majkl-J commented on modular_zubbers/code/game/machinery/computer/orders/order_computer/cook_order_interdyne.dm
> + */
> Perhaps I should default back to the current ID holder's account instead.

We could provide the admiral or whatever the highest rank is, with a card linked to the account so they can sort out payments to the crew if we do this.

2024-04-19 06:32 UTC, Majkl-J approved these changes

2024-04-19 06:33 UTC, merged