Adds Big Fat Security Glocks
Bubberstation/Bubberstation pull request #1400
Opened 2024-04-18 13:56 UTC by BurgerLUA

## About The Pull Request

![image](https://github.com/Bubberstation/Bubberstation/assets/8602857/3fd6d48a-28ea-459e-ab92-96a3d8535c41)

Sprite from Skyrat

Adds 9mm Security Glocks to Security Officer + HoS lockers, as well as cargo. You can purchase ammo from cargo or print it with the appropriate technode researched. Compared to the Syndicate Markov, it is significantly weaker.

**To prevent misuse, the guns are fitted with a firing pin that prevents use on code green.** There is nothing stopping you from swapping it out with another firing pin, however.

Here is a funny table

| Weapon Name | Firerate | Magazine Size | Damage Multiplier | Damage Per Hit (Normal) | Damage Per Hit (Flathead) | Damage Per Second (Normal) |
| --- | --- | --- | --- | --- | --- | --- |
| Syndicate Makarov | Server's Tickrate | 8 | x1.00 | 30 | 24 | 150 DPS* |
| Laser Gun | 0.4 seconds | 20 (Per Charge) | x1.00 | 22 | x | 55 DPS |
| WT-551 | 0.3 seconds | 20 | x1.00 | 20 | 18 | 67 DPS |
| Black Glock (Security) | 0.3 seconds | 8 |  x0.70 | 21 | 17.5 | 70 DPS |
| Silver Glock (HoS) | 0.2 seconds | 8 | x0.80 | 24 | 20 | 125 DPS |

 \* Assuming you can shoot and hit 5 rounds in a second.

## Why It's Good For The Game

Security needs more ballistics. Ballistics good. Security also needs a way to actually defend themselves.

## Proof Of Testing

I need to still test if the research nodes work fine, as well as the munitions workbench.

## Changelog

:cl: BurgerBB
add: Adds Big Fat Security Glocks
fix: Fixes some WT-551 ammo errors.
/:cl:

2024-04-18 14:01 UTC, Majkl-J approved these changes
Will need a TM to see how it goes but code looks good

2024-04-18 14:01 UTC, Majkl-J commented on modular_zubbers/modules/security_glock/cargo.dm
> +	desc = "Contains a pair of Black MOCK-9mm pistols pre-loaded with less-than-lethal rubber-tipped rounds. Additional ammo sold seperately. NanoTrasen reminds you that the other weapon is for a friend
You and I both know what could've been

2024-04-19 04:27 UTC, Wolf-751 commented
![Screenshot 2024-04-19 062429](https://github.com/Bubberstation/Bubberstation/assets/128626963/1f3511d6-c108-4166-a2f7-ea401a0fb6c1)
want a custom inhand too?

2024-04-19 05:07 UTC, Swiftfeather commented
god i love gock

2024-04-19 07:49 UTC, IgiariValkyr commented
As long as we get the alt-skins for it too, I'll be fine. Love my generic 9mm pistol.

2024-04-19 11:01 UTC, BurgerLUA commented
> As long as we get the alt-skins for it too, I'll be fine. Love my generic 9mm pistol.

alt skins do not exist for it

2024-04-20 14:44 UTC, BurgerLUA commented
Research works. Good to testmerge. I am prepared for people on discord to @ me over this PR for being insane.

2024-04-26 07:57 UTC, Majkl-J requested changes

2024-04-26 07:57 UTC, Majkl-J commented on modular_zubbers/icons/obj/guns/sec_pistol.dmi
Which skyrat PR/file is this from, considering you had to add this into our files.

2024-04-26 09:37 UTC, BurgerLUA commented on modular_zubbers/icons/obj/guns/sec_pistol.dmi
It's from ``modular_skyrat/modules/aesthetics/guns/icons/guns.dmi``

They had to be moved from another file because the sprites were not properly formatted for /tg/ pistols.

2024-04-28 02:14 UTC, NanoCats commented
Can you please make it so that we can change the name and description like some other weapons so I can change mine to the Gock.

2024-04-28 03:38 UTC, Swiftfeather commented
Can you just rename every mention of glock to gock?

2024-05-01 07:12 UTC, projectkepler-ru commented
gock

2024-05-02 14:28 UTC, projectkepler-ru approved these changes
balance wise, you get a pass from me, this is actually an interesting alternative to the wespe and eland, given the sol guns mag require plastic, thus, they are not as available during lower pop or if chemist isnt putting out a lot, as shotgun ammo box take priority.

more ammo type to keep track of in sec arsenal, but, not a big deal.

2024-05-02 15:04 UTC, BurgerLUA commented
It's not balanced in the slightest. I'm going to be making slight changes.

2024-05-22 14:19 UTC, merged