Adds Research cyborgs [Modularish] (oh no)
Bubberstation/Bubberstation pull request #1407
Opened 2024-04-21 06:12 UTC by pixelkitty286

## About The Pull Request

This PR added a new module for cyborgs it also replaces the malfunctioning AI cyborg factory with the ability when hacked to manufacture cyborgs manually (Cyborg building CO-OP)

The PR also adds a research cyborg exclusive jaunting module, much like the ninja energy sword and hierophant, when they are emagged or hacked.

An alterative way was added to remove cells on cyborgs to allow for cyborgs to upgrade ONLY cells. Other upgrades are restricted to balance them.

## Why It's Good For The Game

I've always wondered why the research department never had cyborgs of their own, but own them.

Research cyborgs are for a dedicated cyborg type assisting the research department.

Disabling the robot factory was done because the printer would just shit 3 to 4 cyborgs at once and make them out of nothing.
It was replaced with Cyborg CO-OP to encourage the cyborgs and the AI to make cyborgs them self if they wish for more cyborgs.

Research cyborgs were given jaunting and a stun arm to hopefully allow them to evade capture. In other words they are to run when hunted as they are mostly defenseless (fighting back is a bad idea.)

## Proof Of Testing

NOTE: These images taken were during development and may be missing a few items.

Stock
![dreamseeker_zPm0yyoOZC](https://github.com/Bubberstation/Bubberstation/assets/78038207/267bb6d8-6042-451b-9678-7d7907f53bd0)

Fully upgraded
![dreamseeker_qyG5Oq1cav](https://github.com/Bubberstation/Bubberstation/assets/78038207/a53dffb1-2d75-4e0f-95f5-5971403c2c7d)

Emagged
![dreamseeker_nQcm41bycd](https://github.com/Bubberstation/Bubberstation/assets/78038207/2618afe6-8d04-40fe-a8bf-e8550e3e4fcf)
Note: NO EMAG
![dreamseeker_tNIapvYTHM](https://github.com/Bubberstation/Bubberstation/assets/78038207/98f76dcf-d042-474f-94f7-2d1923755524)

## Changelog

:cl:
add: Research cyborgs
add: ability to pry cyborg cells out 
del: disabled malf cyborg factory
qol: made an alt method removing cells
balance: rebalanced cyborg making
image: Sprites for research cyborgs
code: what ever needed to get the cyborgs working
/:cl:

2024-04-21 07:55 UTC, pixelkitty286 commented
upstream merge has caused new bugs and will have to put this on hold

2024-04-23 06:04 UTC, pixelkitty286 commented
oh uh, it's ready

2024-04-23 06:41 UTC, StrangeWeirdKitten commented
qol: made an alt method removing cells
balance: rebalanced cyborg making
image: Sprites for research cyborgs
code: what ever needed to get the cyborgs working

Don't entirely need this in the changelog.

2024-04-23 06:44 UTC, pixelkitty286 commented
> qol: made an alt method removing cells balance: rebalanced cyborg making image: Sprites for research cyborgs code: what ever needed to get the cyborgs working
> 
> Don't entirely need this in the changelog.

I'm just used to doing that since I was required to where I last made PRs at.

2024-04-23 11:49 UTC, pixelkitty286 commented
Got a round in to test my stuff.  The module mostly works only problem ran into seems to being unable to pick up rods or eject some stuff, mainly cells, I will be adding rods as a pick up and synth repairs are kinda scuffed, but I will be looking more into it the more I test in real rounds (I can not add any more items kinda at the limit) Other than those two issues seems my local tests all worked as intended.
![dreamseeker_yvQzKjWJVT](https://github.com/Bubberstation/Bubberstation/assets/78038207/05eaf5e1-f2ce-463d-8acd-fc8a78f381bf)

2024-04-23 12:50 UTC, StrangeWeirdKitten commented
Why does it need the needle and the dropper?

2024-04-23 12:51 UTC, StrangeWeirdKitten commented
Also synths have this issue where some of the surgeries*might* require medical tools for surgery. But they should be capable of basic repair and revival

2024-04-23 14:12 UTC, ChaosCzar commented
> Why does it need the needle and the dropper?

For assisting with Xenobio duties, I'd assume.

2024-04-23 19:03 UTC, pixelkitty286 commented
> Also synths have this issue where some of the surgeries_might_ require medical tools for surgery. But they should be capable of basic repair and revival

I can add the tools required but do know if i do it the inventory will take half of the screen and also would pretty much make Medi borgs useless

2024-04-23 19:06 UTC, pixelkitty286 commented
> > Why does it need the needle and the dropper?
> 
> For assisting with Xenobio duties, I'd assume.

yes i was told to do such I will be taking suggestions to what items i should remove to cut bloat down

2024-04-23 19:46 UTC, pixelkitty286 commented
Added rods to be picked up by the sheet apparatus.

2024-04-23 21:49 UTC, pixelkitty286 commented
Stock RPED is broken this seems to be an issue upstream.

2024-04-25 23:25 UTC, YakumoChen commented
Initial thoughts is that malf changes should be atomised

The borg model itself also seems like fairly ludicrous power creep, being able to build more borgs and mechs and take out the robotics middle man is bonkers

2024-04-26 01:49 UTC, pixelkitty286 commented
> Initial thoughts is that malf changes should be atomised
> 
> The borg model itself also seems like fairly ludicrous power creep, being able to build more borgs and mechs and take out the robotics middle man is bonkers
> 
Mech building is allowed but you can not move them so good luck. Mod building is allowed but is very slow.

Borg building is locked be hind illegal tech and emag.
> It's almost all the best parts of engi and medborg plus a ton more
> 
Jessie what are you talking about
> Also "it's defenseless when emagged" but bro you can teleport and stun, that's the most powerful combo outside of "literally a gun"

The stun arm is really useless it has a cool off of 4 seconds.

Jaunting is not able to go though walls and has a penalty on using it 3200 KJ of power along with a reasonable cool down for recharge.

2024-04-26 02:06 UTC, StrangeWeirdKitten commented
> Initial thoughts is that malf changes should be atomised
No.

2024-04-28 16:50 UTC, R3dtail commented
As a gut reaction it doesn't feel really great that they can do most of robotics outside of moving the mechs.  Roboticist is already a very limited job that sometimes feels crowded with two people.  Sure, there's 'butting in and telling them to buzz off' but that's not fun for anyone to do.  It doesn't feel good to be replaced, borgs should be able to help, sure.  But being replaced doesn't feel great.

2024-04-29 01:48 UTC, pixelkitty286 commented
Added cyborg printing back since wow is it painful. Cyborg making is now optional.

2024-05-12 14:38 UTC, Eastwardrope commented
Borgs having that power is cool in theory but in practice it ends up being way way too powerful. One of the main weaknesses of borgs is requiring them to have a human to do basic maintence. I think the battery swap thing should take a long period of time to do(something like 10 seconds) as removing their batteries is a big way to gimp borgs. I do think it fits the servers style and vibe but I fear it might be abused hard by Malfs or anyone with a Law Board and a dream.

2024-05-22 15:50 UTC, Swiftfeather commented
Idk what the other maintainers think but I don't like this at all.

2024-06-05 08:41 UTC, Majkl-J reviewed
Would you consider this complete?

2024-06-05 17:54 UTC, pixelkitty286 commented
fuck oops. also yes it's ready.

2024-06-07 18:45 UTC, Majkl-J commented on code/game/objects/items/robot/items/storage.dm
> +					)
Can be made modular with
```
/obj/item/borg/apparatus/sheet_manipulator/Initialize()
	. = ..()
	storable += /obj/item/stack/rods
```

2024-06-07 18:47 UTC, Majkl-J commented on code/game/objects/items/robot/robot_upgrades.dm
Modularly override with

```
/obj/item/borg/upgrade/processor
	name = "medical and research cyborg surgical processor" // BUBBER EDIT Research borgs
	desc = "An upgrade to the Medical and Research model, installing a processor \
		capable of scanning surgery disks and carrying \
		out procedures"

/obj/item/borg/upgrade/processor/Initialize()
	. = ..()
	model_type += /obj/item/robot_model/sci
	model_flags += BORG_MODEL_RESEARCH

2024-06-07 19:07 UTC, Majkl-J requested changes

2024-06-07 19:07 UTC, Majkl-J commented on modular_zubbers/modules/borgs/code/robot_items.dm
> +	var/charge_cost = (3200 KILO JOULES) //bruh
```suggestion
	var/charge_cost = (STANDARD_CELL_CHARGE * 0.0032)
```

2024-06-07 19:07 UTC, Majkl-J commented on modular_zubbers/modules/borgs/code/robot_upgrade.dm
> +
```suggestion
/obj/item/borg/upgrade/healthanalyzer
	name = "Research cyborg advanced Health Analyzer"
	desc = "An upgrade to the Research model cyborg's standard health analyzer."
	icon_state = "cyborg_upgrade3"
	require_model = TRUE
	model_type = list(/obj/item/robot_model/sci)
	model_flags = BORG_MODEL_RESEARCH

	items_to_add = list(/obj/item/healthanalyzer/advanced)
	items_to_remove = list(/obj/item/healthanalyzer)
```

2024-06-07 19:07 UTC, Majkl-J commented on modular_zubbers/modules/borgs/code/robot_upgrade.dm
> +
```suggestion
```

2024-06-07 19:07 UTC, Majkl-J commented on modular_zubbers/modules/borgs/code/robot_upgrade.dm
> +
```suggestion
/obj/item/borg/upgrade/inducer_sci
	name = "Research integrated power inducer"
	desc = "An integrated inducer that can charge a device's internal cell from power provided by the cyborg."
	require_model = TRUE
	model_type = list(/obj/item/robot_model/sci)
	model_flags = BORG_MODEL_RESEARCH

	items_to_add = list(/obj/item/inducer/cyborg/sci)
```

2024-06-07 19:07 UTC, Majkl-J commented on modular_zubbers/modules/borgs/code/robot_upgrade.dm
> +		borg.model.add_module(RPED, FALSE, TRUE)
```suggestion
/obj/item/borg/upgrade/brped
	name = "Research cyborg Rapid Part Exchange Device Upgrade"
	desc = "An upgrade to the Research model cyborg's standard RPED."
	icon_state = "cyborg_upgrade3"
	require_model = TRUE
	model_type = list(/obj/item/robot_model/sci)
	model_flags = BORG_MODEL_RESEARCH

	items_to_add = list(/obj/item/storage/part_replacer/bluespace)
	items_to_remove = list(/obj/item/storage/part_replacer)
```

2024-06-08 02:58 UTC, pixelkitty286 commented
Waiting on https://github.com/Bubberstation/Bubberstation/pull/1609 to do the changes.

2024-06-09 20:19 UTC, Majkl-J approved these changes

2024-06-10 08:53 UTC, merged