Adds a damage threshold + RNG requirement for EMPs affecting heads and torsos, as well as organs inside those two.
Bubberstation/Bubberstation pull request #1424
Opened 2024-04-24 11:16 UTC by BurgerLUA

## About The Pull Request

Adds a damage threshold + RNG requirement for EMPs affecting heads and torsos, as well as organs inside those two.
For every point of damage on the bodypart (or if you're an organ, the bodypart you belong to), there is a +2% chance for that bodypart (or organ) to trigger the effects of EMP. This chance is doubled if it's a heavy EMP.

Example, if your torso has 25 damage, and you were affected by an EMP, your torso has a 50% chance to suffer the default effects of EMP. All your organs inside your torso will EACH roll the 50% chance to be affected by the EMP, regardless if your torso was EMP'd or not.

Graph here: https://www.desmos.com/calculator/7sdtn22uda

**Note that some effects can still trigger, such as stun and blindness, regardless of damage. This is intentional.**

## Why It's Good For The Game

EMPs are super strong against synths. Perhaps unreasonably strong. This PR nerfs this by making it so that you actually have to do some damage to the synth before you can EMP them for an instant win. The justification for this is below:

![image](https://github.com/Bubberstation/Bubberstation/assets/8602857/2b05fca7-df59-451d-a88e-eb59f51af478)

TL;DR, if your electronics are enclosed in steel, it won't suffer the effects of EMP unless there are holes (damage).

## Proof Of Testing

Draft because untested.

## Frequently asked questions

### Synth main????
I have never played synth because I am not sexually attracted to metal.

### Does this affect cyborgs?
This PR does not change cyborg EMP behavior.

### Does this affect legs and arms?
This PR does not change leg and arm EMP behavior, since they're jointed.

## Changelog

:cl: BurgerBB
balance: Adds a damage threshold + RNG requirement for EMPs affecting heads and torsos, as well as organs inside those two.
/:cl:

2024-04-24 13:10 UTC, Majkl-J requested changes

2024-04-24 13:10 UTC, Majkl-J commented on modular_zubbers/code/modules/emp_overhaul/organ.dm
> +	if(!(src.biological_state & BIO_STANDARD_JOINTED) && !prob((src.brute_dam + src.burn_dam)*2*(2/severity))) //Chance to get EMP'd is based on self bodypart damage.
```suggestion
	if(!(src.biological_state & BIO_STANDARD_JOINTED) && !prob((src.get_damage())*2*(2/severity))) //Chance to get EMP'd is based on self bodypart damage.
```

2024-04-24 13:46 UTC, BurgerLUA commented on modular_zubbers/code/modules/emp_overhaul/organ.dm
> +		return EMP_PROTECT_ALL
In a lot of act_emp calls, EMP_PROTECT_CONTENTS is returned. EMP_PROTECT_ALL contains that bitflag and more. I'm just doing the same thing.

2024-04-24 13:51 UTC, Majkl-J commented on modular_zubbers/code/modules/emp_overhaul/organ.dm
> +		return EMP_PROTECT_ALL
`code/modules/surgery/bodyparts/_bodyparts.dm#L1409-L1412` Seems to be using `return FALSE`, we probably should keep consistent with the parent proc

2024-05-20 06:45 UTC, Majkl-J approved these changes
Looks good to me, once you're done testing it, undraft it and I'll TM it for a week just incase before merging.

2024-05-25 14:15 UTC, projectkepler-ru approved these changes

2024-05-27 11:36 UTC, Majkl-J requested changes
Due to how `code\modules\surgery\bodyparts\robot_bodyparts.dm` handles these, you need to return FALSE or refactor this upstream. Damage isn't applied but negative effects still are

2024-05-27 14:05 UTC, BurgerLUA commented
> Due to how `code\modules\surgery\bodyparts\robot_bodyparts.dm` handles these, you need to return FALSE or refactor this upstream. Damage isn't applied but negative effects still are

Check the first file changed. This already was resolved.

2024-05-27 14:38 UTC, Majkl-J commented
> > Due to how `code\modules\surgery\bodyparts\robot_bodyparts.dm` handles these, you need to return FALSE or refactor this upstream. Damage isn't applied but negative effects still are
> 
> Check the first file changed. This already was resolved.

Nope, robot parts still have old handling code. I tested your PR locally and still got a good half of the negative effects, like the ugly green screen

2024-05-27 14:49 UTC, BurgerLUA commented
pain

2024-06-04 15:32 UTC, BurgerLUA commented
This is ready to be merged.

2024-06-04 16:23 UTC, Majkl-J approved these changes
This will need some adjustments once I go and make organ and limb emp processing not happen independently of eachother

Looks fine for now though, love the work

2024-06-04 16:23 UTC, merged