[modular] Renames the code for Inquisition ERT from Spanish Red to just Unexpected because admins keep asking me why I'm sending red alert ERTs (I'm not)
Bubberstation/Bubberstation pull request #1488
Opened 2024-05-07 12:19 UTC by Odairu

## About The Pull Request
Does what the title says

## Why It's Good For The Game
Differentiates it more clearly from actual red alert ERTs

## Proof Of Testing
![Screenshot_12](https://github.com/Bubberstation/Bubberstation/assets/39929315/8834aa24-bc58-49bf-b4be-db0ba6881646)

## Changelog

:cl:
qol: its now easier to tell what ERT is being spawned
/:cl:

2024-05-07 16:49 UTC, BurgerLUA commented
I thought Spanish Red was creative :( darn

2024-05-07 17:33 UTC, projectkepler-ru approved these changes

2024-05-07 18:13 UTC, Odairu commented
> I thought Spanish Red was creative :( darn

Its very creative, but the last two times I've spawned it, Asay immediately lights up with "YOU SPAWNED A CODE RED?!?"

2024-05-07 23:14 UTC, destrucktoid commented
Why not just name it "Spanish Inquisition" instead of "Spanish red" if we're making a monty python reference? Heck, might as well just make it a code "Unexpected" ERT. Since nobody expects the Spanish inquisition.

2024-05-08 19:51 UTC, projectkepler-ru commented
> Why not just name it "Spanish Inquisition" instead of "Spanish red" if we're making a monty python reference? Heck, might as well just make it a code "Unexpected" ERT. Since nobody expects the Spanish inquisition.

you're right

2024-05-08 19:52 UTC, projectkepler-ru requested changes
Not funny enough

2024-05-08 19:52 UTC, projectkepler-ru commented on modular_zubbers/code/datums/ert.dm
> +	code = "Inquisition"
```suggestion
	code = "Unexpected"
```
Funnier

2024-05-09 09:31 UTC, merged