[DRAFT] [MOD] smolraptors
Bubberstation/Bubberstation pull request #1524
Opened 2024-05-17 13:29 UTC by aKromatopzia

## About The Pull Request

smaller raptor borgs. i might bring these to skyrat but these will be here for now. I can't figure out how to test w/ https://github.com/Bubberstation/Bubberstation/pull/1407 so no preview for research borgs.

## Proof Of Testing

in a bit ya

## Changelog

:cl:
add: new silicon model (smolraptor)
/:cl:

2024-05-17 15:55 UTC, Erol509 commented
They loook awesome

2024-05-17 16:34 UTC, NargaInDisguise commented
co-starring: my voice lmao????
commenting here before it remakes the video without me in it

2024-05-18 05:01 UTC, aKromatopzia commented
Update: CC model and some colours got shifted.

2024-05-18 18:20 UTC, aKromatopzia commented
bugfix and sprite changes, ready again

2024-05-18 18:20 UTC, Superhats commented
![image](https://github.com/Bubberstation/Bubberstation/assets/21011148/bba7c644-0f56-425f-bed8-063263135d79)
I don't know how this happened but I joined the round and my sprite was in between two tiles

2024-05-18 18:21 UTC, aKromatopzia commented
> ![image](https://private-user-images.githubusercontent.com/21011148/331824807-bba7c644-0f56-425f-bed8-063263135d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTY3MjUsIm5iZiI6MTcxNjA1NjQyNSwicGF0aCI6Ii8yMTAxMTE0OC8zMzE4MjQ4MDctYmJhN2M2NDQtMGY1Ni00MjVmLWJlZDgtMDYzMjYzMTM1ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE4MjAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOTA5ZTUzZDgxM2IzM2IzOTMxNDJjMTIxNWNkZWRjYzkxMDJiZDRjYzk2YTZkNmRiMWZjMDliODdhNDdmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WATH_EsdULpLkZ_MnRpWAwCDowGRFfp3Dlu-tio9Rxo) I don't know how this happened but I joined the round and my sprite was in between two tiles

this tends to happen with two-wide borgs; find your pixel shift button and move along the misaligned axis until you can't any more. then move. it should reset you.

2024-05-19 00:44 UTC, Superhats commented
> > ![image](https://private-user-images.githubusercontent.com/21011148/331824807-bba7c644-0f56-425f-bed8-063263135d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTY3MjUsIm5iZiI6MTcxNjA1NjQyNSwicGF0aCI6Ii8yMTAxMTE0OC8zMzE4MjQ4MDctYmJhN2M2NDQtMGY1Ni00MjVmLWJlZDgtMDYzMjYzMTM1ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDE4MjAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiOTA5ZTUzZDgxM2IzM2IzOTMxNDJjMTIxNWNkZWRjYzkxMDJiZDRjYzk2YTZkNmRiMWZjMDliODdhNDdmNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WATH_EsdULpLkZ_MnRpWAwCDowGRFfp3Dlu-tio9Rxo) I don't know how this happened but I joined the round and my sprite was in between two tiles
> 
> this tends to happen with two-wide borgs; find your pixel shift button and move along the misaligned axis until you can't any more. then move. it should reset you.

I tried doing that, it did not fix it

2024-05-19 03:31 UTC, thegrb93 commented
> ![image](https://private-user-images.githubusercontent.com/21011148/331824807-bba7c644-0f56-425f-bed8-063263135d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODk3NTQsIm5iZiI6MTcxNjA4OTQ1NCwicGF0aCI6Ii8yMTAxMTE0OC8zMzE4MjQ4MDctYmJhN2M2NDQtMGY1Ni00MjVmLWJlZDgtMDYzMjYzMTM1ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDAzMzA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNjE1NzZhNjJiNGZkMzI2MDU1MDM4OTQ4ZDI5OTBlMzNhYWJjNGYwODYzYmJiOTc1NmY3ZmRhMGFmMWFjYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RhA9XwcEMJ-96_F1lU2MxzrXI1VuRyW6h0EwWnsN_28) I don't know how this happened but I joined the round and my sprite was in between two tiles

yeah It's currently happening

2024-05-19 05:07 UTC, aKromatopzia commented
TRAIT_R_WIDE has been given back to them, and they now have appropriate emote sprites.

2024-05-19 23:14 UTC, Superhats commented
Pretty significant problem. The Raptorborg's panel isn't visible from the front, so there's no feedback to indicate it's open. I've personally gotten emagged twice because someone opened my panel while I was talking to them and there was no prompt or other visual to warn me.

2024-05-19 23:17 UTC, thegrb93 commented
> Pretty significant problem. The Raptorborg's panel isn't visible from the front, so there's no feedback to indicate it's open. I've personally gotten emagged twice because someone opened my panel while I was talking to them and there was no prompt or other visual to warn me.

Thats true for any borg, you just gotta watch for them grabbing their emag and crowbar. If your hatch is open and you haven't already noticed, its already too late.

I think the raptor's hatch is on the back too. I've seen it open.

2024-05-20 08:01 UTC, aKromatopzia commented
> Pretty significant problem. The Raptorborg's panel isn't visible from the front, so there's no feedback to indicate it's open. I've personally gotten emagged twice because someone opened my panel while I was talking to them and there was no prompt or other visual to warn me.

other borgs have their panel visible from the front and sides; raptors are on the back and sides. It is what it is.

2024-05-22 06:17 UTC, projectkepler-ru commented
science variant perhaps

2024-05-22 07:05 UTC, ReturnToZender commented
> science variant perhaps

Sprites for the science variant are here but until research borgs get merged they can't be put in :(

2024-05-23 08:23 UTC, Majkl-J requested changes
Looks good to me otherwise, once you add the undefs this should be ready to merge.

2024-05-23 08:23 UTC, Majkl-J commented on modular_zubbers/modules/smolraptors/code/smallraptor.dm
> +#define CYBORG_ICON_CC_SMOLRAPTOR 'modular_zubbers/modules/smolraptors/icons/smolraptor_cc.dmi'
Add undefs on the end of the file.

2024-05-23 11:00 UTC, projectkepler-ru commented on modular_zubbers/modules/smolraptors/code/smallraptor.dm
> +#undef CYBORG_ICON_TYPE_SMOLRAPTOR "smolraptor"
```suggestion
#undef CYBORG_ICON_TYPE_SMOLRAPTOR 
```

2024-05-23 20:35 UTC, CenkTheRaptor commented
YEAAAAAAH BABYYYYYY THATS WHAT IVE BEEN WAITING FOR THATS WHAT ITS ALL ABOUT WOOOOOOOOOOOOOOOOOOOOOOOOO

2024-05-24 14:20 UTC, Erol509 commented
What about skin hat offset?

2024-05-24 16:23 UTC, thegrb93 commented
> What about skin hat offset?

Is this what controls hat position? I know the other wide borgs have hat wearing issues.

2024-05-24 16:27 UTC, Erol509 commented
> > What about skin hat offset?
> 
> Is this what controls hat position? I know the other wide borgs have hat wearing issues.

Yes, it shifts the hat offset so it can land on the  actual head. its a pixel shift

2024-05-24 16:33 UTC, thegrb93 commented
> Yes, it shifts the hat offset so it can land on the actual head. its a pixel shift

Even if the borg's head position changes depending on rotation? I think the problem with wide borgs is their head is not stationary. That would be cool if it works for any rotation though. I would fix some of them if it does have the capability.

2024-05-26 17:27 UTC, Majkl-J approved these changes

2024-05-26 17:31 UTC, merged

2024-05-26 17:59 UTC, pixelkitty286 commented
oh god i should of told them to fix file paths now i gotta clean that AAAAAAA