makechangelogs
Bubberstation/Bubberstation pull request #1525
Opened 2024-05-19 01:31 UTC by codehonky

## About The Pull Request

Adds a bluespace experi-scanner to the game which unlocks with the Applied Bluespace tech node and can perform experiments instantly and from range.

## Why It's Good For The Game

The first thirty minutes of science gameplay in a shift is typically the exact same grindfest, and any roleplay from asking departments to open for early upgrades/experiment scans loses all glamour after the first few times a scientist performs it. The alternative to walking around with a bluespace scanner is just building copies of the machines for experiments in science anyway, which still lacks roleplay. QoL change for science that encourages walking outside the department more without counterhopping and allows it to engage in roleplay shticks sooner.

## Proof Of Testing

## Changelog

:cl:
add: Added new bluespace experi-scanner.
qol: Made science slightly less tedious after the Applied Bluespace tech node.
image: Added a simple reskin of the experi-scanner for the bluespace variant.
/:cl:

2024-05-19 05:39 UTC, R3dtail commented
Maybe consider making it a piece of RD's equipment?  I fully understand that people just do the meta strats nowadays with experiments (if they bother to do them at all), but you can make plenty of fun of showing up to people's departments to pester them about  being let in for experiments.  It's as fun as you make it.    Ranged experiment scanning has some niche uses that would be neat, but I also don't really like the idea of REDUCING the need to interact even if said interactions ARE typical and basically a script.  I think that's part of the charm and adds some believability to the whole job RP portion.  Just something to consider.

2024-05-19 05:54 UTC, aKromatopzia commented
taking out the hypothetical situation that a scientist uses their experiments to trespass is both unfortunate, and amusing

2024-05-19 06:13 UTC, codehonky commented
It barely takes away from the need to interact. Instead of waiting for doors to be opened, you still walk to where the things you'll be scanning are and can interact all the same but aren't forced to sit and wait for every door to open. It actually encourages walking and interacting more than building copies of the machines in science. And you can still use experiments as an excuse to trespass; just say there weren't materials for another bluespace scanner or you forgot to make one.

2024-05-19 06:30 UTC, R3dtail commented
Y'know that's true.  I was approaching it from the aspect of the 'using through cameras" point brought up in the PR.  I don't mind the range part  since as you said, doesn't take away from interactions, just makes things slightly less annoying to an extent.

2024-05-19 19:27 UTC, nevimer requested changes
this all will need to be made either modular, or comment blocked for non-modular edits

2024-05-19 20:44 UTC, codehonky commented
> this all will need to be made either modular, or comment blocked for non-modular edits

Done

2024-05-27 17:12 UTC, codehonky commented
@nevimer The modular defines file was in the wrong spot - fixed and tested locally.

2024-06-07 14:12 UTC, codehonky commented
@nevimer bumping this

2024-06-07 16:29 UTC, Majkl-J reviewed
Looks testmerge ready, just minor code clarity touches

2024-06-07 16:29 UTC, Majkl-J commented on modular_zubbers/code/modules/experisci/experiment/handlers/experiment_handler.dm
> +	if ((selected_experiment == null && !(config_flags & EXPERIMENT_CONFIG_ALWAYS_ACTIVE)) || config_flags & EXPERIMENT_CONFIG_SILENT_FAIL)
```suggestion
	if ((isnull(selected_experiment) && !(config_flags & EXPERIMENT_CONFIG_ALWAYS_ACTIVE)) || config_flags & EXPERIMENT_CONFIG_SILENT_FAIL)
```

2024-06-07 16:29 UTC, Majkl-J commented on modular_zubbers/code/modules/experisci/experiment/handlers/experiment_handler.dm
> +	SIGNAL_HANDLER
No need to have this when the parent that calls it already has it

```suggestion

```

2024-06-07 16:29 UTC, Majkl-J commented on modular_zubbers/code/modules/experisci/handheld_scanner.dm
> +	)
```suggestion
	AddComponent(/datum/component/experiment_handler, \
		allowed_experiments = list(/datum/experiment/scanning, /datum/experiment/physical), \
		disallowed_traits = EXPERIMENT_TRAIT_DESTRUCTIVE, \
		config_flags = EXPERIMENT_CONFIG_IMMEDIATE_ACTION|EXPERIMENT_CONFIG_WORKS_FROM_RANGE, \
		experiment_signals = handheld_signals, \
	)
```

2024-06-07 18:26 UTC, pixelkitty286 commented
if this gets added i'm adding it to research borgs as an upgrade

2024-06-17 14:58 UTC, R3dtail commented
After experiencing it a couple of times yeah no this was the greatest thing to have ever period.  Little powercreepy I guess but  hot damn it's sleek as fuck  and more interesting to use.

2024-06-25 09:22 UTC, Majkl-J approved these changes
I like it, the code is solid, nothing was broken during testing. If it feels too powercreepy later down the line we can move it to a different node.

2024-06-25 09:59 UTC, merged