Nerfs borg tipping
Bubberstation/Bubberstation pull request #1529
Opened 2024-05-20 06:30 UTC by ReturnToZender

## About The Pull Request
This PR makes it so instead of the agonizingly long 60 second timer on righting yourself as a borg, you have a 20 second timer instead. It's still a very long stun, but is not an entire minute in a game where you can be killed in 3 seconds.

## Why It's Good For The Game
There's long, and then there's too long. This is too long, and makes the game worse for cyborg players without much tangible benefit.

## Proof Of Testing

## Changelog

:cl: ReturnToZender
balance: The stun time on the tippable component for borgs has been reduced by 40 seconds, from 60 seconds.
/:cl:

2024-05-20 06:33 UTC, ReturnToZender commented
I included Robotic pleas for help and mercy in the footage to make the full 60 second stun more bearable. You're welcome, maintainers.

2024-05-23 09:58 UTC, Swiftfeather approved these changes
why not

2024-05-23 10:00 UTC, Swiftfeather requested changes

2024-05-23 10:00 UTC, Swiftfeather commented on code/modules/mob/living/silicon/robot/robot.dm
> +		self_right_time = 20 SECONDS, \
```suggestion
		self_right_time = 20 SECONDS, \ //BUBBER EDIT: REDUCES THE SELF-RIGHT TIME FOR BORGS TO 20 SECONDS, FROM 60 SECONDS
```

2024-05-23 10:00 UTC, Swiftfeather commented on code/modules/mob/living/silicon/robot/robot.dm
> +		//BUBBER EDIT: REDUCES THE SELF-RIGHT TIME FOR BORGS TO 20 SECONDS, FROM 60 SECONDS
```suggestion
```

2024-05-23 10:01 UTC, Swiftfeather approved these changes

2024-05-23 11:28 UTC, Swiftfeather commented
OH THAT'S WHY YOU DID IT SO SILLY. Alright oops

2024-05-23 11:56 UTC, merged