Heretic Nerfs Part 1
Bubberstation/Bubberstation pull request #1536
Opened 2024-05-21 10:28 UTC by Erol509

## About The Pull Request

Nerfs heretic blade armor penetration by a bit, subject to change. Plus forces them to sacrafice targets which had client linked to them before they died. Making the ascension much harder, and I have plan to make it, that they NEED to sacrafice their further sacraficial targets.

## Why It's Good For The Game

Because they are too powerfull after ascension and before.

## Proof Of Testing

Didnt test it yet. Its still wip
## Changelog

:cl:
balance: rebalanced something
/:cl:

2024-05-21 10:35 UTC, Majkl-J requested changes
isnull is faster

2024-05-21 10:35 UTC, Majkl-J commented on code/modules/antagonists/heretic/heretic_knowledge.dm
> +	return (sacrifice.stat == DEAD) && !ismonkey(sacrifice) && (sacrifice.last_mind) // Bubberstation edit
```suggestion
	return (sacrifice.stat == DEAD) && !ismonkey(sacrifice) && (!isnull(sacrifice.last_mind)) // BUBBER EDIT - adds last mind requirement
```

2024-05-21 10:53 UTC, Erol509 commented
Changes work so far

2024-05-21 13:02 UTC, destrucktoid commented
I think you really need to make it so that if you try to sac someone who is disconnected you instead get that target re-rolled, another idea is to make it so that someone who is disconnected for 10 minutes auto-rerolls. This is because that making it so you cannot sacrifice targets who are disconnected will really screw over your heretic round.

2024-05-21 13:03 UTC, Majkl-J commented
> I think you really need to make it so that if you try to sac someone who is disconnected you instead get that target re-rolled, another idea is to make it so that someone who is disconnected for 10 minutes auto-rerolls. This is because that making it so you cannot sacrifice targets who are disconnected will really screw over your heretic round.

last_mind is proofed against this

2024-05-21 13:04 UTC, destrucktoid commented
Also, why the nerf to the armour pen? Seems a bit out of the blue and unusual, heretic knives aren't really THAT strong compared to other antagonist weapons so i'm not really sure why it needs a nerf.

2024-05-21 13:04 UTC, destrucktoid commented
> > I think you really need to make it so that if you try to sac someone who is disconnected you instead get that target re-rolled, another idea is to make it so that someone who is disconnected for 10 minutes auto-rerolls. This is because that making it so you cannot sacrifice targets who are disconnected will really screw over your heretic round.
> 
> last_mind is proofed against this

What do you mean by it's proofed against this?

2024-05-21 13:06 UTC, destrucktoid commented
Wait... I just realised this is making it so that the heretic ASCENSION needs a mind component. This is a big no from me as it will inherently making ascending violate round removal rules.

2024-05-21 13:06 UTC, projectkepler-ru requested changes
It'd be better for us to just nerf their spawnrate than the antag itself, the problem is because in higher pop round theres a lot more heretic and more rift for them to loot from.

2024-05-21 13:07 UTC, projectkepler-ru commented
Also, Heretic Nerfs Part 1?

2024-05-21 13:47 UTC, Erol509 commented
> It'd be better for us to just nerf their spawnrate than the antag itself, the problem is because in higher pop round theres a lot more heretic and more rift for them to loot from.

Spawnrate doesnt really matter 90% of the time, even when only 3 spawns, bah 2 spawns. They are able to completly ruin round for everyone on the server, Im thinking about lowpop.

2024-05-21 14:14 UTC, Majkl-J commented
> > It'd be better for us to just nerf their spawnrate than the antag itself, the problem is because in higher pop round theres a lot more heretic and more rift for them to loot from.
> 
> Spawnrate doesnt really matter 90% of the time, even when only 3 spawns, bah 2 spawns. They are able to completly ruin round for everyone on the server, Im thinking about lowpop.

Heretics are 40+ pop, at which point at least 4, and a max of 6 can spawn roundstart

This is no only an uninformed assumption, but also applying survivorship bias to the 1/6 that survives long enough to end the round.

2024-05-21 16:38 UTC, projectkepler-ru commented
> > > It'd be better for us to just nerf their spawnrate than the antag itself, the problem is because in higher pop round theres a lot more heretic and more rift for them to loot from.
> > 
> > 
> > Spawnrate doesnt really matter 90% of the time, even when only 3 spawns, bah 2 spawns. They are able to completly ruin round for everyone on the server, Im thinking about lowpop.
> 
> Heretics are 40+ pop, at which point at least 4, and a max of 6 can spawn roundstart
> 
> This is no only an uninformed assumption, but also applying survivorship bias to the 1/6 that survives long enough to end the round.


Precisely, most heretic are caught and often time stopped before anything happens, Also, this is not including the fact there are heretics who can cause a lot of damage to the station without ever ascending.

2024-05-26 16:52 UTC, KazooBard commented
You do realize ascencion gibs targets, right? This will cause more round removal than you intended to. 

As for the rest, heretics dont ascend often, they are at even odds with sec and the fact they are a threat to every other antag makes sure they are balanced because you're not fighting sec. You're fighting sec and the traitor and changeling and vampire.

2024-05-26 17:02 UTC, Erol509 commented
> You do realize ascencion gibs targets, right? This will cause more round removal than you intended to.
> 
> As for the rest, heretics dont ascend often, they are at even odds with sec and the fact they are a threat to every other antag makes sure they are balanced because you're not fighting sec. You're fighting sec and the traitor and changeling and vampire.
> 
> EDIT: There is only one person who manages to ascend somewhat consistently and they still die while ascended PRE nerfs, we all know who. Time constraints due to sec chasing etc and even just 4 coordinated officers end a heretic's run quite easily.

There is always a way to remove gib from the heretic ascension ritual.

2024-05-26 17:03 UTC, Erol509 commented
Guh, I will close it for now. Gonna work on it in the future, I plan on forcing the heretics to fight aginst each other, and sap others for powers. Only one can ascend stepping on the bodies of others.

2024-05-26 17:03 UTC, closed without merging