Sending in the Clowns: More Clown outfits.
Bubberstation/Bubberstation pull request #1576
Opened 2024-05-29 18:39 UTC by theselfish

## About The Pull Request

![image](https://github.com/Bubberstation/Bubberstation/assets/102828457/45ad0260-6914-4003-ac7e-03fd20f09846)
![image](https://github.com/Bubberstation/Bubberstation/assets/102828457/3cb9ecf5-397a-421c-b705-e29906d885ea)
Credits are in the files.

## Why It's Good For The Game

I like Clowns, a lot of users like clowns.
Other than the weird fact that there's orange/red/blue/etc uniforms but no matching masks, the other two outfits allow variety.

Or something.
I also re-added clown cryto as...We aren't Skyrat, and they removed it during the Clown Purge. Barely anyone does cryto. If this ends up being trouble, it can be reverted.

## Proof Of Testing

See the screenshots.

## Changelog

:cl:
add: Added various clown clothing into the autodrobe.
add: Clown Cryto is back.
code: Modular Vending code from Skyrat, but for us.
/:cl:

2024-05-29 18:44 UTC, Majkl-J requested changes
You need to comment that you edited skyrat uncomments (As cursed as that may be), otherwise all good

2024-05-29 18:44 UTC, Majkl-J commented on modular_zubbers/modules/vending/vending.dm
> +	var/list/zubbers_contraband
I could've sworn we already had this somewhere. Guess not. alas, add a whitespace
```suggestion
/obj/machinery/vending
	/// Additions to the `products` list  of the vending machine, modularly. Will become null after Initialize, to free up memory.
	var/list/zubbers_products
	/// Additions to the `product_categories` list of the vending machine, modularly. Will become null after Initialize, to free up memory.
	var/list/zubbers_product_categories
	/// Additions to the `premium` list  of the vending machine, modularly. Will become null after Initialize, to free up memory.
	var/list/zubbers_premium
	/// Additions to the `contraband` list  of the vending machine, modularly. Will become null after Initialize, to free up memory.
	var/list/zubbers_contraband

```

2024-05-29 18:53 UTC, theselfish commented on code/modules/clothing/masks/gasmask.dm
> +// BUBBERSTATION EDUT
```suggestion
// BUBBERSTATION EDIT
```

2024-05-29 18:53 UTC, theselfish commented on code/modules/clothing/under/jobs/civilian/clown_mime.dm
> +// BUBBERSTATION EDUT
```suggestion
// BUBBERSTATION EDIT
```

2024-06-01 21:10 UTC, plsleavemealon commented
Is there any chance to be able to add these things to the loadout as a generalist option?

2024-06-02 00:57 UTC, theselfish commented
> Is there any chance to be able to add these things to the loadout as a generalist option?

Just go to an autodrobe.

2024-06-02 17:21 UTC, plsleavemealon commented
I can't customize the physical description and the name of the item if I am forced to buy it from an autodrobe.

2024-06-03 02:22 UTC, theselfish commented
> I can't customize the physical description and the name of the item if I am forced to buy it from an autodrobe.

Fine.

2024-06-03 19:23 UTC, plsleavemealon commented
Thank you!

2024-06-03 22:22 UTC, Majkl-J approved these changes
Honk (Also I really hope the clown cytology won't become a mess)

2024-06-03 22:22 UTC, merged

2024-06-04 00:32 UTC, plsleavemealon commented
Aww the pink clown skirt is role locked :(