[TEST] Removes the Ambient Buzz
Bubberstation/Bubberstation pull request #1590
Opened 2024-06-02 02:37 UTC by nevimer

## About The Pull Request

It's actually kind of grating, the other ambiences are so much better and this isn't covered by a pref

## Why It's Good For The Game

Ears

## Proof Of Testing

builds

## Changelog

:cl:
qol: ambience buzz is gone
/:cl:

2024-06-02 03:06 UTC, YakumoChen commented
Isn't this covered by a config?

2024-06-02 03:21 UTC, nevimer commented
> Isn't this covered by a pref though?

the pref covers shuttle sounds

2024-06-02 17:09 UTC, pixelkitty286 commented
please make this into a pref

2024-06-02 18:15 UTC, Arturlang commented
There's no reason to make specific ambience's pref only, but this is incredibly grating, is there *any* reason to keep it, @pixelkitty286?

2024-06-02 18:45 UTC, YakumoChen commented
I've never found it grating, it adds immersion since you're existing more or less on a giant floating machine filled with florescent lights and other things that quietly hum.

2024-06-03 01:46 UTC, captainfrost20 commented
The ambient buzz really adds to the atmosphere of the station. Removing it outright is sorta dumb. Like if its that big of an issue make a pref for it.

2024-06-03 01:58 UTC, nevimer commented
![reaper_Qvxok64ZJz](https://github.com/Bubberstation/Bubberstation/assets/77420409/6d6a6848-71e4-4960-b41e-1f75154edf3e)

I don't think you even know what you're arguing for. I'm not removing ambience effects. I am removing the low rumble that makes subwoofers shake constantly, and is just generally like listening to a 24 fan noise sound bit. There is no need to have it- it out-volumes many other effects that go on, and just is literally the definition of noise.

2024-06-03 02:13 UTC, captainfrost20 commented
Shipambience.ogg is it not? I know exactly which ambience I'm talking about it. Having a general hum of the station isn't a bad thing when the other choice is literally just deafing silence. It is meant to be just station noise hence it being ambience, it adds a nice hum to the actual station itself giving the station the feeling of being in space. Genuinely this should just be a pref option, bundle a few of the other more "annoying" ambience ones into a grating category and be done with it. This shouldn't be a straight up removal based off your own personal preference

2024-06-03 03:10 UTC, Patriot210 commented
> Shipambience.ogg is it not? I know exactly which ambience I'm talking about it. Having a general hum of the station isn't a bad thing when the other choice is literally just deafing silence. It is meant to be just station noise hence it being ambience, it adds a nice hum to the actual station itself giving the station the feeling of being in space. Genuinely this should just be a pref option, bundle a few of the other more "annoying" ambience ones into a grating category and be done with it. This shouldn't be a straight up removal based off your own personal preference

I agree with this tbh, I like the ambience, and it'd feel weird to remove the hum completely instead of adding an audio perf option.

2024-06-05 08:39 UTC, Majkl-J requested changes
This needs to be a pref

2024-06-07 18:27 UTC, Redrover1760 commented
Its surprising how much its needed.

2024-06-27 07:11 UTC, StrangeWeirdKitten requested changes
This just looks like a TG bug then to warrent a flat out removal. I personally enjoy the white noise too, ngl.

2024-06-27 09:00 UTC, StrangeWeirdKitten commented
I found out the issue. Ambiance code requires area sensitivity. Living mobs are given area sensitivity via their mood. Ghosts do not have area sensitivity. It also does a !isliving early return. This should be a simple fix.

2024-06-27 09:09 UTC, StrangeWeirdKitten commented
Narrowing it down. It's because ghosts are above the area plane and they don't trigger shit.

2024-06-27 09:23 UTC, StrangeWeirdKitten commented
@nevimer this bug is extensive and deep. Disable ambiant sounds prefrence and use the stop all sounds command and it will remove the buzz while you're observing. The only thing I can think to do is giving a prefrence check on dead/observer initalize and it will correctly set what you need.

2024-06-27 09:23 UTC, closed without merging