Nerfs the Bow Because I died To It Once
Bubberstation/Bubberstation pull request #1603
Opened 2024-06-06 04:02 UTC by AllCorruptingWyrm

## About The Pull Request
This PR completely slashes the damage of arrows and essentially reverts the extremely overpowered tribal buffs from SR as they were not attuned for a player vs player environment. The arrows are essentially brought in line with the stats of the Chaplain arrows. Please, never-ever change this again.

If this severely effects ice cats, i'll buff the mob arrows but ensure they can't really be used against the crew.

## Why It's Good For The Game

Completely overtuned weapons that you can essentially get at round start when the Chaplain gets weaker arrows again, at round start. Also asked to do this so here we are.

## Proof Of Testing

it compiles.

## Changelog

:cl:
balance: Brings arrows into line with the Chaplain arrows.
/:cl:

2024-06-06 05:59 UTC, Wolf-751 commented
I always found it funny that arrows hit harder than space age technology,but to be fair its a weird theme of space station 13.

2024-06-06 06:12 UTC, projectkepler-ru requested changes
do it modularly

2024-06-06 07:05 UTC, Majkl-J requested changes
You'd need to give it a buff against `/mob/living/basic/mining` to compensate for ashies and such.

2024-06-06 07:43 UTC, Cyprex commented
We can do this upstream. But this absolutely needs to be done. It does a T3 bleeding wound against a security armor in default gear(including chest armour), and if you hit the arm rather than the chest it will disable the arm after 12 seconds or so too (and do the full 50 damage +embed damage). The bloodloss kills you like 40s after. You can fix the wound with just a suture, but you're still gonna lose a fair bit of blood, and another hit will very likely knock you out via bloodloss. And all this is assuming you even have time to stitch yourself up- if the attacker simply presses the attack you are simply going to die.

They need a large negative wound_bonus- `damage + wound_bonus` should be 15 or so, so it wounds like a 15 damage hit.

2024-06-06 11:55 UTC, NargaInDisguise commented
I still don't understand why we can even craft the skyrat bow+arrow as crew. They were made for ashies to be completely overpowered and take any gamer chem they could make to defend themselves with. Crew were literally never SUPPOSED to have these, and the fact that they're being abused right now shows why lol

2024-06-06 15:36 UTC, AllCorruptingWyrm commented
I have absolutely no idea how to make it do extra damage to the lavaland faction with the regular bow cause it didnt work when I did it.

and the same applies to doing it modularily.

2024-06-06 17:23 UTC, CloverIsLucky commented
I don't believe the arrows needs a nerf that big, the arrows are strong and everything but not everyone has good enough talent nor reloading reaction time to put another arrow in the bow and pray you hit your target.... However, I believe the bow deserves a nerf, but not this one.

2024-06-08 15:36 UTC, projectkepler-ru commented
> I have absolutely no idea how to make it do extra damage to the lavaland faction with the regular bow cause it didnt work when I did it.
> 
> and the same applies to doing it modularily.



> I still don't understand why we can even craft the skyrat bow+arrow as crew. They were made for ashies to be completely overpowered and take any gamer chem they could make to defend themselves with. Crew were literally never SUPPOSED to have these, and the fact that they're being abused right now shows why lol

they aren't supposed to really be easily craftable but I haven't talked to @Useroth  about what to do yet

2024-06-08 15:37 UTC, projectkepler-ru commented
> I also believe the arrows deserve a nerf, but somwhow I don't like the requested changes in this PR. The arrows are strong and everything but not anyone has talent nor the reaction speed to quickly reload another arrow in the bow.
> 
what do you not like about the requested change I just asked for this to be done modularly  since the bow and arrow themselves are a tg content but the ability to craft them is inherently SR

2024-06-09 00:48 UTC, AllCorruptingWyrm commented
Blessed be to burger.

2024-06-09 00:48 UTC, closed without merging