F3-LINE cyborg updates attempt 2 [Modularish]
Bubberstation/Bubberstation pull request #1641
Opened 2024-06-12 21:40 UTC by pixelkitty286

## About The Pull Request

This attempt two of https://github.com/Bubberstation/Bubberstation/pull/1636

Makes the sprite file resolutions from 64 x 32 to 32 x 32 for cat borgs

Makes 32 x 32 quadruped cybrogs into it's own borg type with it's own quadruped module of it's own.

Allows only station standard cat borgs to be hold able, non standard can not be held.

Adds code for cyborgs to indicate when they are being held.

Makes cyborg that are being held unable to interact items around them, they can still break free any time.

This does not allow cyborgs with shape shifting to be picked up it only allows the REAL model to be held.

A slight change from the last PR is the addition of a cargo variant of cat borg.

## Why It's Good For The Game

I've always wondered why can't I make cat borgs hold able and also make it so it don't have sweeping mechanical changes to the game so I came up with a way to allow them to be held disabling their abilities to interact with much wile being in a held state and being almost unbaggable.

Cargo cat borg was added since there was no variant.

Making the sprites 32 x 32 means they won't look so offsetted when using things quite as often.

Cent Com don’t want you to know this but the the cat borgs on space station 13 are free you can take them home I have 458 cat borgs at home.

## Proof Of Testing

![dreamseeker_wBPMde6WO5](https://github.com/Bubberstation/Bubberstation/assets/78038207/8830cb9f-a281-44d0-9527-3b4bba8320c1)

![dreamseeker_xTFBOmZHyJ](https://github.com/Bubberstation/Bubberstation/assets/78038207/4dd933b8-e431-4d1a-9a98-18265c50be8e)

![sc19jFbsn7](https://github.com/Bubberstation/Bubberstation/assets/78038207/95c9e0af-bd0d-4c9f-948a-c4f101f892b4)

![dreamseeker_mmNECEkkUe](https://github.com/Bubberstation/Bubberstation/assets/78038207/cf0f743d-7b78-49eb-b833-10c58d369853)

## Changelog

:cl:
add: holding code for cyborgs
del: Old 32x32 F3-LINE sprites
image: 32x32 F3-LINE sprites and a cargo variant
code: preventive flags to indicate when held
admin: Two robot traits added to the trait list
/:cl:

2024-06-13 01:47 UTC, projectkepler-ru approved these changes
Quite frankly minimal player-facing concerns from this

2024-06-13 14:25 UTC, Majkl-J requested changes

2024-06-13 14:25 UTC, Majkl-J commented on code/_onclick/cyborg.dm
> +	if(stat || (lockcharge) || IsParalyzed() || IsStun() || (mob_in_holder)) //BUBBER EDIT - makes it so cyborgs that are holdable can not interact wile being held
Can't we just check with `istype(loc, /obj/item/clothing/head/mob_holder)` ?

2024-06-14 20:08 UTC, Majkl-J requested changes
Looks good otherwise

2024-06-15 00:34 UTC, pixelkitty286 commented on modular_zubbers/code/modules/borgs/code/robot_upgrade.dm
> +	icon_state = "cyborg_upgrade3"
I tried this before and it ended up just duping the items and giving it to the unintended modules

2024-06-15 17:19 UTC, pixelkitty286 commented
fuck

2024-06-16 00:29 UTC, Majkl-J requested changes
Get rid of this and it should be ready to merge

2024-06-16 00:29 UTC, Majkl-J commented on modular_zubbers/code/modules/research/techweb/all_nodes.dm
> +
```suggestion
```

2024-06-16 04:15 UTC, pixelkitty286 commented
> Get rid of this and it should be ready to merge

HUUUUUUUUUUUUUNNNNNNNNNNNNNGGGGG HOW HOW HOW DID I FOR GET THAT?!

one second

2024-06-16 09:30 UTC, Majkl-J approved these changes

2024-06-16 09:31 UTC, merged