[MODULAR] Reduce Empath point cost
Bubberstation/Bubberstation pull request #1691
Opened 2024-06-28 18:41 UTC by ForrestWick

## About The Pull Request

Just lowers the cost of the Empath trait by 2 points, down to 4.

## Why It's Good For The Game

Skyrat already lowered this thing from 8 to 6, but it looks like TG made some big changes to it since then and now it's basically just a flavor thing. Personally I'd rather it be 2 points, but I got told 4 would be best so here we are. Most of the stuff you get from it isn't exactly powerful enough to warrant a 6 point price.

## Changelog

:cl:
balance: lowered Empath cost from 6 to 4.
/:cl:

2024-06-28 19:11 UTC, StrangeWeirdKitten requested changes

2024-06-28 19:11 UTC, StrangeWeirdKitten commented on modular_zubbers/code/modules/quirks/code/positive_quirks/empath_override.dm
> +	mail_goodies = list(/obj/item/toy/foamfinger)
```suggestion
	value = 4
```
You don't need all this

2024-06-28 19:22 UTC, plsleavemealon commented
2 would probably be fine honestly.  It doesn't seem to do all that much....could also be used as one of the mythical 3 pointers, we don't really have many of those.

2024-06-28 19:23 UTC, ForrestWick commented on modular_zubbers/code/modules/quirks/code/positive_quirks/empath_override.dm
> +	mail_goodies = list(/obj/item/toy/foamfinger)
> ```suggestion
> 	value = 4
> ```
> You don't need all this

Ah, gotcha

2024-06-28 19:46 UTC, StrangeWeirdKitten commented on modular_zubbers/code/modules/quirks/code/positive_quirks/empath_override.dm
> +	value = 4 // Original: value = 8 - Skyrat Value: 6
```
value = 4
```

2024-06-28 19:50 UTC, StrangeWeirdKitten requested changes

2024-06-28 19:50 UTC, StrangeWeirdKitten commented on modular_zubbers/code/modules/quirks/code/positive_quirks/empath_override.dm
> +	name = "Empath"
You don't need this either. Basically what you are doing is overriding the original value of 6 with 4. The compiler will first compile the original code, then when it compiles our modular changes, it'll see datum path again and duplicate variables with what you set here. (Or add an entirely new variable if you're adding one)

2024-06-28 21:31 UTC, theselfish commented
> 2 would probably be fine honestly. It doesn't seem to do all that much....could also be used as one of the mythical 3 pointers, we don't really have many of those.
> 
> Edit: Actually wait, we don't even have a single 3 point positive quirk. Huh.

Traits *are* meant to go in increments of two.
Skyrat and whomever added the clicker traits forgot that.

2024-06-28 21:54 UTC, SonicGotNuked commented
> > 2 would probably be fine honestly. It doesn't seem to do all that much....could also be used as one of the mythical 3 pointers, we don't really have many of those.
> > Edit: Actually wait, we don't even have a single 3 point positive quirk. Huh.
> 
> Traits _are_ meant to go in increments of two. Skyrat and whomever added the clicker traits forgot that.

This is arbitrary and I dont really care tbqh.

2024-06-28 21:55 UTC, StrangeWeirdKitten commented
This is arbitrary and I dont really care.

2024-06-28 22:07 UTC, theselfish commented
It's not arbitrary, it's consistency.

2024-06-28 22:15 UTC, plsleavemealon commented
> > 2 would probably be fine honestly. It doesn't seem to do all that much....could also be used as one of the mythical 3 pointers, we don't really have many of those.
> > Edit: Actually wait, we don't even have a single 3 point positive quirk. Huh.
> 
> Traits _are_ meant to go in increments of two. Skyrat and whomever added the clicker traits forgot that.

To be fair we have several traits that aren't in increments of 2.  With some being 7 points, others being 1 point.  And negative quirks are the same way with some being 3 and 1.

2024-06-28 22:25 UTC, theselfish commented
> > > 2 would probably be fine honestly. It doesn't seem to do all that much....could also be used as one of the mythical 3 pointers, we don't really have many of those.
> > > Edit: Actually wait, we don't even have a single 3 point positive quirk. Huh.
> > 
> > 
> > Traits _are_ meant to go in increments of two. Skyrat and whomever added the clicker traits forgot that.
> 
> To be fair we have several traits that aren't in increments of 2. With some being 7 points, others being 1 point, and yet some others being 5. And negative quirks are the same way with some being 3 and 1.

See "Skyrat and whomever added the clicker traits forgot that."

2024-06-29 04:27 UTC, nikothedude commented
> It's not arbitrary, it's consistency.

id argue its an arbitrary consistancy, theres no reason it has to go in increments of two besides tradition

2024-06-29 06:18 UTC, merged