Blob Networked Fibers Nerf + Starting Changes
Bubberstation/Bubberstation pull request #1758
Opened 2024-07-08 03:21 UTC by BurgerLUA

## About The Pull Request

Your blob strain on start will always be Distributed Neurons, instead of a random strain. The cost to reroll for the first time is still free.

Changing to Networked Fibers will instantly alert the crew that you exist (With a level 5 blob biohazard announcement), regardless of how many tiles you have.

## Why It's Good For The Game

Babe, new blob meta just dropped (Intentionally gaming the announcement system where you hoard resources and only build nodes in the middle of bumfuck nowhere, then start building a fuckload of shit all at once).

## Proof Of Testing

Untested :)

## Changelog

:cl: BurgerBB
balance: Your blob strain on start will always be Distributed Neurons, instead of a random strain. The cost to reroll for the first time is still free.
balance: Changing to Networked Fibers will instantly alert the crew that you exist (With a level 5 blob biohazard announcement), regardless of how many tiles you have.
/:cl:

2024-07-08 03:44 UTC, AllCorruptingWyrm commented
It does make the Blueshift/OceanMap/GrassMap/ slop a lot more enjoyable.

2024-07-08 06:03 UTC, projectkepler-ru commented
> It does make the Blueshift/OceanMap/GrassMap/ slop a lot more enjoyable.

the audacity to call blueshift slop is making me want to fly over in enola gay once more

2024-07-08 07:17 UTC, Majkl-J requested changes

2024-07-08 07:17 UTC, Majkl-J commented on code/modules/antagonists/blob/powers.dm
> +
Should be a tgui alert window that asks you if you wish to proceed once you switch strains.

2024-07-08 07:17 UTC, Majkl-J commented on code/modules/antagonists/blob/overmind.dm
> +	var/datum/blobstrain/BS = /datum/blobstrain/reagent/distributed_neurons //BUBBERSTATION CHANGE, YOUR STRAIN WILL ALWAYS BE THE SAME.
Not too sure if distributed neurons should be the pick, reactive spines feel like a generally safer starter.

2024-07-08 07:17 UTC, Majkl-J commented on modular_zubbers/code/modules/antagonists/blob/blobstrains/_blobstrain.dm
> +		announcement_size = 0
Since you're already making this variable under `/datum/blobstrain`, you should extend its on_gain() proc with the logic

2024-07-11 05:15 UTC, StrangeWeirdKitten approved these changes
Lol I was told the context behind this PR and what prompted it

2024-07-12 07:17 UTC, StrangeWeirdKitten commented on code/modules/antagonists/blob/powers.dm
```suggestion
// BUBBER REFACTOR END
```

2024-07-12 07:18 UTC, StrangeWeirdKitten commented
It's not compiling. Otherwise when you get this fixed up I'll merge it.

```modular_zubbers/code/modules/antagonists/blob/blobstrains/_blobstrain.dm:6:error: has_announced: undefined var
modular_zubbers/code/modules/antagonists/blob/blobstrains/_blobstrain.dm:7:error: announcement_size: undefined var
code/world.dm:23:warning (loop_checks): 0: Disabling loop_checks is dangerous and should only be used as a temporary debugging measure. Without these checks an infinite loop in your code can cause the world to hang. Proceed with caution.
tgstation.dmb - 2 errors, 2 warnings (7/8/24 8:21 pm)```

2024-07-16 02:51 UTC, StrangeWeirdKitten commented
Ping me on discord @BurgerLUA when you resolve all the compile and CI issues. I will happily merge something like this

2024-07-16 06:36 UTC, StrangeWeirdKitten commented
👍

2024-07-16 06:39 UTC, merged