The offstation cargo update
Bubberstation/Bubberstation pull request #1764
Opened 2024-07-10 00:45 UTC by shellspeed1

## About The Pull Request

First things first, credit to tmyqlfpir aka Feignsleep for making the initial cargo crate import code. I probably butchered it when I messed with it to make it only import on console so make sure to yell at me if there are issues.

This PR does several things. 

FIRST it brings Tarkon up to date with Interdyne as far as cargo goes. In this case, that means an express cargo console, selling pad, and powerator tied to a budget account.

Second, thing, both Interdyne and Tarkon now have access to cargo company items. Its a bit janky but it should do for at least now. With how it was done, we should be able to add unique items to the consoles for each faction, although that might need some work.

As a minor note, I also nerfed the interdyne powerator. It had a 2x multiplier and I'm not sure that is really needed.

## Why It's Good For The Game

Cargo goes brrrt, also Tarkon could use some love.

## Proof Of Testing

![image](https://github.com/Bubberstation/Bubberstation/assets/46614774/a34cd62a-e40d-4c35-9305-20e3f77aed18)

## Changelog

:cl:
add: Cargo Companies are now available to offstation factions
add: Tarkon now has a cargo setup available to them
balance: rebalanced something
/:cl:

2024-07-28 05:59 UTC, StrangeWeirdKitten requested changes
I forgot to actually submit my review, lol

2024-08-01 21:18 UTC, shellspeed1 commented
I'll get to it in a couple of days, bonk me if I forget

2024-08-04 19:06 UTC, Majkl-J requested changes

2024-09-05 06:17 UTC, shellspeed1 commented
Found a minor issue with existing stuff, will get it figured out and fixed shortly so listings are complete

2024-09-11 20:50 UTC, Swiftfeather commented on modular_skyrat/modules/tarkon/code/misc-fluff/research.dm
> +		"bountyconsole_tarkon"//end bubber edit
```		
		"rcd_tarkon", //Bubber edit (the comma)
		"powerator_tarkon", //Bubber edit addition start
		"cargoconsole_tarkon",
		"bountypad_tarkon", 
		"bountyconsole_tarkon"//Bubber edit addition end
```

2024-09-11 21:10 UTC, Swiftfeather requested changes

2024-09-11 21:15 UTC, Swiftfeather commented on modular_skyrat/modules/tarkon/code/misc-fluff/research.dm
>  	departmental_flags = DEPARTMENT_BITFLAG_ENGINEERING
```suggestion
	departmental_flags = DEPARTMENT_BITFLAG_ENGINEERING
	
```

2024-09-15 17:41 UTC, Majkl-J commented
I already read through this before and it's good, so

2024-09-15 17:45 UTC, merged

2024-09-25 08:15 UTC, Hotmud9 commented
I am losing my mind; WHERE ARE THESE BOARDS