Buffing Bounty Rewards, Rebalancing Bounties for Security Roles
Bubberstation/Bubberstation pull request #1786
Opened 2024-07-13 06:31 UTC by SirSwagmeyer

## About The Pull Request

Increases the space credit reward for a good variety of departments that had woefully underfunded or underwhelming bounties and rewards. Gave Detectives security bounties. Secmeds get medical bounties too now.

## Why It's Good For The Game

Providing actionable rewards for bounties will incentivize players in the community other than medical players to do their bounties and bring more funding to cargo. 

Bounties are heavily underutilized in a majority of departments and heavily utilized in one or two departments. 
Security bounties net you around 120 credits for a handful of handcuffs, while medical gets thousands in the wallet for a bodybag full of synth organs. They both cost next to nothing to produce at roundstart. 

There's a clear imbalance to the bounty system, and I believe bringing the currently underwhelming bounty rewards for the other departments up to their level will make everyone happy. 

## Proof Of Testing

https://discord.com/channels/1059199070016655462/1061369280572166164/1261562590241488946

^^ Example of the improved bounty rewards. Ran it through locally, and it worked fine. 

## Changelog

:cl:
add: Increased bounty multipliers for the following:
-  Engineers - emitters, borg chargers, SMES units, field generators, tesla coils.
- Robotics - All mechs. 
- Chemistry - Simple and rare chems.
- Security - Rechargers, Earmuffs, Handcuffs, N-Spect Reports
- Science - Modular Machines, Genetics Disability Mutators, all Refined Anomaly Cores

add: Added Security bounties to the Detective role. 
add: Added Medical bounties to the Security Medic role.
balance: Increased the quantity requirements for Security bounties and science's Modular laptops. 

/:cl:

2024-07-13 06:39 UTC, projectkepler-ru requested changes
modularize the bounty changes

2024-08-02 16:13 UTC, Majkl-J requested changes
Making most of these into modular overrides and adding the files to the tgstation.dme reccomended

2024-08-02 16:13 UTC, Majkl-J commented on modular_zubbers/code/modules/security/secmed/security_medic.dm
> +	bounty_types = CIV_JOB_MED
You can either have one or the other

2024-08-02 16:13 UTC, Majkl-J commented on modular_zubbers/code/modules/cargo/bounties/engineering.dm
> +	wanted_types = list(/obj/machinery/power/emitter = TRUE)
When making overrides, you only need the variable you're changing
```suggestion
/datum/bounty/item/engineering/emitter
	reward = CARGO_CRATE_VALUE * 8
```

2024-08-02 16:13 UTC, Majkl-J commented on code/modules/jobs/job_types/detective.dm
Needs bubber edit comment or an override

2024-08-02 16:13 UTC, Majkl-J commented on code/modules/cargo/bounties/security.dm
Needs to be made into overrides

2024-08-02 16:13 UTC, Majkl-J commented on modular_zubbers/code/modules/cargo/bounties/engineering.dm
File is not included in the dme -> has no effect

2024-08-23 07:22 UTC, Majkl-J commented
staled out

2024-08-23 07:22 UTC, closed without merging