[Non-Modular] Grants anyone standing on a crate automatic loud mode because my underlings refuse to listen to me
Bubberstation/Bubberstation pull request #1787
Opened 2024-07-13 09:30 UTC by Odairu

## About The Pull Request
Does as the title says (doesn't work on comms)

## Why It's Good For The Game
I can stand on my soapbox

## Proof Of Testing
![image](https://github.com/user-attachments/assets/8fafee30-2d5e-4480-b908-69104a2a77c2)

## Changelog

:cl:
add: Standing on a closed crate will give you loudmode in speech
/:cl:

2024-07-13 09:59 UTC, ReturnToZender commented
Teshari player woes

2024-07-13 10:22 UTC, Swiftfeather commented
Sorry you don't have windows activated we can't accept a pr from an illegal computer

2024-07-13 11:20 UTC, projectkepler-ru requested changes
Fix your PR Body

2024-07-13 13:56 UTC, theselfish commented
Honestly you could try this upstream. They might take it.

2024-07-13 14:57 UTC, projectkepler-ru commented
> Honestly you could try this upstream. They might take it.

if he opens it on skyrat without filling the PR body beside "it's funny" I am still closing it

2024-07-13 16:04 UTC, Odairu commented
> Honestly you could try this upstream. They might take it.

https://github.com/tgstation/tgstation/pull/84942 good idea :P

2024-07-13 17:04 UTC, Majkl-J commented on code/modules/mob/living/living_say.dm
> +				message_mods[SAY_FAKE_COMMAND] = TRUE
```suggestion
		if(soapbox && !soapbox.opened && !ismovable(loc))
			spans |= SPAN_COMMAND
			message_mods[SAY_FAKE_COMMAND] = TRUE
```

2024-07-13 17:32 UTC, imedial commented on code/modules/mob/living/living_say.dm
> +				message_mods[SAY_FAKE_COMMAND] = TRUE
Fixed

2024-07-17 15:28 UTC, StrangeWeirdKitten commented
Will be brought from upstream

2024-07-17 15:28 UTC, closed without merging