Reverts Ghost being votable at any time
Bubberstation/Bubberstation pull request #1793
Opened 2024-07-15 07:22 UTC by Odairu

## About The Pull Request
Title

## Why It's Good For The Game
Every time this story teller is voted pop is slashed by half, peak hours should not be going from 90 connected to 50 connected because 4 people voted ghost, those 4 people can go ERP somewhere else

## Proof Of Testing
it works trust me

## Changelog

:cl:
fix: Ghost being votable
/:cl:

2024-07-15 07:29 UTC, projectkepler-ru requested changes
the changelog should be server: or admin:
not fix:

2024-07-15 08:03 UTC, Majkl-J requested changes
Bump it up to 40

2024-07-15 08:03 UTC, Majkl-J commented on modular_zubbers/code/modules/storyteller/storytellers/storyteller_tellers.dm
> +	population_max = 30
```suggestion
	population_max = 40
```

2024-07-15 08:06 UTC, Majkl-J approved these changes

2024-07-15 12:46 UTC, Majkl-J approved these changes

2024-07-15 13:13 UTC, merged

2024-07-16 13:55 UTC, NargaInDisguise commented
I was the one that originally suggested moving ghost's pop limit up, so this is more than fine with me, 40 is reasonable