Limbgrown bodies.
Bubberstation/Bubberstation pull request #1842
Opened 2024-07-27 12:51 UTC by xXPawnStarrXx

## About The Pull Request

The limbgrower was an often underutilised item, it was only really useful for bounties, because most medical staff never checked if their ~~victim~~ patient was a body purist or not. They'd just jam them full of parts and off they go. This allows an easier method (if not more expensive) to getting corses for body transfers. I have also added blank brains for the niche reason of RSD phylacteries for those who were completely gibbed or dusted to be able to return to the round. 

~~(When I work out what's preventing me, I'll remove the restriction on ghosts being put into phylacteries and adding new people to the round.)~~

## Why It's Good For The Game

Miners who get gibbed, dusted or just trapped deep in lava.
Genetics gets to keep their monkeys.
Coroners have more to do, by printing, preserving and prepping corpses for revival.
More uses for the limbgrower and less CBT of restraining a feral monkeyman.

## Proof Of Testing

![image](https://github.com/user-attachments/assets/7edacc4f-82be-4f8c-8460-97fa022dd62a)

## Changelog

:cl:
add: Added blanks to the limbgrower, for soul/brain transfer.
/:cl:

2024-07-27 16:02 UTC, projectkepler-ru reviewed
Please hold, the implication of this change is abit, big

2024-07-27 20:12 UTC, aKromatopzia commented
> Please hold, the implication of this change is abit, big

isn't this pretty on-rate with stealing monkey cubes from botany/genetics/xenobio/virology?

2024-07-27 22:08 UTC, xXPawnStarrXx commented
> isn't this pretty on-rate with stealing monkey cubes from botany/genetics/xenobio/virology?

Yeah. That's the majority of what I was hoping to replace. You need more synthflesh, but means no monkeydone or anything like that.

2024-07-28 04:32 UTC, YakumoChen commented
Regardless of the implications of this, we should not be encouraging in any manner players cold ghosting into RSDs in order to get a new body when they've been gibbed or similarly round removed.

In most cases, round removal either happens by intention or otherwise can be ahelped and an admin will usually fix it, if the round removal is against the rules, the result of a bug, or dying so badly that the admin gives you a more manageable way to be revived out of pity.

What this would encourage is security being even more suicidal, since we truly would be removing all consequences of dying to antagonists no matter the cost.

2024-07-28 05:41 UTC, StrangeWeirdKitten commented
It's either this or monkeydone. Remove monkeydone from the code as we try out this PR. I don't think it's awful to require synthflesh or coorporation with genetics (to use the machine) to print a new body.

2024-07-28 17:08 UTC, xXPawnStarrXx commented
> It's either this or monkeydone. Remove monkeydone from the code as we try out this PR. I don't think it's awful to require synthflesh or coorporation with genetics (to use the machine) to print a new body.

I didn't feel it was right to rip someone else's PR out to test mine. Monkeydone can also still be useful, since the chem will work without power.

2024-07-30 22:06 UTC, shellspeed1 commented
Honestly, why not have both. Monkey done is useful as a basic bitch solution while this lets medical have several bodies prepped for quick revives while still giving medical pretty of content. Especially as the content is not reactive to the round.

2024-07-31 12:01 UTC, aKromatopzia commented
> Regardless of the implications of this, we should not be encouraging in any manner players cold ghosting into RSDs in order to get a new body when they've been gibbed or similarly round removed.

true, but if you had the brain can't you just slot that into a monkey body anyways?

But, what is this about monkeydone - is that not just a more-specific mutadone?

2024-07-31 12:06 UTC, Majkl-J commented
> But, what is this about monkeydone - is that not just a more-specific mutadone?

Mutadone no longer turns monkeys into humans

2024-08-08 14:39 UTC, Majkl-J requested changes
Also you should remove monkeydone with this PR. Feels like a better and more elegant solution

2024-08-08 14:39 UTC, Majkl-J commented on modular_zubbers/code/modules/limbgrowncorpses/limbgrowerblanks.dm
> +	death_sound = old_death_sound // Now they can die loudly again
Normal humans don't have death sounds, also the nullcheck is not needed as the brain is guaranteed to exist and qdelling already removes the organ from the body so we don't need to do that.

Turns out my old synth code that you copied is not that good lol

```suggestion
	death()

	var/obj/item/organ/internal/brain/to_remove = get_organ_slot(ORGAN_SLOT_BRAIN)
	QDEL_NULL(to_remove)
```

2024-10-01 05:39 UTC, StrangeWeirdKitten commented
stale

2024-10-09 10:42 UTC, Majkl-J requested changes
Code is solid, I still think you should review monkeydone with this PR as well

2024-10-12 11:09 UTC, xXPawnStarrXx commented
> Code is solid, I still think you should review monkeydone with this PR as well

Fair enough, monkeydone is monkeydone-done away with.

2024-10-12 17:30 UTC, xXPawnStarrXx commented
@Majkl-J Won't let me request another review, so I'll do it this way.

2024-10-14 18:23 UTC, Majkl-J approved these changes

2024-11-06 06:08 UTC, funnyfreeperson commented
this is ironically cloning again. not to say that's a bad thing. but yanno. full circle

2024-11-06 11:04 UTC, Majkl-J commented
> this is ironically cloning again. not to say that's a bad thing. but yanno. full circle I'd like to say that synthflesh is a good way to "limit" it, as that's the way most modern implementations of cloning work rn anyway

So was making monkeys and that was cheaper than this

2024-11-06 11:07 UTC, merged