[Modular] [Bounty] Adds the ability to 'army crawl'
Bubberstation/Bubberstation pull request #1918
Opened 2024-08-08 06:24 UTC by Odairu

## About The Pull Request
This PR adds the ability to lower yourself even further onto the ground than normal resting, allowing you to crawl under tables/railings and the like
Being prone in this manner will prevent you from attacking, pulling, and getting back up onto your feet until you've gotten back up from the prone state, while bullets and lasers will go over you, you are pretty helpless in this state to prevent abuse cases

## Why It's Good For The Game
This is mostly for under the table shenanigans (ERP purposes) elsewise I can't really think of any other use case.

## Proof Of Testing
https://youtu.be/j1WBvLybH50

## Changelog

:cl:
add: added the ability to army crawl below the table layer
/:cl:

2024-08-08 12:06 UTC, projectkepler-ru approved these changes
Code looks fine + bounty

2024-08-08 18:10 UTC, Majkl-J requested changes
The bounty specifically states this should be made into a module for any (presumably living) mobs, yet the component/element is limited to carbons. Also this is better off to do upstream so we can add the functionality to borers too and not have 2 different cases of the same behaviour defined differently in the code

2024-08-08 18:35 UTC, Odairu commented on modular_zubbers/code/datums/components/prone_mob.dm
> +		return COMPONENT_INCOMPATIBLE
Done

2024-08-08 18:35 UTC, Odairu commented on modular_zubbers/code/modules/mob/mob_movement.dm
> +		return balloon_alert(src, "you must be laying down to army crawl.")
done

2024-08-10 01:43 UTC, YakumoChen commented
I don't see the code regarding layering with tables and the like, or any sanity checks for if the crawler is under a table when they stop crawling (so they don't presumably phase through the table)

Army crawling should inflict a more severe crawl slowdown to stem abuse from the fact they dodge projectiles (people will just abuse this to be annoying as they are unclickable or dance between flaps or stairs

This is also going to make snail drifting even more annoying as well

2024-08-10 02:41 UTC, projectkepler-ru requested changes
On second review has this actually been tested on any other things to make sure they do work and have the intended interaction?

2024-08-10 02:50 UTC, Odairu commented
> I don't see the code regarding layering with tables and the like, or any sanity checks for if the crawler is under a table when they stop crawling (so they don't presumably phase through the table).
> 
> Army crawling should inflict a more severe crawl slowdown to stem abuse from the fact they dodge projectiles (people will just abuse this to be annoying as they are unclickable or dance between flaps or stairs. The enhanced click protection is going to be abused by people trying to spite security for sure.
> 
> This is also going to make snail drifting even more annoying as well
> 
> I am sure people are going to find just a lot of exploits in general this doesn't cover, as one would expect.

They cant attack, pull, use ranged weapons, or throw objects in this state, they also cannot stand back up, and the only way to exit it is with the 3 second do_after requiring them to stand still for that time. 
They dont need more slowdown because if someone enters this state you just melee them and they literally cannot do anything back to you

2024-08-10 16:30 UTC, YakumoChen commented
How are you supposed to melee them when their entire sprite is hidden under a table

2024-08-10 16:49 UTC, Majkl-J commented
> Can you address the other legitimate concerns

Altclick table - click sprite.
The same counter works on borers, and nobody ever had concerns over that even though borers can still fire off abilities from under tables

2024-08-10 23:44 UTC, Odairu commented
This got PRed up on SR

2024-08-10 23:44 UTC, closed without merging

2024-08-11 02:10 UTC, YakumoChen commented
> Altclick table - click sprite.
The same counter works on borers, and nobody ever had concerns over that even though borers can still fire off abilities from under tables

Alt clicking and loading up the menu is not an instant process, you will not be able to do this on someone actively moving around