Changes to guard accesses
Bubberstation/Bubberstation pull request #1929
Opened 2024-08-09 22:21 UTC by Adrian16199

## About The Pull Request
Olderly getting morgue secure mostly because most morgues have even the first door to be secure and if a doctor gets a secured one on extra access then... bit odd that olderly doesnt have it at all. Psychology because i mean.... part of medical, isnt it not? I think.

The cargo guard gets bitrunner access while destroyin the QM one because.... well, weird that they get qm access but cant get into bitrunner den.

Bouncer gets janitorial one because.... service... no? Not sure if to add chapel aswell... only if told to.

Not sure if missed any more which... well, would make sense.

## Why It's Good For The Game
I mean, its weird that some accesses are just *not there* or the access is just not correct like having QM access, just odd really.

## Proof Of Testing
Yes

## Changelog

:cl:
add: Added additional access to olderly and service guard for their respective departments.
fix: Fixes cargo guards having QM access and not bitrunner access.
:cl:

2024-08-09 22:38 UTC, Majkl-J requested changes
Take these upstream to skyrat

2024-08-09 22:38 UTC, Majkl-J commented on modular_skyrat/modules/goofsec/code/department_guards.dm
> +		ACCESS_MORGUE_SECURE
```suggestion
		ACCESS_MORGUE_SECURE,
```

2024-08-10 11:13 UTC, Adrian16199 commented
> Take these upstream to skyrat

uuuuuuuuuuuuuuuuuuuuh..
If i can find the repository, fair.

2024-08-10 23:41 UTC, Majkl-J commented
> uuuuuuuuuuuuuuuuuuuuh.. If i can find the repository, fair.

https://github.com/Skyrat-SS13/Skyrat-tg/pulls

2024-08-11 13:04 UTC, Majkl-J commented
Should be taken upstream

2024-08-11 13:04 UTC, closed without merging