Allows Traitors to buy the ninja kit
Bubberstation/Bubberstation pull request #1957
Opened 2024-08-15 04:06 UTC by nevimer

## About The Pull Request
As it says on the title

## Why It's Good For The Game
It's good for the game if people can choose this instead of ghosting for it

## Proof Of Testing

## Changelog

:cl:
add: traitor ninja kit is now purchasable
/:cl:

2024-08-15 23:31 UTC, pixelkitty286 commented
Honestly I liked the non crew ghost selection more and tots can just out right just have a shit ton of stuff on them then buy this mid round and power game seem a bit bad. Also tots just going from their employer to another just like that seems a bit off because they are betraying their own employer. Space ninja is supposed to be a mild medium antagonist that causes some havoc enough to distract sec to let other antags cook more.

2024-08-15 23:32 UTC, ReturnToZender commented
> Honestly I liked the non crew ghost selection more and tots can just out right just have a shit ton of stuff on them then buy this mid round and power game seem a bit bad.

The kit costs 20TC, traitors will be unable to buy anything else

2024-08-15 23:40 UTC, pixelkitty286 commented
> > Honestly I liked the non crew ghost selection more and tots can just out right just have a shit ton of stuff on them then buy this mid round and power game seem a bit bad.
> 
> The kit costs 20TC, traitors will be unable to buy anything else

Do you not see the issue I do that will be abused I am a known exploiter I find stuff like this. There is a good reason TG don't do stuff like this and didn't make space ninja a round start antagonist. Also do know and I've now seen this live Sec instantly knows you are a ninja and sets you to arrest meaning the AI can track you and with a REAL ninja you could set your name and were not on the manifest. I just see soo much wrong with this and think we really should reconsider this being a thing tots can do.

2024-08-15 23:55 UTC, Wolf-751 commented
> > Honestly I liked the non crew ghost selection more and tots can just out right just have a shit ton of stuff on them then buy this mid round and power game seem a bit bad.
> 
> The kit costs 20TC, traitors will be unable to buy anything else

what if multiple traitors get this kit how is sec meant to deal with like 3 ninjas emping,stunning and cutting them to pieces with there 50 ap 30 damage 50 block chance swords,i have played sec alot and one ninja is a nightmare to fight,multiple is going to be impossible to fight.

2024-08-16 00:02 UTC, Redrover1760 commented
Don't traitors get 25 TC here?

2024-08-16 00:22 UTC, projectkepler-ru requested changes
There appears to be no apparent check or time progression requirement put in place to stop multiple people from getting this and tripling the threat

2024-08-16 19:03 UTC, TheGandalf85 commented
_I'm sorry for sounding like a huge hardass, but someone has to do it._

This is feeling like yet another minimally written or thought about PR.

So you just enabled ninja kit on traitors in hopes that people would become ninja naturally instead of staying on ghost for it or something?

_Ever thought of the resulting consequences?_

Sorry if this sounds a bit harsh, but this is looking to be an extremely short sighted change, and in current TMs we just have 2-3 traitors running around with full ninja gear and some extra TC to buy other things. This is not only a giant balance issue, but you've increased the rate of ninja appearances in all aspects which has it's own consequences for the people not choosing to be an antag that round.

At the very least, address the above concerns **specifically within your PR** and look at your change from all angles before just dropping it with little information and depending entirely on player feedback. (A practice with variable results) This is how servers get wacked off balance. Think, spaceman, think.

![zo872yq9fnx61](https://github.com/user-attachments/assets/fdfd22e4-6dd9-4026-87e8-d97369b9d9ab)

If you want to achieve your goal of having a more common source of ninjas outside of ghost antags, restrict the usage of this kit via the reputation system, or strictly disallowing more then one of them being used at a time.

2024-08-16 19:27 UTC, KazooBard commented
> _I'm sorry for sounding like a huge hardass, but someone has to do it._
> 
> This is feeling like yet another minimally written or thought about PR.
> 
> So you just enabled ninja kit on traitors in hopes that people would become ninja naturally instead of staying on ghost for it or something?
> 
> _Ever thought of the resulting consequences?_
> 
> Sorry if this sounds a bit harsh, but this is looking to be an extremely short sighted change, and in current TMs we just have 2-3 traitors running around with full ninja gear and some extra TC to buy other things. This is not only a giant balance issue, but you've increased the rate of ninja appearances in all aspects which has it's own consequences for the people not choosing to be an antag that round.
> 
> At the very least, address the above concerns **specifically within your PR** and look at your change from all angles before just dropping it with little information and depending entirely on player feedback. (A practice with variable results) This is how servers get wacked off balance. Think, spaceman, think.
> 
> ![zo872yq9fnx61](https://private-user-images.githubusercontent.com/4382340/358683953-fdfd22e4-6dd9-4026-87e8-d97369b9d9ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MzY2MDIsIm5iZiI6MTcyMzgzNjMwMiwicGF0aCI6Ii80MzgyMzQwLzM1ODY4Mzk1My1mZGZkMjJlNC02ZGQ5LTQwMjYtODdlOC1kOTczNjliOWQ5YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTZUMTkyNTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI5NmY4ZDYwODE1MWIxNTkxNjcwMDYyODczZmVmMjFjYzZiMzY1MTU2ZDMyMTRmMjgyMjI2N2JiYmFlMGEwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dXLva_a0-nfljxOlJfoA8kWiDaUPqOkYVkF8iZDYTTI)
> 
> If you want to achieve your goal of having a more common source of ninjas outside of ghost antags, restrict the usage of this kit via the reputation system, or strictly disallowing more then one of them being used at a time.

Ngl kinda wish there were more really high rep items, this would fit the bill. Like didn't cook all round or spent shitton of time not doing much? Sec's going to be stronger than if you would've harassed from the start soooo yep checks out for me. Good call with the rep stuff

2024-08-17 03:47 UTC, YakumoChen commented
Ninjas are incredibly strong, I don't see why we should be giving the average traitor the power of a wizard-level antag?

2024-08-17 03:51 UTC, SovietSpaghetti commented
I wouldn't call ninjas wizard-level by any stretch of the imagination, but they're definitely strong, and considering how many traitors roll every round this definitely shouldn't be as accessible as it is. Especially considering you still have 5 tc left over. One ninja is enough to fuck over the station, but multiple ninjas with access to a traitor uplink all for the threat cost of roundstart traitors is nuts.

2024-08-17 03:56 UTC, nevimer commented
> I wouldn't call ninjas wizard-level by any stretch of the imagination, but they're definitely strong, and considering how many traitors roll every round this definitely shouldn't be as accessible as it is. Especially considering you still have 5 tc left over. One ninja is enough to fuck over the station, but multiple ninjas with access to a traitor uplink all for the threat cost of roundstart traitors is nuts. If this is your idea of a better alternative to ghost-rolling antags I shudder to think of what your solution for blob would be.
> 
> Edit: Apparently it was changed to 25 tc before I posted this. Point still stands, ninja shouldn't be this accessible. How many times have you seen multiple ninjas in a round that weren't bussed in?
there already is one. it's crew blob. a crewmember turns into blob.

2024-08-17 04:43 UTC, NargaInDisguise commented
Again, I really liked when you made it so that crew could mid-roll ninja, that was definitely a much better solution to giving crew more antag types than this.

2024-08-17 05:24 UTC, BurgerLUA commented
I like this as an alternative of people ghosting to get antags. I'd be happy with this being added and ninja from midround being removed.

2024-08-17 12:40 UTC, Majkl-J commented
> I like this as an alternative of people ghosting to get antags. I'd be happy with this being added and ninja from midround being removed.

As of recent we have decided to keep midround rolls happening for ghosts as the current ghost population is so low it's hard to even get people into ERTs when they are needed. It is a necessary evil to keep rounds flowing.

2024-08-17 19:07 UTC, SovietSpaghetti commented
> > I wouldn't call ninjas wizard-level by any stretch of the imagination, but they're definitely strong, and considering how many traitors roll every round this definitely shouldn't be as accessible as it is. Especially considering you still have 5 tc left over. One ninja is enough to fuck over the station, but multiple ninjas with access to a traitor uplink all for the threat cost of roundstart traitors is nuts. If this is your idea of a better alternative to ghost-rolling antags I shudder to think of what your solution for blob would be.
> > Edit: Apparently it was changed to 25 tc before I posted this. Point still stands, ninja shouldn't be this accessible. How many times have you seen multiple ninjas in a round that weren't bussed in?
> 
> there already is one. it's crew blob. a crewmember turns into blob.

Crew blob is disabled here to my knowledge. Don't think I've seen it once. Crew blob is also involuntary and happens to anyone with it enabled at any time.

2024-08-21 04:47 UTC, StrangeWeirdKitten requested changes
Having the ability for every traitor in a given round to have the direct ability to upgrade themselves into a signifigantly more powerful antag without cap, or limitation seems like a massive source of frustration. Especially since this is ninja we're talking about; our resident glass cannon with extremely high mobility whose abilities have a wide, tangable impact on the round. Every traitor round doesn't need to also be a ninja round, let alone _every_ traitor becoming a ninja. @Majkl-J mentioned something about a random chance inside a random item kit or a supply crate where it's not every traitor, every round, versus it just being flat purchasable via uplink as an every round thing.

2024-08-21 04:54 UTC, projectkepler-ru commented
The alternative is you could role restrict this so that its only purchasable by curator or something. I think it fits em well enough

2024-08-21 05:00 UTC, projectkepler-ru requested changes
Re iterating my review proper on what needs to be done
Option
A) the Ninja need some sort of limit on how many can actually gets it




B) You could instead make the ninja kit a ninja-in-training kit that isn't as powerful as the full spider clan ninja


C)  the kit could be role restricted to something appropiate to it

2024-08-21 16:38 UTC, YakumoChen commented
B already exists, there is a ninja bundle in base tg code that comes with a katana (a regular one) and other ninja-y antag gear

2024-09-08 20:17 UTC, StrangeWeirdKitten commented
Cleaning up old PRs. Feel free to reopen with the changes mentioned.

2024-09-08 20:17 UTC, closed without merging