Deer
Bubberstation/Bubberstation pull request #1979
Opened 2024-08-20 05:26 UTC by shayoki

## About The Pull Request

This PR adds five new antler types made by me. And un-whitelists a clothing set by request.

## Why It's Good For The Game

More variety for deer and related characters with antlers will have more options to choose from, over the little selection there was. Additionally, the player 'Leafy' requested their donator items to no longer have restrictions. This also fulfills the long awaited request from the player 'ironknight' to fix the whitelist for their jacket.

Screenshots and local tests:

![prev_short](https://github.com/user-attachments/assets/fb46c9f9-3b0e-4953-9a5e-a125771836f8)
Short Antlers

![prev_complex](https://github.com/user-attachments/assets/dcd20c5f-809f-4879-8801-99f7b95fc9cd)
Complex Antlers

![prev_large](https://github.com/user-attachments/assets/a028ed20-2dbc-4aff-8621-9ce7c034a015)

Large Antlers

![prev_regal](https://github.com/user-attachments/assets/e54ce862-7bc2-4a76-9394-ba29611e5f61)
Regal Antlers

![prev_monarch](https://github.com/user-attachments/assets/9e1d8ef9-e3df-455e-84f6-6eaf3e627f9f)
Monarch Antlers

![image](https://github.com/user-attachments/assets/2e0f36e7-0a8c-4885-a33b-46c8c7e6442c)
wow

## Changelog

:cl:
add: Five more new antler types.
/:cl:

2024-08-20 06:05 UTC, projectkepler-ru approved these changes
Sprites are fine

2024-08-20 07:11 UTC, ReturnToZender commented
It looks like you removed the items themselves rather than their whitelist

2024-08-21 10:52 UTC, Majkl-J commented on modular_zubbers/code/modules/customization/sprite_accessories/horns.dm
> +	icon_state = "antlersless"
Also please repath the icon states with snakecase

```suggestion
/datum/sprite_accessory/horns/bubber/big/antlers //sprites by Gavla
	name = "Aged Antlers"
	icon_state = "antlersmore"

/datum/sprite_accessory/horns/bubber/big/antlers/large
	name = "Large Antlers"
	icon_state = "antlersmost"

/datum/sprite_accessory/horns/bubber/big/antlers/regal
	name = "Regal Antlers"
	icon_state = "antlersregal"

/datum/sprite_accessory/horns/bubber/big/antlers/monarch
	name = "Monarch Antlers"
	icon_state = "antlersmonarch"

/datum/sprite_accessory/horns/bubber/big/antlers/short	//end of sprites by Gavla
	name = "Short Antlers"
	icon_state = "antlersless"
```

2024-08-23 07:24 UTC, Majkl-J requested changes

2024-08-23 07:24 UTC, Majkl-J commented on modular_zubbers/code/modules/customization/sprite_accessories/horns.dm
> +	icon_state = "antlersmore"
Snakecase these, remember to do so in the DMI as well

```suggestion
	icon_state = "antlers_more"
```

2024-08-23 07:24 UTC, Majkl-J commented on modular_zubbers/code/modules/customization/sprite_accessories/horns.dm
> +	icon_state = "antlersmost"
Ditto

2024-08-23 07:24 UTC, Majkl-J commented on modular_zubbers/code/modules/customization/sprite_accessories/horns.dm
> +	icon_state = "antlersregal"
Ditto

2024-08-23 07:24 UTC, Majkl-J commented on modular_zubbers/code/modules/customization/sprite_accessories/horns.dm
> +	icon_state = "antlersmonarch"
Ditto

2024-08-23 07:24 UTC, Majkl-J commented on modular_zubbers/code/modules/customization/sprite_accessories/horns.dm
> +	icon_state = "antlersless"
Ditto

2024-08-24 07:34 UTC, Majkl-J approved these changes

2024-08-24 08:57 UTC, merged