Reworks (mostly) and renames all the storytellers and improves the code. (TM Only, for now)
Bubberstation/Bubberstation pull request #1980
Opened 2024-08-21 02:32 UTC by BurgerLUA

## About The Pull Request

Adds a new storyteller tag called TAG_CHAOS which is assigned to chaotic events. So far, this is assigned to Blob, Meteors, Abductor, Rampant Brand Intelligence, Space Vines, Portal Storms, MALF, Nuke Ops, Space Dragon, Xenomorph Infestation, and Spider Infestation.

All existing storytellers have been renamed and tweaked to what they're supposed to do, if they were known to have issues (see below).

Changes how antag cap calculation works. Makes it so that antag count is limited by security's population as well as population count.

### Current Storytellers
The Gamer: A remake of the warrior. Has a focus on combat events and antagonist spawns, while limiting destructive events.

Default Andy: The default storyteller. Just a renamed guide.

The Bomb: A remake of the DemoMan. Practically unchanged from The DemoMan.

Extended: A remake of The Ghost. Practically unchanged from The Ghost.

The Fragile: A working (allegedly) version that existed before. It had a tendency to spawn all the antagonists because an antag divisor wasn't set.

The Chill: A remake of The Guide. Limits chaotic, combat, and destructive events.

The Clown: A remake of The Jester. Practically unchanged from The Jester.

## Why It's Good For The Game

Storyteller seems to be having issues right now where non-chaotic storytellers are turning into chaos. Part of the reason for this is that people have different expectations of storytellers than what it actually does, and the storyteller system doesn't really have consideration if an event is chaotic.

According to Odairu, another issue that needs to be fixed is how the antag cap isn't updated while antags are being spawned, so that probably needs to be fixed in another PR.

## Proof Of Testing

Untested.

## Changelog

:cl: BurgerBB
balance: Reworks (mostly) and renames all the storytellers and improves the code.
/:cl:

2024-08-21 03:15 UTC, Odairu commented
>According to Odairu, another issue that needs to be fixed is how the antag cap isn't updated while antags are being spawned, so that probably needs to be fixed in another PR.

for reference, this is for round start where story teller is spending points to make ROUNDSTART antags, since before the round actually starts and people have loaded in, regardless of how many antags story teller rolls for, there are no antags, so it can roll 3 times and on the third time it doesn't know it rolled 2 times before

2024-08-21 03:56 UTC, projectkepler-ru approved these changes

2024-08-21 05:30 UTC, nevimer approved these changes
I like it, but whats up with the file moving

2024-08-21 06:35 UTC, BurgerLUA commented
> I like it, but whats up with the file moving

For organization purposes, each storyteller gets its own file.

2024-08-21 06:49 UTC, Majkl-J requested changes
I like this, literally only a formatting nitpick (Also sobbing because this will cause conflicts with teller 2.0 for which I had the same idea but oh well I should've been faster)

Anyhow, burger cooking moment

2024-08-21 06:49 UTC, Majkl-J commented on modular_zubbers/code/modules/storyteller/gamemode.dm
> +	return CEILING( clamp(get_correct_popcount() / storyteller.antag_divisor + sec_crew,ANTAG_CAP_FLAT,sec_crew*1.5), 1 )
I'm not sure whether to trust ceiling in this, we used it before and for some reason it clamped the whole thing to one even though it makes no sense for it to do so. Whatever, we'll see in testing

```suggestion
	return CEILING(clamp(get_correct_popcount() / storyteller.antag_divisor + sec_crew, ANTAG_CAP_FLAT, sec_crew*1.5), 1)
```

2024-08-21 06:49 UTC, Majkl-J commented on modular_zubbers/code/modules/storyteller/storytellers/tellers/storyteller_peaceful.dm
> +		TAG_CHAOTIC = 0.1
To be honest chaotic could be knocked down to 0 on this one but up to you really

2024-08-21 06:49 UTC, Majkl-J commented on modular_zubbers/code/modules/storyteller/storytellers/tellers/storyteller_peaceful.dm
> +	welcome_text = "If you vote for this storyteller on Ice Box, you have no originality."
Okay this one is funny

2024-08-24 12:12 UTC, Majkl-J approved these changes
Has been working well, so I'll be looking to merge this whenever you consider it ready

2024-08-24 19:17 UTC, BurgerLUA commented
todo: some events don't exist in the storyteller folder, and need to be added to that

2024-08-27 20:31 UTC, Swiftfeather commented
Where's predictable chaos?

2024-08-27 21:45 UTC, BurgerLUA commented
> Where's predictable chaos?

It should still exist in here

2024-08-30 21:07 UTC, merged