Half modular, if you make me do this on skyrat I will cry because they do not have the feature this solves
Bubberstation/Bubberstation pull request #2013
Opened 2024-08-26 13:46 UTC by Odairu

## About The Pull Request
Makes it so ghosts can vote on transfers after the first one at 2:30 has happened

## Why It's Good For The Game
![image](https://github.com/user-attachments/assets/f5a4ec00-cf98-4532-82ca-de032fbcd352)

## Proof Of Testing
it compiles (I tested it and forgor screenshot)

## Changelog

:cl:
qol: ghosts can vote on transfers 2 - infinity
/:cl:

2024-08-26 13:50 UTC, Majkl-J requested changes

2024-08-26 14:18 UTC, Majkl-J requested changes
Just this and it's done

2024-08-26 14:18 UTC, Majkl-J commented on modular_zubbers/code/modules/voting/_votes.dm
>  	allow_ghosts = FALSE
```suggestion
/datum/vote/transfer_vote
	allow_ghosts = FALSE
	// Has this vote been run before?
	var/has_ran = FALSE

/datum/vote/transfer_vote/can_mob_vote(mob/voter)
	if(has_ran)
		return TRUE
	return ..()

/datum/vote/transfer_vote/finalize_vote(winning_option)
	has_ran = TRUE
	return ..()
```

2024-08-27 03:01 UTC, projectkepler-ru approved these changes

2024-08-27 06:56 UTC, merged