Vetted System conversion to SQL
Bubberstation/Bubberstation pull request #2075
Opened 2024-09-12 03:21 UTC by nevimer

## About The Pull Request

This PR will convert the vetted system to SQL. It will populate the with entries from the old config file, and then that file can be safely removed after it is imported. Also adds three verbs, one to force a conversion, one to add, and one to remove a ckey from the database. The admin who adds a user is record in the DB. 

## Why It's Good For The Game

## Proof Of Testing

## Changelog

:cl:
refactor: Vetted system is now using SQL and improved. 
/:cl:

2024-09-12 04:54 UTC, ReturnToZender commented
I'm finally free

2024-09-12 06:05 UTC, StrangeWeirdKitten requested changes

2024-09-12 06:05 UTC, StrangeWeirdKitten commented on modular_zubbers/code/modules/vetted/vetted.dm
> +		SSplayer_ranks.vetted_controller.remove_player(ckey = user_del)
make sure these procs give admin_log feedback.

2024-09-12 06:54 UTC, Cyprex commented
Should increment schema version

2024-10-04 11:12 UTC, StrangeWeirdKitten commented
Merging due to the importance of it.

2024-10-04 11:16 UTC, merged