'Re-memes' certain languages.
Bubberstation/Bubberstation pull request #21
Opened 2023-02-06 19:55 UTC by theselfish

## About The Pull Request
Host request.
These were removed for dumb reasons. They are now back.
## How This Contributes To The Skyrat Roleplay Experience

I don't know. We are still not Skyrat.

## Proof of Testing

<details>
<summary>Screenshots/Videos</summary>
  I can't test this. Why? I'm clueless, but whenever I use your build cmd/bat it throws an error I have quite literally never seen before.
![image](https://user-images.githubusercontent.com/102828457/217071387-429c9614-2693-490e-a003-2c8143462753.png)

</details>

## Changelog

:cl: Cursor
add: Pirate, neko and Common are back.
/:cl:

2023-03-12 07:57 UTC, Cyprex commented on modular_skyrat/modules/customization/modules/language/nekomimetic.dm
> +	secret = FALSE //BUBBERSTATION EDIT ORIGINAL secret = FALSE
This won't work, this needs to be scoped

2023-03-12 07:57 UTC, Cyprex commented on modular_skyrat/modules/customization/modules/language/piratespeak.dm
> +	secret = FALSE //BUBBERSTATION EDIT ORIGINAL secret = TRUE
same as above

2023-03-12 07:57 UTC, Cyprex requested changes
see above

2023-06-12 02:32 UTC, Sweettoothart commented
Why is yangu being removed? Let Asian characters not have to speak mew meow language.

2023-07-17 03:58 UTC, nevimer commented
stale

2023-07-17 03:58 UTC, closed without merging