Reverting PR #1223, which removed gun safeties
Bubberstation/Bubberstation pull request #2170
Opened 2024-10-02 20:24 UTC by Boviro

## About The Pull Request
This PR reverts Bubberstation/Bubberstation#1223 aka "RULE 1: Always keep the muzzle pointed in a safe direction", which disabled gun safeties on Bubberstation.
Does not add new content, solely re-enables gun safeties by reverting the PR that disabled them.
Untested but it should work fine, as the original simply comments out the line that adds safeties.

## Why It's Good For The Game
Gun safeties are a good feature for preventing accidental misclicks and shooting a gun. On top of this, there is an RP aspect to disabling a safety during an interaction when one or more people have a gun. It's easy to ignore if you don't want to use it and quite helpful if you do want to use it. Along with this, there's an 80% majority for re-adding safeties on the #suggestions channel in the discord:
![image](https://github.com/user-attachments/assets/a1d73079-b72e-4774-9a48-8c33b4854c34)
Ultimately I believe people want this to be re-added and for a mechanic that is ultimately optional I don't see a reason to deny it.

## Proof Of Testing
N/A, this revert shouldn't cause issues. I can locally test it to ensure it works if you would like.

## Changelog

:cl:
add: Re-adds gun safeties
/:cl:

2024-10-02 20:36 UTC, StrangeWeirdKitten commented
If we're going to want this back, a straight revert isn't going to get merged, Safties need to get disabled after the first click.

2024-10-02 20:52 UTC, Boviro commented
If I may ask, why exactly would we need that feature?

2024-10-02 20:59 UTC, StrangeWeirdKitten commented
Because the primary issue with gun safties was due to their clunky nature on an item that's supposed to be responsive and is typically used in the heat of the moment where players trip up over it because they forgot to click the action button. I really do not want guns to be clunky and unintititive to use. They're click and shoot, and should be click and shoot, even if it means someone might ocassionally click and shoot by accident. 

I'm not really a fan of the action button either, since I really hate action button clutter- but it's not something I'm going to strictly die on.

2024-10-02 21:06 UTC, Boviro commented
FYI it has a hotkey as well (Alt-F if i recall) but I understand where you're coming from and I'll see if I can do something about disabling the safety when you fire.

2024-10-02 21:31 UTC, Swiftfeather commented
The hotkey was trash just like the whole safeties system was

2024-10-02 23:08 UTC, Boviro commented
Correction: the hotkey was actually Shift+F, new commit makes guns disengage their safety if you attempt to fire them with the safety on, locally tested.

2024-10-02 23:44 UTC, shellspeed1 commented
Time for security and antags alike to fumble the gun safeties so we can laugh about it.

2024-10-03 02:15 UTC, YakumoChen commented
I never remember to use the hotkey for unholstering from the belt in the heat of the moment, I'm definitely not going to remember a hotkey so I can shoot my gun in the first place.

The only thing this will lead to is either:
a) people fumbling safeties in the middle of firefights again
b) people not fumbling safeties because they disengage safeties as soon as they pick up any gun, invalidating the entire point

2024-10-03 02:19 UTC, Boviro commented
This is why guns will now disengage their safeties once you pull the trigger while the safety is engaged. This prevents safeties from serving as a major hindrance in an emergency but should stop most friendly-fire incidents

2024-10-04 09:17 UTC, Arturlang commented
This is fine AS LONG as there's not a huge off action button for safeties, too much action button bloat

2024-10-10 08:51 UTC, StrangeWeirdKitten requested changes
Have the safties off by default.

2024-10-12 07:03 UTC, Boviro commented
Honestly I don't think that makes sense. I mean safeties are already disabled when you click now so like, I don't see how having them off by default would make gunplay that much smoother. And this change would solve the issue of picking up a gun and just using  it, so why have the safety disable on click? I don't really think it makes sense to have both of them.

2024-10-12 07:20 UTC, Boviro commented
Like, I have a commit I can push at any time to switch it to being disabled by default, but I don't know if it's necessary to have both the self-disabling safeties and have them off by default. Kinda feels like it compromises their effectiveness too much.

2024-10-12 17:27 UTC, Boviro commented
Just one or the other does that fine, there's no need to have both

2024-10-12 18:12 UTC, StrangeWeirdKitten commented
Just do both, and it leaves it as an optional mechanic instead of forcing it on everyone who wants to use a gun. I want this mechanic to remain as uncumbering as possible.

- The mechanic then becomes optional.
- Guns set to saftey then don't impeed someone wanting to shoot said gun because it'll toggle off if they're spamming the click.

2024-10-12 20:01 UTC, Boviro commented
Okay I understand that but if you don't want to interact with the mechanic, then you're most likely never going to touch the toggle, making the click to toggle redundant. If you want to interact with the mechanic, then you're most likely going to prefer the extra safety of not having it turn off when you click once. So I don't see the point in having both of them.

2024-10-12 20:10 UTC, StrangeWeirdKitten commented
The requirement presented is it to be an opt in, not an opt out. Hence every gun having it off by default while anyone picking up a gun is still able to disable it (if it was disabled) and primarily so if someone does pick up a gun with safties on, they aren't spending valuable time clicking the trigger without it then disabling for them. I want weapons to remain responsive for everybody who comes across it while still allowing the people who may want the extra safety to then have the extra cushioning if they opt into having it.

2024-10-12 20:13 UTC, Boviro commented
Fair enough. Gun safeties are now all set to OFF by default

2024-10-12 20:14 UTC, StrangeWeirdKitten commented
Aka if it exists, it's important to be an action button. But that doesn't mean I won't entirely rework its location on the screen in the future when we break off from Skyrat.

2024-10-12 20:15 UTC, Boviro commented
That's fine, I mostly just want them back

2024-10-12 20:15 UTC, StrangeWeirdKitten commented
Np

2024-10-13 02:23 UTC, StrangeWeirdKitten commented on modular_skyrat/modules/gun_safety/code/safety_component.dm
> +/datum/component/gun_safety/Initialize(safety_currently_on = FALSE)
```suggestion
/datum/component/gun_safety/Initialize(safety_currently_on = FALSE) // Bubber Edit - Org: True
```

2024-10-13 02:24 UTC, StrangeWeirdKitten commented on modular_skyrat/modules/gun_safety/code/safety_component.dm
> +		toggle_safeties(user)
```suggestion
		user.balloon_alert(user, "The safety disengages!") // Bubber Edit
		toggle_safeties(user) // Bubber Edit
```

2024-10-13 02:30 UTC, merged