Changes protogen snout sprite to look like an actual protogen visor
Bubberstation/Bubberstation pull request #2175
Opened 2024-10-03 22:44 UTC by Fn-OS

## About The Pull Request

resprites the protogen snout to look like a visor, rather than a snout

## Why It's Good For The Game
Makes the protogen visor eye candy and not doodoo dogshit

## Proof Of Testing
![image](https://github.com/user-attachments/assets/548d556e-fe42-4f6d-ac0f-569b7dd7e398)

## Changelog
Changes protogen snout sprite

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-10-03 23:00 UTC, Kurzaen commented
About time, hell yeah.

2024-10-03 23:19 UTC, ShockOmega commented
wowoozay very nice

2024-10-04 01:06 UTC, RadiantFlash7 commented
I'm not the biggest fan of the tajaran muzzle sprite change, to be honest. It's almost too circular, with the muzzle not being pronounced enough. It also makes tajaran seem less like their own thing and instead anthro cats- which I suppose they /are/ but historically they were always closer to lynx's then house cats, iirc.

2024-10-04 01:12 UTC, Fn-OS commented
> I'm not the biggest fan of the tajaran muzzle sprite change, to be honest. It's almost too circular, with the muzzle not being pronounced enough. It also makes tajaran seem less like their own thing and instead anthro cats- which I suppose they /are/ but historically in ss13 they were always closer to lynx's then house cats, iirc.
> 
> That said, I don't even use the old muzzle, because none of the tajaran markings actually work on it at the moment, as far as I can tell. So it's not like it's super great either.

I'm sadly nowhere near being even a decent spriter, this is really the best I could do. I haven't heard much about Tajaran being closer to lynx's but I don't know all too much of their lore either.

If I could, I'd make it a seperate sprite but this has already taken around ~3 hours and I don't want to fuck with VSC/Github even more.
It could be changed later on, but this is what I have for now.

2024-10-04 01:56 UTC, Odairu requested changes
The sprites should be moved to .dmi files under the modular_zubbers folder (wherever we have sprite accesories in there, and if there isnt one, one should be made) and then overwrite the file path where the original sprites are used.

2024-10-04 01:58 UTC, Conormackgegore commented
You'll have to guide me through that later. Burnt out rn

2024-10-04 01:59 UTC, Conormackgegore commented
Oh I'm not even on the right account on mobile. Damn

2024-10-05 00:19 UTC, StrangeWeirdKitten requested changes
For the Taj muzzle, make it a new muzzle type so people can pick it if they want to while still keeping the old one.

2024-10-06 22:29 UTC, Fn-OS commented
Okay, fixing this PR today. Old tajaran sprite will be kept, sprites will be moved to the correct folder and I'll try to figure out how to get them into the char creation menu

2024-10-07 00:10 UTC, Fn-OS commented
PR is fixed. Again, Tajaran sprite is NO LONGER being replaced per request

2024-10-07 00:55 UTC, lessthnthree commented on modular_zubbers/code/modules/customization/sprite_accessories/snouts.dm
> +/datum/sprite_accessory/snouts/mammal/cat
```suggestion

/datum/sprite_accessory/snouts/mammal/cat
```

2024-10-07 02:25 UTC, lessthnthree approved these changes

2024-10-07 02:46 UTC, merged