[TestMerge Only] ITS A SPOOKY MONTH
Bubberstation/Bubberstation pull request #2184
Opened 2024-10-06 18:22 UTC by IgiariValkyr

## About The Pull Request

Makes the halloween event last all month, so players can play the creepy things like skeletons and vampires (non-hemophage or bloodsucker) and zombies (wait we have those already) and dullahans (this is mostly for dullahans). I think it also changes player ghosts too or something. I can't remember.

## Why It's Good For The Game

![B87](https://github.com/user-attachments/assets/4a748e94-1df9-4179-965b-c20d477773f2)

## Proof Of Testing

It's a single line edit I did for Skyrat a few years ago too. It'll work just fine.

## Changelog

:cl:
qol: Spooky Month is now actually a month long!
/:cl:

2024-10-06 18:24 UTC, lessthnthree requested changes

2024-10-06 18:24 UTC, lessthnthree commented on code/modules/holiday/holidays.dm
> +	begin_day = 1 //bubberstation edit for spooky month - default: 29th of october
```suggestion
	begin_day = 1 // BUBBER EDIT CHANGE - HALLOWEEN - ORIGINAL: 29
```

2024-10-06 18:25 UTC, lessthnthree commented
I don't see why it has to be TM Only, though.

2024-10-06 18:27 UTC, IgiariValkyr commented
> I don't see why it has to be TM Only, though.

Cause I understand how bad the halloween code is, and having it active the whole month may cause unwanted lag and what not. And it may be decided later on to not be a permanent change. So marking it as TM only means we aren't making the full commitment and possibly forgetting we set it to all month in the event something gets out of hand.

2024-10-06 18:30 UTC, lessthnthree commented
> > I don't see why it has to be TM Only, though.
> 
> Cause I understand how bad the halloween code is, and having it active the whole month may cause unwanted lag and what not. And it may be decided later on to not be a permanent change. So marking it as TM only means we aren't making the full commitment and possibly forgetting we set it to all month in the event something gets out of hand.

I'd run it as a TM candidate like most PRs, it's a one line date change. PR title doesn't ultimately matter, though.

2024-10-17 20:23 UTC, lessthnthree commented
Superseded by https://github.com/Bubberstation/Bubberstation/pull/2211

2024-10-17 20:23 UTC, closed without merging