Adds a new emote: Bonk
Bubberstation/Bubberstation pull request #2251
Opened 2024-10-22 16:39 UTC by xPokee

## About The Pull Request
Have you ever wanted to bonk someone on the head? Well now you can with the [*bonk emote](https://www.youtube.com/watch?v=C0XF57pK67g). Just aim at someone's head and hit them with the hand. I'd advise against doing it to borgs or synthetics though.. that sounds painful.

## Why It's Good For The Game
More variety of emotes.

## Proof Of Testing
It compiled and ran on my end without any runtimes or errors. Everything has been tested to work.

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
add: added a bonk emote
sound: added the coconut hit 01 sound effect to the code
/:cl:

2024-10-22 18:28 UTC, YakumoChen commented
Where is this sound sourced from?

2024-10-22 19:33 UTC, xPokee commented
> Where is this sound sourced from?

It's coconut hit 01, the bonk sound from a bunch of media. The other one is just the toolbox hit sound

2024-10-23 03:47 UTC, YakumoChen commented
Oh, I saw the license, that's all fine then

2024-11-02 21:02 UTC, lessthnthree approved these changes

2024-11-04 19:31 UTC, lessthnthree commented
Someone on the live server said this didn't work properly. Not sure if true or they're just ~~holding~~ doing it wrong.

2024-11-04 23:08 UTC, lessthnthree commented
- It only bonks if the head is targeted. It fails and provides no feedback if you try to use it against any other body zone.
- It doesn't clear itself after bonking someone in the head

2024-11-04 23:12 UTC, lessthnthree requested changes
- It only bonks if the head is targeted. It fails and provides no feedback if you try to use it against any other body zone.
- It doesn't clear itself after bonking someone in the head

https://github.com/user-attachments/assets/0ceea4da-31fc-4960-8ffc-8dc55902cec4

2024-11-07 12:58 UTC, Majkl-J requested changes
Also, how does this handle the lack of head, like synth brains for example?

2024-11-07 12:58 UTC, Majkl-J commented on modular_zubbers/code/modules/emotes/hand_items.dm
> +	else if((issilicon(bonked) && user.zone_selected == BODY_ZONE_HEAD))
No need to check twice if we do this
```suggestion
	if(user.zone_selected != BODY_ZONE_HEAD)
		to_chat(user, span_warning("You can't bonk someone on the head if you aren't aiming for their head!"))
		return
	if((issilicon(bonked))
```

2024-11-07 12:58 UTC, Majkl-J commented on modular_zubbers/code/modules/emotes/hand_items.dm
> +	else if((bonk_victims_head.biological_state & BIO_METAL && user.zone_selected == BODY_ZONE_HEAD))
Ditto
```suggestion
	else if((bonk_victims_head.biological_state & BIO_METAL)
```

2024-11-07 12:58 UTC, Majkl-J commented on modular_zubbers/code/modules/emotes/hand_items.dm
> +	else if(!issilicon(bonked) && user.zone_selected == BODY_ZONE_HEAD)
Ditto, we already have a case for both of these above
```suggestion
	else
```

2024-11-07 12:58 UTC, Majkl-J commented on modular_zubbers/code/modules/emotes/hand_items.dm
> +		qdel(src)
Instead of copypaste qdels we can just qdel at the end
```suggestion
	qdel(src)
```

2024-11-07 12:58 UTC, Majkl-J commented on modular_zubbers/code/modules/emotes/hand_items.dm
> +		qdel(src)
Ditto
```suggestion
		
```

2024-11-07 12:58 UTC, Majkl-J commented on modular_zubbers/code/modules/emotes/hand_items.dm
> +		qdel(src)
Ditto
```suggestion
		
```

2024-11-12 08:44 UTC, merged