Solar Arms Recreation, Inc. Gun Import Company
Bubberstation/Bubberstation pull request #2252
Opened 2024-10-22 18:05 UTC by Boviro

## About The Pull Request

NOT CURRENTLY FINISHED. OPENING PR FOR REVIEW AND BALANCE RECOMMENDATIONS. STILL MISSING IMPORT COMPANY LISTINGS AND A WEAPON, ALONG WITH LACKING POLISH.
Adds an import company for cowboy-era weapons and adds those lever-action weapons.

## Why It's Good For The Game

Lever action weapons are pretty cool. Also, it would add a rifle and shotgun that can be used one-handed (at great cost to the user)

## Proof Of Testing

Code that is currently in place has been tested repeatedly, works as intended. Will update with screenshots and videos later.

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
add: Adds lever-action weapons (import company pending)
image: Adds sprites and animations for lever-action weaponry
/:cl:

2024-10-24 18:09 UTC, Boviro commented
also gives long guns a slight damage increase to go with their more difficult use compared to other weapons of their caliber

2024-11-06 23:39 UTC, Boviro commented
Import Company is finalized, weapons are in a functional and polished state, sprites are done, things are (hopefully) balanced. Gonna revise the PR body and then un-draft it because i'm losing motivation rapidly and i'm getting sick of this project.

2024-11-08 01:44 UTC, nevimer requested changes

2024-11-08 01:48 UTC, Boviro commented on code/__DEFINES/~skyrat_defines/cargo_import_companies.dm
> +#define CARGO_COMPANY_SAR_INC (1<<11)
Aware, but still figured it's best to keep up the practice just for posterity

2024-11-08 01:49 UTC, Boviro commented on tgstation.dme
> +#include "modular_skyrat\modules\company_imports\code\armament_datums\sar_inc.dm"
This one's on me, I meant to include that in modular_zubbers SAR files instead of the modular_skyrat folder, I'll resolve that in a second

2024-11-08 20:49 UTC, Paxilmaniac requested changes
![image](https://github.com/user-attachments/assets/aeb9ec4e-370b-4c31-9347-1f6f35f98eb6)

2024-11-08 22:58 UTC, Boviro commented
Paxil please offer something constructive instead of just being a twit thanks

2024-11-08 23:13 UTC, Boviro commented
You know what that's a little mean but still do try to give constructive criticism instead of just posting a gif like it will manifest your perfect changes

2024-11-11 02:09 UTC, Boviro commented
ough oops

2024-11-11 02:18 UTC, Boviro commented
Oh good I didn't realize I could do that

2024-11-17 08:57 UTC, Majkl-J reviewed
Probably needs a tm to see if it is balanced or not

2024-11-17 08:57 UTC, Majkl-J commented on code/__DEFINES/~skyrat_defines/manufacturer_strings.dm
> +#define COMPANY_SAR_STOCK "It has the text <b>[span_blue("Solar Arms Recreations, Inc.")]</b> engraved into it, along with a stylized depiction of the <b>[span_blue("Sol sytem")]</b> and a <b>[span_b
```suggestion
#define COMPANY_SAR_STOCK "It has the text <b>[span_blue(COMPANY_NAME_SAR_INC)]</b> engraved into it, along with a stylized depiction of the <b>[span_blue("Sol sytem")]</b> and a <b>[span_blue("cobalt blue SAR seal of quality")]</b> burned into the stock."
```

2024-11-17 08:57 UTC, Majkl-J commented on code/__DEFINES/~skyrat_defines/manufacturer_strings.dm
> +#define COMPANY_SAR_NOSTOCK "It has the text <b>[span_blue("Solar Arms Recreations, Inc.")]</b> engraved into it, along with a stylized depiction of the <b>[span_blue("Sol sytem")]</b>."
```suggestion
#define COMPANY_SAR_NOSTOCK "It has the text <b>[span_blue(COMPANY_NAME_SAR_INC)]</b> engraved into it, along with a stylized depiction of the <b>[span_blue("Sol sytem")]</b>."
```

2024-11-17 08:57 UTC, Majkl-J commented on code/__DEFINES/~skyrat_defines/manufacturer_strings.dm
> +#define COMPANY_SAR_BARREL "It has the text <b>[span_blue("Solar Arms Recreations, Inc.")]</b> engraved into it, along with a stylized depiction of the <b>[span_blue("Sol sytem")]</b> and a <b>[span_
```suggestion
#define COMPANY_SAR_BARREL "It has the text <b>[span_blue(COMPANY_NAME_SAR_INC)]</b> engraved into it, along with a stylized depiction of the <b>[span_blue("Sol sytem")]</b> and a <b>[span_blue("cobalt blue SAR seal of quality")]</b> engraved onto the barrel."
```

2024-11-17 08:57 UTC, Majkl-J commented on modular_skyrat/modules/company_imports/code/company_datums.dm
> +// Bubber Edits End
No need to mark bubber edits in skyrat folders anymore
```suggestion
// SAR Inc. sells recreations of antique firearms
/datum/cargo_company/sar_inc
	name = COMPANY_NAME_SAR_INC
	company_flag = CARGO_COMPANY_SAR_INC
	cost = 2000
	cost_change_lower = -1000
	cost_change_upper = 1000
	can_roundstart_pick = FALSE

```

2024-11-17 08:57 UTC, Majkl-J commented on modular_zubbers/code/modules/cargo/expressconsole.dm
> +	COMPANY_NAME_SAR_INC
The extra comma isn't a meme it makes future conflict resolution and gitblaming faster
```suggestion
	COMPANY_NAME_SAR_INC,
```

2024-11-17 09:10 UTC, Majkl-J commented
Also I feel like the sprites are extremely flat and need some touchup

2024-11-17 21:48 UTC, Boviro commented
Suggested changes from Majkl-J were added, also a typo that I only caught while I was adding those (Sol sytem instead of Sol system, in manufacturer_strings.dm)

2024-11-18 17:32 UTC, KazooBard commented
More guns to the arsenal of limitless guns on server. Like there isn't gun bloat already. We have semiauto rifles, we have autorifles, 5 types of revolvers, multiple boltactions, jesus christ why do we need even _more_ guns? For a cowboy gimmick? If that'd be the reason then why not just add it as a conversion kit to lessen confusion on gunstats.

2024-11-18 19:31 UTC, projectkepler-ru commented
I'll takeover handling this

2024-12-10 07:40 UTC, Majkl-J commented
Since strange has disappeared into a deep pit Ill be handling this, DM me about the spriting adjustments

2024-12-14 15:33 UTC, RimiNosha commented
Not a fan of adding yet more guns. It should replace an existing one in a somewhat similar niche IMO.

2024-12-19 23:50 UTC, Boviro commented
i just remembered that this pr exists. rn it's kind of in limbo until i work up the motivation to keep working on it, so i'm going to set it back to draft for the forseeable future. sprite changes were in the works when i was last working on it and they look way better than the ones in this PR, but it's not complete yet and won't be until i can work up enough motivation to finish it off

2025-01-19 01:00 UTC, Boviro commented
if i don't regain the will to finish this by the end of the month i'm going to close the PR. the fork will stay up and i'll hold onto the changes in case i get the will to return to it after then, but i dont like the concept of this unfinished pr sitting here in draft because i don't have it in me to complete it.

2025-03-20 08:38 UTC, Majkl-J commented
Staling this out

2025-03-20 08:38 UTC, closed without merging