Adds Hemoglobin Iced Tea, a drink for hemophages
Bubberstation/Bubberstation pull request #2343
Opened 2024-11-05 21:19 UTC by CydiaButt13

## About The Pull Request

I play hemophages sometimes and we're constantly low on blood unless we're bugging genetics or medical or the bar. So just how synths have a welding fuel drink, I'm making hemos a blood drink.

## Why It's Good For The Game

This is great for hemos, bloodsuckers, and in a pinch when someone is low on blood, I suppose.

## Proof Of Testing

Took a dumb little video:

https://github.com/user-attachments/assets/13bedf27-a630-4467-b85d-1c7d6cc5d05e

summary>Screenshots/Videos</summary>

## Changelog

:cl:
add: Added sprite for blood_tea
add: Added vending machine option for blood_tea
/:cl:

2024-11-07 07:37 UTC, Genevesh commented
They're using light mode. How do I downvote someone's PR?

2024-11-07 08:46 UTC, Majkl-J requested changes
Needs to be modularized, and the icon moved

2024-11-07 21:24 UTC, CydiaButt13 commented
> They're using light mode. How do I downvote someone's PR?

you cant stop me

2024-11-07 22:49 UTC, CydiaButt13 commented
okay we're modularized

2024-11-08 15:01 UTC, Majkl-J requested changes

2024-11-08 15:48 UTC, CydiaButt13 commented on tgstation.dme
Ah, it appears some of my changes just reverted there yea, my bad. Hold on

2024-11-08 19:06 UTC, Majkl-J requested changes

2024-11-08 19:06 UTC, Majkl-J commented on modular_zubbers/code/modules/reagents/reagent_containers/cups/soda.dm
> +	icon_state = "modular_zubbers/icons/obj/drinks/soda.dmi"
```suggestion
	icon = "modular_zubbers/icons/obj/drinks/soda.dmi"
	icon_state = "blood_tea"
```

2024-11-08 20:29 UTC, Majkl-J approved these changes

2024-11-08 21:07 UTC, Majkl-J approved these changes

2024-11-08 21:08 UTC, merged