Adds a new mod module - mind swap - to illegal tech
Bubberstation/Bubberstation pull request #2419
Opened 2024-11-13 13:02 UTC by Odairu

## About The Pull Request
This module allows for the at-will body swapping between a suit AI and a player mob. At face value its not really useful for real mechanical purposes as, neither player will be able to be able to really do anything extra that their counterpart couldn't do. I just personally think its cool and could add some new cool scenarios for when wearing a suit AI

## Why It's Good For The Game
I've been told its hot and cool. Gives more reason/gameplay to suit AIs and the people wearing them

## Proof Of Testing
![image](https://github.com/user-attachments/assets/bf945365-7e5b-4921-8b5b-84c5386769c7)

https://github.com/user-attachments/assets/015b9e9d-8f30-482c-ba8a-c41f05fc466a

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
add: adds a new mod module
/:cl:

2024-11-13 13:13 UTC, Odairu commented
> Can we get a button to disable modsuit AI telemetry while we're at it so people can make MODsuit AIs for this stuff without messing with other things

out of scope, also a pain in the ass to do (since I had to do that while making my antag, and it'd be harder for a non-antag AI)

2024-11-13 13:27 UTC, aKromatopzia commented
> > Can we get a button to disable modsuit AI telemetry while we're at it so people can make MODsuit AIs for this stuff without messing with other things
> 
> out of scope, also a pain in the ass to do (since I had to do that while making my antag, and it'd be harder for a non-antag AI)

Yeah, I ken. Goodness knows we're not getting a full AI code refactor from TG either. But! I suppose since in the end any issues with this kind of stuff would be player/IC issue anyways. Hope certain folk actually cooperate with damage mitigation/control!

2024-11-13 21:47 UTC, YakumoChen commented
I'd rather this be limited to emag / traitors only, the crew printing full AIs explicitly to ride in their modsuit is powergaming as it is.

2024-11-13 21:54 UTC, sippykot commented
imo if the swapped ai/player talk it should still use their original voice instead of the voice of the other person

2024-11-18 08:08 UTC, Arturlang requested changes

2024-11-18 08:08 UTC, Arturlang commented on modular_zubbers/code/modules/research/designs/mechfab_designs.dm
> +		/datum/material/diamond =SMALL_MATERIAL_AMOUNT*5,
While indendation in this file is inconsistent, avoid contributing to it, put a space on each side of the =

2024-11-18 23:28 UTC, shellspeed1 commented
Actually, I like this idea  but the AI needs to take over the mod specifically with no ability for the player to mess with it imo.

2024-11-20 23:34 UTC, Swiftfeather commented
This is bugged in such a way that a player with no AI in the MOD, with the mind transfer module in the MOD, gets ghosted when depowering the suit. I dragged them back into their body but they were also unable to remove the module afterwards, it required a vv delete.

2024-12-10 07:33 UTC, Majkl-J requested changes

2024-12-10 07:33 UTC, Majkl-J commented on modular_zubbers/code/modules/mod/modules.dm
> +		balloon_alert(mod.wearer, "No AI present for swap.")
balloon alerts are not capitalized, and meant to be short
```suggestion
		balloon_alert(mod.wearer, "no AI present")
```

2024-12-10 07:33 UTC, Majkl-J commented on modular_zubbers/code/modules/mod/modules.dm
> +	wearer_key = mod.wearer.key
```suggestion
/obj/item/mod/module/mind_swap/on_suit_activation()
	ai_key = mod.ai_assistant?.key
	wearer_key = mod.wearer.key
```

2024-12-10 07:33 UTC, Majkl-J commented on modular_zubbers/code/modules/mod/modules.dm
> +	var/controller = WEARER_CONTROL
you could make this into a boolean, something like ai_control = FALSE, makes the switch logic lower down easier as well.

2024-12-10 07:33 UTC, Majkl-J commented on modular_zubbers/code/modules/mod/modules.dm
> +			controller = WEARER_CONTROL
ditto, with the change suggested above you can simplify this to

```suggestion
/obj/item/mod/module/mind_swap/proc/swap_minds()
	mod.wearer.ghostize(FALSE)
	mod.ai_assistant.ghostize(FALSE)
	if(ai_control)
		mod.wearer.key = wearer_key
		mod.ai_assistant.key = ai_key
	else
		mod.wearer.key = ai_key
		mod.ai_assistant.key = wearer_key
	ai_control = !ai_control
```

2024-12-10 09:36 UTC, Majkl-J approved these changes

2024-12-10 09:36 UTC, merged

2024-12-15 18:45 UTC, aKromatopzia commented
This has been used to give crew members AI shells, and AI organic bodies. You can argue it's a "drawback" to having no cameras, but wasn't "AI shouldn't have hands" something that's supposed to be held dearly with how much the research borg PR got gutted for it?

2024-12-15 20:45 UTC, Odairu commented
> This has been used to give crew members AI shells, and AI organic bodies. You can argue it's a "drawback" to having no cameras, but wasn't "AI shouldn't have hands" something that's supposed to be held dearly with how much the research borg PR got gutted for it?
> 
> Anyways, I must ask for this to be re-reviewed in some way because of that fact.

Its not like the organic can just use the shell whenever, you're not suddenly getting 2 AIs or an AI with hands since, anything the AI can do in the host body, the host can also do themself, and the AI can only do these things so long as they're in the suit with the host, you're not suddenly getting an extra pair of hands, you have two people who can now fill knowledge gaps the other doesn't, say, something engineering related needs done, the carbon doesn't know how, AI can swap and do it, they can't act independently of one another because they're tied by the suit, suit turns off, they switch back etc.

2024-12-16 01:41 UTC, aKromatopzia commented
> Its not like the organic can just use the shell whenever, you're not suddenly getting 2 AIs or an AI with hands since, anything the AI can do in the host body, the host can also do themself, and the AI can only do these things so long as they're in the suit with the host, you're not suddenly getting an extra pair of hands, you have two people who can now fill knowledge gaps the other doesn't, say, something engineering related needs done, the carbon doesn't know how, AI can swap and do it, they can't act independently of one another because they're tied by the suit, suit turns off, they switch back etc.

It was one person put into the MODsuit to puppet their own lifeless corpse around.

2024-12-16 04:57 UTC, TattoMoon commented
> > This has been used to give crew members AI shells, and AI organic bodies. You can argue it's a "drawback" to having no cameras, but wasn't "AI shouldn't have hands" something that's supposed to be held dearly with how much the research borg PR got gutted for it?
> > Anyways, I must ask for this to be re-reviewed in some way because of that fact.
> 
> Its not like the organic can just use the shell whenever, you're not suddenly getting 2 AIs or an AI with hands since, anything the AI can do in the host body, the host can also do themself, and the AI can only do these things so long as they're in the suit with the host, you're not suddenly getting an extra pair of hands, you have two people who can now fill knowledge gaps the other doesn't, say, something engineering related needs done, the carbon doesn't know how, AI can swap and do it, they can't act independently of one another because they're tied by the suit, suit turns off, they switch back etc.

Yeah so, watching the rounds recently I'm seeing a lot of people getting debrained and using the mind-swap module without permission so.. you have just introduced a way for people to turn themselves into an Ai and become practically unkillable, with most of their reasons being "Lol, mechanic go brrr."
I know from a previous PR, specifically the research cyborgs that one of the issues was "Ai with hands" and now we, do infact, have "AI with hands" as a reality. I think this PR as is, is not great for the server, and I should not have to explain why this isn't great. At least make this locked behind the traitor uplink or something, and not under illegal tech, please. I like the idea but having it be illegal tech is just a terrible idea, and is being proven to be a terrible idea.

2024-12-16 05:27 UTC, aKromatopzia commented
Thinking on it a bit more the issue might be at least alleviated by making the swap require a cKey in the body being swapped into