Operating Table Beep Boops
Bubberstation/Bubberstation pull request #2430
Opened 2024-11-15 01:20 UTC by nevimer

## About The Pull Request

Operating Tables Beep and Boop depending on patient state. 

## Why It's Good For The Game

Cinematic Moments and atmosphere

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
add: Added beeps and boops to operating tables. 
/:cl:

2024-11-15 02:32 UTC, ReturnToZender commented
Can you attach this to the operating computer instead of the actual table?

2024-11-15 04:51 UTC, IgiariValkyr commented
People in OOC are actively complaining about the noise and one even mentioned that the pitch hurts their ears because of prior damage.

Please. Just stop making things then testmerging them immediately. Let people look over them. Make videos of what they showcase. Don't make it a three hour complaint-fest.

2024-11-15 05:27 UTC, nevimer commented
fixed the loop issue and made it quieter.

2024-11-15 07:45 UTC, Shi3ly commented
I basically never comment, but purely for the sake of my sensitive hearing-- Please add a toggle so we can mute this client-side. It's all fine, but the flatline SFX is just way, way too much for me.

2024-11-16 03:00 UTC, SpringSkipper commented
the fact that you can hear this from thirteen tiles away is just obnoxious. It needs **way** more distance falloff. Four to six tiles max.

2024-11-16 07:56 UTC, Hislyna commented
PLEASE FOR THE LOVE OF GOD LET US DISABLE THIS

2024-11-17 13:13 UTC, sippykot commented
...why would this be a table thing
the computer should be handling it
the table is literally just a slab of silver

2024-11-17 22:50 UTC, nevimer commented
> ...why would this be a table thing the computer should be handling it the table is literally just a slab of silver

the beeps only emit from the computer and are controlled by it, if you had read the code/pr you would realize this....

2024-11-17 23:31 UTC, sippykot commented
> > ...why would this be a table thing the computer should be handling it the table is literally just a slab of silver
> 
> the beeps only emit from the computer and are controlled by it, if you had read the code/pr you would realize this....

i read the description... which is supposed to describe the pr
i guess im fine with it if its not too loud or annoying

2024-11-18 23:38 UTC, Arturlang requested changes

2024-11-18 23:38 UTC, Arturlang commented on code/game/objects/structures/tables_racks.dm
> +		computer.muted = FALSE // BUBBER EDIT
This runtimes on integration tests due to the computer not being nullchecked

2024-11-18 23:38 UTC, Arturlang commented on modular_zubbers/code/modules/beepbooptable/table.dm
> +		playsound(computer, pick('modular_zubbers/sound/machines/operating_table/ekg_alert.ogg', 'modular_zubbers/sound/machines/operating_table/flatline.ogg'), 5, ignore_walls = FALSE, extrarange = SHORT_
My main complaint is with the flatline sound, it's not good for my ears

2024-11-18 23:38 UTC, Arturlang commented on modular_zubbers/code/modules/beepbooptable/table.dm
> +/obj/machinery/computer/operating/
There's a / on the end of this path for some reason

2024-11-19 00:29 UTC, Arturlang commented on modular_zubbers/code/modules/beepbooptable/table.dm
> +		playsound(computer, pick('modular_zubbers/sound/machines/operating_table/ekg_alert.ogg', 'modular_zubbers/sound/machines/operating_table/flatline.ogg'), 5, ignore_walls = FALSE, extrarange = SHORT_
https://discord.com/channels/1059199070016655462/1097484328012886067/1308227352605491213

2024-11-19 00:42 UTC, Arturlang commented on modular_zubbers/code/modules/beepbooptable/table.dm
> +		playsound(computer, pick('modular_zubbers/sound/machines/operating_table/ekg_alert.ogg', 'modular_zubbers/sound/machines/operating_table/flatline.ogg'), 5, ignore_walls = FALSE, extrarange = SHORT_
Likely will need to up the volume when you add it

2024-11-19 02:26 UTC, Shi3ly commented
gonna make another comment; I appreciate that you can mute it AT the console, that's _something,_ But I'd really like if there was a client side full mute, or something of that sort. In game/sound preferences, Same way we can turn off admin sounds or related effects that might be annoying. 

The beeping is whatever, but that death drone is going to trigger a migraine if I sit around it long. It's just too much :(

2024-11-19 12:19 UTC, Arturlang commented
@Shi3ly trying to figure out a better variant of the beeping drone that doesn't hurt

2024-11-20 01:11 UTC, Shi3ly commented
> @Shi3ly trying to figure out a better variant of the beeping drone that doesn't hurt

I do appreciate it and it'll probably be a lot better for plenty of players, but regardless of the intensity of it-- My audio sensitivity probably won't agree with it. It's less about the sound effect and more about the drone of it. The duration, the frequency, ETC.

2025-03-20 08:39 UTC, Majkl-J commented
This is stuck in stale hell

2025-03-20 08:39 UTC, closed without merging