[SEMI-MODULAR] Preferences Glowup!
Bubberstation/Bubberstation pull request #2442
Opened 2024-11-16 00:20 UTC by RimiNosha

## About The Pull Request

This PR most importantly: Fucking obliterates the old mutant preference code from orbit.

I've replaced/extended it with my own system that's neatly tucked into it's own module for easy finding, and I also made it a bunch of smaller files instead of a megafuck huge gigafile. Man, why do coders never learn?

Oh, and I also made a unit test for everything I added.

I can atomize this if really wanted. I just dropped this all in one PR cause I got carried away.

### Now onto the stuff players will like!

- ~2/3rds of the mutant choice features (read: tails, snouts, etc) have been converted to icon pickers!
- The icons in said icon pickers now fill the ENTIRE 48x48 box instead of just 32x32 in the center!
- Supplemental features (colours and emissives) now display fully inside icon picker menus!
- The icon picker menu has been made a little bigger so it doesn't feel so cramped.
- The jobs preference menu got shuffled around to remove the need to scroll.
- Species no longer applies when you click on it, instead you have to press apply for it to mess with your character now.
- Oh, and the character preview now resizes depending on what it *estimates* how big your character is, so hopefully fuckhuge folk no longer have half their character cut off now.
  - This is not exact, but be glad your fuckhuge characters display at all now.
- Fixes the main prefs page being scrollable.

## Why It's Good For The Game

- Icons. Need I say more?
- My changes to the feature picker now make it objectively the best way to display visual choices for characters full stop.
- Colors and emissives being grouped directly with their relevant pref makes the prefs list much, much smaller for complex characters.
- Big characters not scaling off the screen is good.
- Not having to scroll in jobs prefs is also good.

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

No taur
![image](https://github.com/user-attachments/assets/e25be983-386f-4035-a97f-9aad572ee6f2)

Taur
![image](https://github.com/user-attachments/assets/ee5a14b1-045d-46a5-a6d6-69867f7f136c)

Fuckhuge (Oversized is exactly 2x.. so it doesn't really show well.)
![image](https://github.com/user-attachments/assets/e469d079-2f24-4f69-a9bd-3c39df36d541)

New hair menu
![image](https://github.com/user-attachments/assets/8d00d931-f862-46cf-84d4-4ef851099b15)

New jobs
![image](https://github.com/user-attachments/assets/14112d4d-d19f-4a4f-a82f-09e6e8cc0588)

Look at me, I can look at a race and not instantly have my race changed!
![image](https://github.com/user-attachments/assets/37702701-facd-4c74-a1a9-ea6e087e835d)

</details>

## Caveats

- **I've not done every mutant part. This is to somewhat preserve my sanity, and I may return to them later down the line.**
  - It wouldn't be hard for someone else to do it, though. I already did 95% of the legwork.
- Absolutely fucking nothing teshari related previews properly. Goddamn chickens.
- Some vox stuff doesn't display properly either, also a chicken problem.
- Some oversized parts don't preview properly, but honestly that's not a me problem.
- Some ears are invisible in the previews, but they're fine. Still trying to figure out why this is.
- Taur previews are somewhat blurry due to the aspect ratio I chose. I might do a second pass later, but it's a hell of a lot better than no icons.

## Changelog

:cl:
qol: A fair few mutant parts got proper feature pickers now!
qol: Feature pickers now have ALL relevant prefs inside, not just color.
qol: Made it so the preview for characters now scales with your character's size.
fix: Fixed a couple of visual issues in the preferences UI.
/:cl:

2024-11-16 00:23 UTC, RimiNosha commented
None of the savekeys changed though, so common sense says this **shouldn't** be a problem, BUUUT I don't have a save to check against, so I wouldn't TM this until someone can load up their existing character and ensure I didn't accidentally break something.

2024-11-16 00:47 UTC, ReturnToZender commented
This already looks really cool. There's some looks issues with TGUI that are hitting linters, and if you could hopefully get some of those mutant parts to show correctly... that'd be awesome. Great work so far!

2024-11-16 15:32 UTC, RimiNosha commented
Fuck linters.

2024-11-16 15:40 UTC, RimiNosha commented
At least the unit tests are working properly.

2024-11-16 16:16 UTC, RimiNosha commented
Yeah, I think the linter is pulling the schema jsons from master, so you guys *should* be able to ignore the error about the include.

2024-11-16 19:00 UTC, ReturnToZender commented
Only one more little error!

2024-11-16 19:02 UTC, RimiNosha commented
Oh no, it's so much more worse than that

2024-11-16 19:29 UTC, RimiNosha commented
![image](https://github.com/user-attachments/assets/d158fea7-3307-4401-b393-cc10c845863b)
*scream

2024-11-16 20:03 UTC, RimiNosha commented
The worst part is this fixes ears, synth parts, and literally nothing else.

2024-11-22 18:10 UTC, RimiNosha commented
Afaik, this is ready for re-review. Taking a new set of testing captures cause some of the sprites display differently now.

2024-11-22 18:54 UTC, RimiNosha commented
Nevermind, something else broke that I'm now trying to figure out.

2024-11-27 03:48 UTC, nevimer commented
Think this is ready for a testmerge?

2024-11-27 08:08 UTC, RimiNosha commented
No, mismatched parts stopped working properly and I'm trying to figure out why.

2024-11-27 17:00 UTC, RimiNosha commented
Found out why, I accidentally snowflaked visible and species application checks. Woops.

2024-11-27 18:21 UTC, RimiNosha commented
![image](https://github.com/user-attachments/assets/2e7aa9f7-6eb6-430e-a99c-006e42925b28)

New tesh previews, they just don't provide a human icon now. I'll add a basic tesh base icon in a follow up PR.

2024-11-30 21:22 UTC, ReturnToZender commented
How's this coming along? Gonna spin it up locally and try it :)

2024-11-30 22:03 UTC, RimiNosha commented
The PR itself is finished.

2024-11-30 22:04 UTC, RimiNosha commented
I have follow up PRs planned, but I need this merged first, and I'm not about to dump another bunch of changes on top of this.

2024-12-06 15:13 UTC, Majkl-J commented
Ill get to this in the upcoming days

2024-12-11 11:21 UTC, Majkl-J commented
Also, does this resolve https://github.com/Bubberstation/Bubberstation/issues/1975 ?

2024-12-11 14:36 UTC, RimiNosha commented
Yes

2024-12-12 00:06 UTC, Arturlang requested changes

2024-12-12 00:06 UTC, Arturlang commented on tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
> +                randomizations={new Object() as Record<string, RandomSetting>}
Why give randomizations a empty object? If you want to not do any randomization deal with making it not a required variable

2024-12-12 01:24 UTC, Arturlang commented on tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
> +                  const supplementalsRecord: Record<string, unknown> =
if you cant get it to be valid without it, remove the : typing as having both is unnecesary

2024-12-13 19:08 UTC, Arturlang commented on tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
> +                    new Object() as Record<string, unknown>;
No point to setting type twice with : type and as type at the same time

2025-01-02 17:23 UTC, Majkl-J requested changes
Otherwise I heard this runs fine, and changes no pref keys, so we can probably give this a test run, sorry for the wait

2025-01-02 17:23 UTC, Majkl-J commented on code/modules/unit_tests/~bubber/ensure_pref_sanity.dm
> +			emissive_checks(preference, supplementals_failed)
Pretty sure this can be an else if since only one can pass at any given time
```suggestion
		if (istype(preference, /datum/preference/choiced/mutant))
			mutant_checks(preference, supplementals_failed)

		else if (istype(preference, /datum/preference/mutant_color))
			color_checks(preference, supplementals_failed)

		else if (istype(preference, /datum/preference/emissive_toggle))
			emissive_checks(preference, supplementals_failed)
```

2025-01-02 17:23 UTC, Majkl-J commented on modular_zubbers/code/modules/rimiprefs/code/helpers.dm
> +	return new_color
This is utterly cursed, do the colors we use this on pass through rgb2num? 
If so is it possible to work with the color after it's made into the color matrix which would make this easier and cheaper?

(Sorry for not checking this myself)

2025-01-09 16:26 UTC, RimiNosha commented on modular_zubbers/code/modules/rimiprefs/code/helpers.dm
> +	return new_color
New darken method done, and looks pretty close to the old system, so there we go.

![image](https://github.com/user-attachments/assets/f77581fb-3a93-41a4-a421-bffcdf0896b8)

2025-01-09 17:33 UTC, ReturnToZender commented
I'm so fucking stoked for this

2025-01-14 00:46 UTC, ReturnToZender commented
if I enable mismatched parts, it will show parts that physically cannot go on me, like IPC screens and chassis. Only issue with that is that they don't do anything.

2025-01-14 00:47 UTC, ReturnToZender commented
Previews don't show with the selected colors I have (such as with snouts and my tail), but do show otherwise.

2025-01-14 00:48 UTC, ReturnToZender commented
Wings do not show a preview on the side when enabled, only feature that doesn't

2025-01-14 00:49 UTC, ReturnToZender commented
Preview area still seems to cut off, I remember asking you to atomize that change but since this is getting testmerged first, we can include it

2025-01-14 01:02 UTC, RimiNosha commented
> Previews don't show with the selected colors I have (such as with snouts and my tail), but do show in the preview. Just brown.

Physically impossible to do without insane overhead.

> Wings do not show a preview on the side when enabled, only feature that doesn't

Please read the PR body, I say that not every feature uses the new system, and I plan of fixing that up in later PRs.

> Preview area still seems to cut off, I remember asking you to atomize that change but since this is getting testmerged first, we can include it

I can adjust the sizes more if needed, but be aware that there's no perfect solution to this unless you like spamming the server with laggy `getflaticon` calls.

2025-01-14 02:19 UTC, ReturnToZender commented on modular_zubbers/code/modules/rimiprefs/code/mutant_emissive.dm
> +	return list(sanitize_integer(input_bools[1]), sanitize_integer(input_bools[2]), sanitize_integer(input_bools[3]))
Runtimes repeatedly with "cannot read from list"

[19:44:37] Runtime in modular_zubbers/code/modules/rimiprefs/code/mutant_emissive.dm, line 10: cannot read from list
proc name: deserialize (/datum/preference/emissive_toggle/deserialize)
src: /datum/preference/emissive_tog... (/datum/preference/emissive_toggle/pod_hair_emissive)
call stack:
/datum/preference/emissive_tog... (/datum/preference/emissive_toggle/pod_hair_emissive): deserialize(0, /datum/preferences (/datum/preferences))
/datum/preference/emissive_tog... (/datum/preference/emissive_toggle/pod_hair_emissive): read(/list (/list), /datum/preferences (/datum/preferences))
/datum/preferences (/datum/preferences): read preference(/datum/preference/emissive_tog... (/datum/preference/emissive_toggle/pod_hair_emissive))
/datum/preferences (/datum/preferences): load character(4)
/datum/preferences (/datum/preferences): New(TeckTonic (/client))
TeckTonic (/client): New(null)
TeckTonic (/client): New()

2025-01-14 02:23 UTC, ReturnToZender commented
Can't figure out what the error specifically is due to TGUI-dev not working, but selecting a new character causes the character creator to permanently get stuck on an error. Looks like this
![image](https://github.com/user-attachments/assets/7f97d155-6848-4489-a879-f12c83d558f0)

2025-01-14 02:23 UTC, RimiNosha commented on modular_zubbers/code/modules/rimiprefs/code/mutant_emissive.dm
> +	return list(sanitize_integer(input_bools[1]), sanitize_integer(input_bools[2]), sanitize_integer(input_bools[3]))
Send an affected save please.

2025-01-14 02:32 UTC, ReturnToZender commented on modular_zubbers/code/modules/rimiprefs/code/mutant_emissive.dm
> +	return list(sanitize_integer(input_bools[1]), sanitize_integer(input_bools[2]), sanitize_integer(input_bools[3]))
Done!

2025-03-30 17:49 UTC, closed without merging