Prevents using sign language in frenzy
Bubberstation/Bubberstation pull request #2453
Opened 2024-11-16 23:36 UTC by Arturlang

## About The Pull Request
In terms of flavour of frenzy, you're supposed to not quite be sane enough to do much of anything besides try to get blood, or maybe act monstrously, that's why you are mute and deaf, but you could bypass via sign language, so this fixes that.

## Why It's Good For The Game
It's wierd when the frenzying vampire literally starving and frenzying can speak, even though they should be really animal-like at that point

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
fix: You can no longer use sign language while frenzying
/:cl:

2024-11-17 01:18 UTC, Arturlang commented
need to fix some mistakes sorry

2024-11-17 18:37 UTC, Arturlang commented
Done, fixed

2024-11-18 19:31 UTC, lessthnthree requested changes
Need to add TRAIT_SIGN_LANGUAGE_BLOCKED to code/_globalvars/traits/_traits.dm then you're good to go.

2024-11-18 23:35 UTC, lessthnthree approved these changes

2024-11-19 00:52 UTC, merged