[LORE UPDATE] Reflavors Caligram clothing to Blacktide
Bubberstation/Bubberstation pull request #2490
Opened 2024-11-19 07:37 UTC by Boviro

## About The Pull Request

Edits the descriptions and names of the Caligram and Ixian clothing items to be brought into new Bubberstation lore, replacing the Caligram Fleet with Blacktide, a mercenary company operating off of Dustworld.
Note: This PR was requested by @goblins4lyfe on the Discord. I am doing this for a steam game
Note 2: This PR reuses donor items that were added on Skyrat. I nor the lore writers take responsibility for the sprites or items that were created for the Caligram faction, and are just reflavoring them for use with the Bubberstation lore.

## Why It's Good For The Game

Brings items grandfathered from Skyrat into line with Bubberstation lore.

## Proof Of Testing

No functional code was changed, purely flavor text. Also, it builds, so it's fine.

## Changelog

:cl:
add: reflavors Caligram gear to Blacktide
/:cl:

2024-11-19 07:44 UTC, projectkepler-ru requested changes
Wait a bit I am asking zydra and bombay about it

2024-11-19 07:45 UTC, Boviro commented
Entirely fair, I'm not... 100% sure on all of this either and I would like the mod and coder staff to sign off on it before it gets merged.

2024-11-19 07:47 UTC, Boviro commented
Also understandable. If it would be better to suffer some loadout bloat to add Blacktide variants of the Caligra stuff I can do that as well.

2024-11-19 07:48 UTC, projectkepler-ru commented
Naw just wait abit, the caligras arent inactive we are just discussing the lore atm. I am waiting on the verdict. at latest it'll be friday but it shouldn't take that long

2024-11-19 08:15 UTC, Boviro commented
Converted to draft via executive decision from the admin team to not go through with it. A wholly unique new set of sprites may be added for the Blacktide stuff, so I will leave this a draft until I get a concrete plan of where it will proceed.

2024-11-19 15:42 UTC, StrangeWeirdKitten commented
I'll take over this PR

2024-11-21 00:04 UTC, Boviro commented
Reflavors the caligram stuff to be a generic Blacktide, as opposed to the new proposal from harvey for the Molerats mercenary group, since I was asked to keep the change name. More importantly, it adds a new set of alt designs for the Caligram-now-Blacktide clothing, that being a deep blue color
![image](https://github.com/user-attachments/assets/3b7907b6-8766-4853-8505-18ee59e699e4)

2024-12-02 16:10 UTC, Majkl-J commented on modular_skyrat/master_files/code/modules/loadout/categories/donator_personal.dm
>  //	ckeywhitelist = list("farsightednightlight", "raxraus", "1ceres", "marcoalbaredaa", "itzshift_yt", "drifter7371", "AvianAviator", "Katty Kat", "Investigator77", "Dalao Azure", "Socialistion", "Chi
Feel free to remove the commented out whitelist it isn't coming back

2024-12-05 13:20 UTC, Majkl-J approved these changes
I have concluded that the comments can stay and whatnot

2024-12-05 13:21 UTC, merged