Grow strong and big!
Bubberstation/Bubberstation pull request #2493
Opened 2024-11-19 08:59 UTC by JagOfTroy

## About The Pull Request

There was originally code written in by Skyrat that would show a visual change in your character as your 'Fitness'(now Athletics) level increased. With the changes to Athletics, you will see your size increase as you grow stronger.

## Why It's Good For The Game

Visually and flavor-wise, this just adds more immersion to the game, especially for those that like playing the stronger, muscular characters. 

## Proof Of Testing

![Screenshot 2024-11-19 024727](https://github.com/user-attachments/assets/43a480c6-7fa2-459f-88b9-bc9a72138e4e)
![Screenshot 2024-11-19 024843](https://github.com/user-attachments/assets/467f6ed2-96b5-43b8-a216-8887f5e449e1)

## Changelog

:cl: Sparex
add: Added size_boost mechanics to the Athletics skill. Now you will visually grow stronger as does your power level!
/:cl:

2024-11-19 09:01 UTC, JagOfTroy commented
You won't actually grow THAT large as shown in the image, it was a test to make sure the size difference would be noticeable but is beyond what legendary would give someone.

2024-11-19 09:03 UTC, projectkepler-ru approved these changes

2024-11-19 09:09 UTC, Majkl-J requested changes
Also needs whitespace fixed you're using spaces instead of tabs

2024-11-19 09:09 UTC, Majkl-J commented on modular_zubbers/code/datums/skills/athletics.dm
> +	var/static/size_boost = list(0, 1/16, 1/8, 3/16, 2/8, 3/8, 4/8)
No need to copypaste all the stuff you aren't changing
```suggestion
	/// How much bigger your mob becomes per level (these effects don't stack together)
	var/static/size_boost = list(0, 1/16, 1/8, 3/16, 2/8, 3/8, 4/8)
```

2024-11-19 09:09 UTC, Majkl-J commented on modular_zubbers/code/datums/skills/athletics.dm
> +
ditto
```suggestion

```

2024-11-19 09:09 UTC, Majkl-J commented on modular_zubbers/code/datums/skills/athletics.dm
> +/datum/skill/athletics/level_gained(datum/mind/mind, new_level, old_level, silent)
ditto
```suggestion
/datum/skill/athletics/level_gained(datum/mind/mind, new_level, old_level, silent)
```

2024-11-19 09:09 UTC, Majkl-J commented on modular_zubbers/code/datums/skills/athletics.dm
> +        ADD_TRAIT(mind, TRAIT_EXAMINE_FITNESS, SKILL_TRAIT)
ditto
```suggestion
```

2024-11-19 09:09 UTC, Majkl-J commented on modular_zubbers/code/datums/skills/athletics.dm
> +        REMOVE_TRAIT(mind, TRAIT_EXAMINE_FITNESS, SKILL_TRAIT)
ditto
```suggestion
    . = ..()
```

2024-11-19 09:16 UTC, JagOfTroy commented
Hmmm, had no idea that VSC would still recognize those extra spaces as tabs as well. 
Will have to keep an eye out for that in the future.

2024-11-19 09:22 UTC, IgiariValkyr commented
Would recommend some kind of toggle for it for people who don't want to scale up when they bulk up, especially for those who are large enough as is.

2024-11-19 09:46 UTC, JagOfTroy commented
> Would recommend some kind of toggle for it for people who don't want to scale up when they bulk up, especially for those who are large enough as is.

Working on adding a toggle atm.

2024-11-19 19:30 UTC, MajManatee commented
Does this allow already tall people just to become colossal?

2024-11-19 19:38 UTC, JagOfTroy commented
> Does this allow already tall people just to become colossal?

It would, yes if people choose to abuse it and they most likely will because it uses RESIZE_DEFAULT_SIZE and the DEFAULT_SIZE is determined by the player in the character menu.

This is a work in progress, I'm still figuring out the @toggle and pending how to add it as as verb so people can turn it off.

There should be a way to place limitations on exactly how big people can grow which is something I'll look into as well.

Thanks for everyone's feedback.

2024-11-20 23:23 UTC, JagOfTroy commented
Still working on this, have to learn how to make and connect front-end/back-end verb as a toggle in the menu.
Just finished exams this week so my brain is fried atm.

2024-12-13 13:23 UTC, Cyprex commented
I don't like this, scaled sprites look bad, and you don't exactly grow an inch taller by working out.

2024-12-13 13:27 UTC, Cyprex commented
We talked about this internally and yeah, we don't like this for the aforementioned reasons.

2024-12-13 13:27 UTC, closed without merging

2024-12-13 15:53 UTC, JagOfTroy commented
Yea, I've been absent due to class and just finished my finals so I can finally get back to looking into DM code again.

If not for the scaling, I would still like there to be something significant about maxing out fitness still. Where would the appropriate place be to discuss those ideas?