Modular Suit Wearing! Most outerwear items can now be worn on your neck!
Bubberstation/Bubberstation pull request #2521
Opened 2024-11-22 19:17 UTC by MajManatee

## About The Pull Request

A Port of https://github.com/NovaSector/NovaSector/pull/4481

Essentially, lets most suit items like jackets and such be Alt+clicked while in your hand to remove any protection or bonuses, and allow them to be worn over the neck instead! 

## Why It's Good For The Game
Its drip or drown in this world
and brother
I'm flying

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>
As usual, will be done soon...
</details>

## Changelog

:cl:
add: Most (tm) suit slot items can be alt clicked and worn around the neck!
balance: Fixes snowflake armor with two items that were stacking for protection
/:cl:

2024-11-23 11:09 UTC, ReturnToZender commented
Really appreciate the work you're doing porting the good stuff here, Manatee. Keep it up!

2024-12-05 13:18 UTC, Majkl-J requested changes

2024-12-05 13:18 UTC, Majkl-J commented on modular_zubbers/code/modules/clothing/neck_wearing.dm
> +	. = ..()
```suggestion
#undef PREV_SLOT_FLAGS
#undef PREV_COLD_PROTECTION
#undef PREV_HEAT_PROTECTION
#undef PREV_SLOWDOWN
#undef PREV_ARMOR_DATUM

/obj/item/clothing/suit/add_context(atom/source, list/context, obj/item/held_item, mob/living/user)
	. = ..()
```

2024-12-05 13:18 UTC, Majkl-J commented on modular_zubbers/code/modules/clothing/neck_wearing.dm
> +		functional_suit_values = list(
This is never nulled out when switching back

2024-12-05 13:18 UTC, Majkl-J commented on modular_zubbers/code/modules/clothing/neck_wearing.dm
> +	/// A temp list to restore the intitial functional values (for armor, cold protection, etc) to the state they were in prior to using the functional toggle
```suggestion
	/// When set to TRUE, this particular suit is not able to use the functional toggle
	var/only_functional
	/// temp list to restore the intitial functional values (for armor, cold protection, etc) to the state they were in prior to using the functional toggle
```

2024-12-05 13:18 UTC, Majkl-J commented on modular_zubbers/code/modules/clothing/neck_wearing.dm
> +	if(!(flags_1 & HAS_CONTEXTUAL_SCREENTIPS_1))
Needless extra whitespace
```suggestion
/obj/item/clothing/suit/Initialize(mapload)
	. = ..()
	if(!(flags_1 & HAS_CONTEXTUAL_SCREENTIPS_1))
```

2024-12-05 13:18 UTC, Majkl-J commented on modular_zubbers/code/modules/clothing/neck_wearing.dm
> +	if(!only_functional)
Ditto
```suggestion
/obj/item/clothing/suit/examine(mob/user)
	. = ..()
	if(!only_functional)
```

2024-12-05 13:18 UTC, Majkl-J commented on modular_zubbers/code/modules/clothing/neck_wearing.dm
> +
ditto
```suggestion
```

2024-12-05 14:41 UTC, OrbisAnima commented
Mind if f you put me as coauthor? also, be sure to check your code for stuff that would still be in effect while used like this, thats what the only functional tag is about!

2024-12-05 18:22 UTC, Majkl-J commented
> Mind if f you put me as coauthor?

Done

2024-12-05 21:32 UTC, OrbisAnima commented
Wouldn't it be better to put in the changelog you need to ctrl + shift +  click for the interaction?

2024-12-29 01:26 UTC, NanoCats commented
Tragically unusable for me, the collar stays ON during sex.

2025-01-10 16:53 UTC, MajManatee commented
please my PR its very sick, the only cure is merging

2025-01-15 21:49 UTC, Arturlang requested changes
![image](https://github.com/user-attachments/assets/baf3d5bd-2dcc-413f-9de5-d54b8a6ceadb)
change the span to be consistent please, and only show it on suits that are actually valid for this, as modsuits are not, and other things you cannot drop

2025-01-16 04:23 UTC, MajManatee commented
> ![image](https://private-user-images.githubusercontent.com/24881678/403595957-baf3d5bd-2dcc-413f-9de5-d54b8a6ceadb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMDE2ODcsIm5iZiI6MTczNzAwMTM4NywicGF0aCI6Ii8yNDg4MTY3OC80MDM1OTU5NTctYmFmM2Q1YmQtMmRjYy00MTNmLTlkZTUtZDU0YjhhNmNlYWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDA0MjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMDJjY2E3MDViMzJlZWNkMjMzNTIyNTEzYzZhMzM3ODFiNzg2ZWUzNTUzYzRhODRmMmM0ZTBjZmE4MDc3ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jkuGXhaeJ6hUaX9fdfQ8PqoLvLMh7LWEST2UyCo2ch8) change the span to be consistent please, and only show it on suits that are actually valid for this, as modsuits are not, and other things you cannot drop. Also could make clothes instantly equippable to neck slots and disable their stats in that case, then, not sure

What do you mean "be more consistent"? I have added the modsuit chestpiece to the excluded list, and it shouldnt show the prompt anymore.

2025-01-16 11:06 UTC, Arturlang commented
@MajManatee 
![image](https://github.com/user-attachments/assets/68f02e30-5e9c-41fd-9ba4-4bf2b1d79ce7)
most things that give you a extra different description info use span_notice, while you're using span_info.
Also you don't need to filter it by types, just check if they have the TRAIT_NODROP to decide if it's possible to toggle it into neck wearing mode

2025-01-16 11:11 UTC, Arturlang commented on modular_zubbers/code/modules/clothing/neck_wearing.dm
> +		slot_flags = ITEM_SLOT_NECK
Not a requirement, but slot_flags is a bitmask meaning it supports multiple flags, thus you could simply make all clothing ITEM_SLOT_NECK | ITEM_SLOT_OCLOTHING, and check on equipped(mob/user, slot, initial) if it's the neck, and make it nonfunctional then, circumventing the need to toggle it

2025-01-16 18:47 UTC, MajManatee commented
bold of you to assume I know anything that's going on in this code, or how it works.

2025-01-16 19:30 UTC, MajManatee commented
changes made to check for no_drop and changed to span_notice

2025-01-17 09:02 UTC, Majkl-J requested changes

2025-01-17 09:02 UTC, Majkl-J commented on modular_zubbers/code/modules/clothing/neck_wearing.dm
> +		user.visible_message(span_notice("[user] adjusts [user.p_their()] [src] for functional use."), span_notice("You adjust your [src] for functional use."))
leave not a list behind

```suggestion
		slowdown = functional_suit_values[PREV_SLOWDOWN]
		set_armor(functional_suit_values[PREV_ARMOR_DATUM])
		functional_suit_values = null
		user.visible_message(span_notice("[user] adjusts [user.p_their()] [src] for functional use."), span_notice("You adjust your [src] for functional use."))
```

2025-01-18 00:00 UTC, Majkl-J approved these changes
Maj said he'd turn me into lizard wine if I didnt review it finally. And you know what, I think this is good enough

2025-01-18 00:00 UTC, merged