Gives lone infiltrator his micro-bomb back.
Bubberstation/Bubberstation pull request #2527
Opened 2024-11-23 13:47 UTC by Adrian16199

## About The Pull Request
Lone infiltrator gets their promised micro-bomb, yey.

## Why It's Good For The Game
They used to have it, was removed by skyrat. Either this or the paper should be removed.
My reasoning for why bring the micro-bomb instead of the paper being evaporated.
Most of the time, your actions get loud or you are taken as enemy of the corporation, causin you to be killed on sight or perhaps even apprehended into perma which will take only 5 minutes before getting executed due to the EOTC being applied.
Even if you would want to roleplay after being kidnapped, the chance is only there if they will actualy try to take you non-lethally so you shouldnt die a horrible death. 
You might say, why this then if you are going to die anyways? Well atleast this wont make you a lootbag just like the paper says and explains. You are there to infiltrate, if you fail then you are not worth loosing all that equipment to the enemy corporation, ey?

## Proof Of Testing
![image](https://github.com/user-attachments/assets/fa5b4ace-3cd2-4838-b21c-ea499221ffb3)
![image](https://github.com/user-attachments/assets/e6db508c-96a2-45c5-af04-6fca94d0df02)
![image](https://github.com/user-attachments/assets/b2816fbf-abfe-4a31-a41d-13dec83f1027)

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
balance: Lone infiltrator has been given back their micro-bomb as the syndicate intended. Budget cuts happend but we good now.
/:cl:

2024-11-24 03:03 UTC, nevimer commented
eh, they're not really a nuclear operative...

2024-11-24 12:16 UTC, Adrian16199 commented
Why does everyone _say_ that

2024-11-25 20:26 UTC, Swiftfeather approved these changes
I agree wholeheartedly with this and generally refuse to play lone op because it doesn't have this.

2024-11-26 10:04 UTC, Adrian16199 commented
> Can you come up with something a bit more original?

...
okay...
How about we make it optional.
You choose if you want it implanted or not and an implanter just spawns in your modsuit.
Does that sound more *Original*

2024-11-27 00:27 UTC, Doom-external commented
Could make it the tactical deniability implant so it doesn't damage the station.

2024-12-09 08:56 UTC, StrangeWeirdKitten commented
I'm just going to make a vote for the maintainers to decide.

2024-12-09 11:07 UTC, Adrian16199 commented
Thank you

2024-12-09 17:06 UTC, StrangeWeirdKitten requested changes
Just spawn the implanter itself in their bag or on their person then I'll merge it.

2024-12-10 11:13 UTC, Adrian16199 commented
![image](https://github.com/user-attachments/assets/e1c41a3f-c76b-4a1d-9008-6f202466aaf4)
Done

2024-12-14 04:19 UTC, StrangeWeirdKitten requested changes

2024-12-14 04:19 UTC, StrangeWeirdKitten commented on modular_skyrat/modules/Midroundtraitor/code/event.dm
> +		/obj/item/knife/combat/survival,
```suggestion
		/obj/item/knife/combat/survival=1,\
```

2024-12-16 22:27 UTC, merged