Updates access levels to make sense
Bubberstation/Bubberstation pull request #253
Opened 2023-06-06 15:59 UTC by Majkl-J

## About The Pull Request

Gives doctors coroner access on lowpop.
Also gives security medics back medical access.

## Changelog

:cl:
qol: Doctor access levels now make sense
/:cl:

2023-06-06 20:40 UTC, nevimer requested changes
Sure. Looks good. Just comment this line with a bubber addition

2023-06-06 20:40 UTC, nevimer commented on code/datums/id_trim/jobs.dm
> +		ACCESS_MORGUE_SECURE,
one comment

2023-06-10 02:00 UTC, nevimer commented
This will go poof next upstream update, but, we can have nice things until then.

2023-06-10 02:00 UTC, merged

2023-06-10 09:07 UTC, Majkl-J commented
> This will go poof next upstream update, but, we can have nice things until then.

Ill just PR it again.