Add permanent limp quirk
Bubberstation/Bubberstation pull request #2560
Opened 2024-11-26 10:37 UTC by TheGreatKitsune

## About The Pull Request

Adds a permanent limp quirk, negative with a cost of -1. Allows adding a minor, moderate, or major limp to a characters leg that cannot be treated short of limb replacement.

## Why It's Good For The Game

Requested by a player. Allows for players to have a character that limps naturally without having to dislocate a leg in round.

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

![perm_limp_1](https://github.com/user-attachments/assets/04293b1d-7879-4875-8f28-f6421c402707)
![perm_limp_2](https://github.com/user-attachments/assets/da3f34b3-2f5b-496c-b502-be72222fd3ca)
![perm_limp_3](https://github.com/user-attachments/assets/853f5fb1-2f75-48ac-8a53-3743403dc10f)

</details>

## Changelog

:cl: Cerami
add: Adds a new negative quirk: permanent limp
/:cl:

2024-11-26 20:03 UTC, ReturnToZender commented
I think this would at least be a -2 trait, considering it severely impairs your movement

2024-11-26 20:45 UTC, YakumoChen commented
This sounds like something upstream tg may like as an aside

2024-11-27 00:23 UTC, Doom-external commented
Dr. Gregory House

2024-11-27 03:13 UTC, TheGreatKitsune commented
Admittedly I don't have much idea what sort of point value would be good. I might also look into how to prevent stacking this quirk with paraplegic perhaps as well

2024-11-27 03:22 UTC, ReturnToZender commented
> Admittedly I don't have much idea what sort of point value would be good. I might also look into how to prevent stacking this quirk with paraplegic perhaps as well

There's a glob list of mutually exclusive quirks that you can add this to

2024-11-27 11:47 UTC, Arturlang requested changes

2024-11-27 11:47 UTC, Arturlang commented on code/datums/wounds/permanent_limp.dm
> +/datum/wound_pregen_data/perm_limp/right/moderate
Put empty spaces before type definitions

2024-11-28 09:58 UTC, merged