[MODULAR] Holomaps!
Bubberstation/Bubberstation pull request #2563
Opened 2024-11-26 19:16 UTC by RimiNosha

## About The Pull Request

Basically a port of a port of a port of a port(?). The direct PR this is based off of is https://github.com/Artea-Station/Artea-Station-Server/pull/274

Notable missing features from the above:
- The PDA/Modcomp app, it runs like ASS on actual maps that aren't a tiny ass ship, as I discovered the hard way.

Total featurelist is:
- These are constructable.
  - The normal holomap is researched with construction, and the engineering one with holographics.
- Engineering holomaps show active fire and atmos alarms.
- Ladders and stairs have icons.
- Click to open.
- Right click or walk away to close.
- Click on any non-department icons in the legend to hide them.
- Multitool to configure what Z is shown. Current valid Zs: All station Zs, and lavaland, though only the base will show.
- EMPs cause these to break very easily.
- Shows station areas with colours.
- Can be hovered over to show the area name.
- The images these use generate on init! No extra work on maptainers is needed!
  - This takes on average ~1.2s to do on my machine, which is plenty tolerable.

## Why It's Good For The Game

It's nice being able to see where you are in the station, and what the station looks like, yeah?

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

https://github.com/user-attachments/assets/94702243-0dc9-4eaf-b4bc-8d70e2caa3d3

(I've since fixed the frames using the wrong state)

</details>

## Changelog

:cl:
add: Holomaps! See where you are, see what's around you!
add: Engineering holomaps! See where that FUCKING FIRE ALARM is!
/:cl:

2024-11-26 19:35 UTC, RimiNosha commented
Drafted pending some changes I need to make.

2024-11-26 20:01 UTC, ReturnToZender commented
ooh let me look at this

2024-11-28 03:23 UTC, lessthnthree commented on modular_zubbers/code/modules/holomaps/holomap.dm
> +		message_admins("\[HOLOMAP] WARNING: Holomap at [x], [y], [z] [ADMIN_FLW(src)] had to set itself up on interact! Something during Initialize went very wrong!")
message_admins doesn't create a log entry, and there's no guarantee any admin is going to see this, nor care, nor know what to do.

2024-11-28 03:24 UTC, lessthnthree approved these changes

2024-11-28 07:13 UTC, Majkl-J requested changes

2024-11-28 07:13 UTC, Majkl-J commented on modular_zubbers/code/modules/holomaps/holomap.dm
> +		message_admins("\[HOLOMAP] WARNING: Holomap at [x], [y], [z] [ADMIN_FLW(src)] had to set itself up on interact! Something during Initialize went very wrong!")
This should stack_trace instead

2024-11-30 21:46 UTC, ReturnToZender commented
This looks really cool, but for some reason every time I try to test it, I get an asset transport error and it ruins my cache. No idea why, but I have no idea what these holomaps look like as a result

2024-12-01 00:13 UTC, RimiNosha commented
Weird, that makes no sense. Works on my machine:tm:

2024-12-01 01:40 UTC, ReturnToZender commented
> Weird, that makes no sense. Works on my machine:tm:

I hope so. This looks really cool and like it'd be a game changer for players. With all the maps we have, I need to start putting them on the ss13 webmap, and something like this to go with it would be great.

2025-03-20 08:40 UTC, Majkl-J commented
Staleness label applied.

2025-03-30 17:50 UTC, closed without merging