actually fixes the mapvote
Bubberstation/Bubberstation pull request #2609
Opened 2024-12-02 01:44 UTC by Odairu

## About The Pull Request
I fucked up

## Why It's Good For The Game

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

</details>

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixes mapvote
/:cl:

2024-12-02 01:46 UTC, lessthnthree requested changes

2024-12-02 01:46 UTC, lessthnthree commented on code/datums/votes/map_vote.dm
> +		"DeltaStation",
```suggestion
		"Delta Station",
```

2024-12-02 01:46 UTC, lessthnthree commented on code/datums/votes/map_vote.dm
> +		"IceBox",
```suggestion
		"Ice Box Station",
```

2024-12-02 01:46 UTC, lessthnthree commented on code/datums/votes/map_vote.dm
> +		"TramStation",
```suggestion
		"Tramstation",
```

2024-12-02 02:00 UTC, lessthnthree approved these changes

2024-12-04 13:41 UTC, Shadow-Quill commented
does this fix https://github.com/Bubberstation/Bubberstation/issues/2605, or is that a separate issue?

2024-12-04 17:58 UTC, lessthnthree commented
Yes it does

2024-12-05 01:28 UTC, merged