Orefruit harvesting producing sheets
Bubberstation/Bubberstation pull request #2800
Opened 2024-12-28 14:37 UTC by xXPawnStarrXx

## About The Pull Request
This PR makes it so that orefruit when harvested produces cores as sheets, instead of a grown item. I've added stack sprites too, so you can get more of a visual update on stacks. This doesn't affect the tedium of peeling them, you still have to do that by hand, this just makes it so that the resulting cores can be loaded into protolathes, machines and silos.

## Why It's Good For The Game

It was tedious for many to produce a recycler layout or autolathe to actually make use of the ores.

## Proof Of Testing

<details>
<summary>Screenshots/Videos</summary>

![image](https://github.com/user-attachments/assets/81eb40fe-1ad5-43c3-87dc-e94ab5ce042a)

![image](https://github.com/user-attachments/assets/bc88f7bd-5481-4595-9226-f3ca33162021)

</details>

## Changelog

:cl:
qol: made orefruits produce sheets as cores, instead of lame objects, letting them be inserted into a silo.
/:cl:

2024-12-29 21:23 UTC, YakumoChen commented
Why not make the fruit produce ores instead? Fruit magically producing flat sheets of material is a little too nonsensical.

2024-12-29 23:55 UTC, IgiariValkyr commented
> Why not make the fruit produce ores instead (creates lots of alternative and automated ways to process them, rewards using an ORM)? Fruit magically producing flat sheets of material is a little too nonsensical.

I think the point is the cores of the fruits are worth 0.2 sheets, so you need 5 fruits to make a single sheet. It's slower, but farmable to a grand scale.

2024-12-30 02:08 UTC, YakumoChen commented
> > Why not make the fruit produce ores instead (creates lots of alternative and automated ways to process them, rewards using an ORM)? Fruit magically producing flat sheets of material is a little too nonsensical.
> 
> I think the point is the cores of the fruits are worth 0.2 sheets, so you need 5 fruits to make a single sheet. It's slower, but farmable to a grand scale.

Would still be able to do that with an ore, essentially through the same process this does with sheets. It makes sense to require the fruit to need refined first.

2024-12-30 17:24 UTC, xXPawnStarrXx commented
> Why not make the fruit produce ores instead (creates lots of alternative and automated ways to process them, rewards using an ORM)? Fruit magically producing flat sheets of material is a little too nonsensical.

I wanted it to be more tedious, it's a temporary suppliment to mining, not replacing. I considered ores, but I didn't want someone getting mining points for just growing something.

2024-12-31 03:53 UTC, YakumoChen commented
> > Why not make the fruit produce ores instead (creates lots of alternative and automated ways to process them, rewards using an ORM)? Fruit magically producing flat sheets of material is a little too nonsensical.
> 
> I wanted it to be more tedious, it's a temporary suppliment to mining, not replacing. I considered ores, but I didn't want someone getting mining points for just growing something.

You can already get mining points without mining by doing anthills and other such methods.
I don't see how ores are less tedious than sheets, you can get stacking machines to automate it even better if you wish.

2025-01-01 23:43 UTC, xXPawnStarrXx commented
> You can already get mining points without mining by doing anthills and xenobiology.

That is true, but these produce ores that they do not, more frequently and you can choose the type you plant.

>I don't see how ores are less tedious than sheets, you can get stacking machines to automate it even better if you wish.
It's supposed to be more tedious than ores for balancing.

2025-01-02 09:50 UTC, YakumoChen commented
> It's supposed to be more tedious than ores for balancing.

Missing the point, ores are more tedious than sheets, especially given they _require_ the extra step for processing. Both can be automated via ORM or Stacking Machine respectively.

2025-01-02 21:25 UTC, xXPawnStarrXx commented
> Missing the point, ores are more tedious than sheets, especially given they _require_ the extra step for processing. Both can be automated via ORM or Stacking Machine respectively regardless.

Nah, ores can literally be loaded into silos providing the same amount of materials, but not giving mining points.

2025-01-03 02:48 UTC, YakumoChen commented
> > Missing the point, ores are more tedious than sheets, especially given they _require_ the extra step for processing. Both can be automated via ORM or Stacking Machine respectively regardless.
> 
> Nah, ores can literally be loaded into silos providing the same amount of materials, but not giving mining points.

> Fruit magically producing flat sheets of material is a little too nonsensical.

Regardless, this is my issue with it, but I suppose my complaints might just be much ado about nothing, so whatever

2025-01-04 11:58 UTC, xXPawnStarrXx commented
> Fruit magically producing flat sheets of material is a little too nonsensical.

The ore fruit cores are sprited and conceptually meant to be ores, but they just stack due to their smaller size, they look like this... Mechanically they'll be sheets.

![image](https://github.com/user-attachments/assets/bdcf33a2-0832-4340-a5c8-133da6a88623)

2025-01-10 20:29 UTC, Arturlang requested changes
Integration tests fail due to your code, please fix

2025-01-13 14:16 UTC, xXPawnStarrXx commented
> Integration tests fail due to your code, please fix

I'm pretty sure I have fixed my fucky-wuckies. Should be ready now.

2025-01-14 00:08 UTC, Arturlang approved these changes
indendation stuff is the major issue, please use proper spacing before lists, prefferably also spaces around = and * but that's mostly a style thing

2025-01-14 00:08 UTC, Arturlang commented on modular_zubbers/code/modules/hydroponics/code/grown/rocks.dm
> +    seed = /obj/item/seeds/sandfruit
Indendation fucked here i think

2025-01-14 00:08 UTC, Arturlang commented on modular_zubbers/code/modules/hydroponics/code/grown/rocks.dm
> +	mats_per_unit =list(/datum/material/bananium=SHEET_MATERIAL_AMOUNT*0.2)
spaces please

2025-01-14 00:08 UTC, Arturlang commented on modular_zubbers/code/modules/hydroponics/code/grown/rocks.dm
> +	mats_per_unit =list(/datum/material/runite=SHEET_MATERIAL_AMOUNT*0.2)
ditto

2025-01-14 00:08 UTC, Arturlang commented on modular_zubbers/code/modules/hydroponics/code/grown/rocks.dm
> +	mats_per_unit =list(/datum/material/adamantine=SHEET_MATERIAL_AMOUNT*0.2)
ditto

2025-01-14 00:08 UTC, Arturlang commented on modular_zubbers/code/modules/hydroponics/code/grown/rocks.dm
> +	mats_per_unit =list(/datum/material/titanium=SHEET_MATERIAL_AMOUNT*0.2)
ditto

2025-02-03 22:11 UTC, merged