Organ Spilling Rebalance
Bubberstation/Bubberstation pull request #343
Opened 2023-07-15 03:13 UTC by BurgerLUA

## About The Pull Request

This isn't an organ spill rebalance but rather a bugfix that fixes sexual organs being spilled out on disembowelment. The title exists so that future employers don't look at my github history and see "Fixes anuses, vaginas, penises, testicles spilling out during disembowelment" on my git history.

I did not test this yet because I need to go to bed and I just spent the last 10 minutes fixing my fucked git repo. But it compiles, so it works:tm:.

actually im not even sure if it compiles i did not even bother to compile it

## Changelog

:cl: BurgerBB
fix: Fixes sexual organs being spilled out on disembowelment.
balance: Removes cock checking.
/:cl:

2023-07-15 03:55 UTC, ReturnToZender commented
Bro didn't even compile his code and straight up deleted upstream's code. So incredibly based

2023-07-15 04:18 UTC, nevimer requested changes

2023-07-15 04:18 UTC, nevimer commented on tgstation.dme
> +#include "interface\skin.dmf"
huh

2023-07-15 04:18 UTC, nevimer commented on tgstation.dme
> -#include "modular_skyrat\master_files\code\modules\mob\living\carbon\death.dm"
why, just comment block out this file we arnt getting this as a merge conflict later

2023-07-15 13:23 UTC, BurgerLUA commented on tgstation.dme
> +#include "interface\skin.dmf"
byond did that

2023-07-16 21:09 UTC, BurgerLUA commented
![image](https://github.com/Bubberstation/Bubberstation/assets/8602857/663a40a8-2b30-4523-ac91-32cc49f53b85)

wow it actually works on first compile, but I did the requested changes

2023-07-17 03:29 UTC, merged