(Non-Modular) Blowgun can fire pills into uncovered mouths.
Bubberstation/Bubberstation pull request #347
Opened 2023-07-15 19:55 UTC by DerFlammenwerfer

## About The Pull Request
A request from BurningCold for a gimmicky meme feature allowing blowguns to fire a pill into someone's mouth if it's uncovered. I had to add a new projectile and ammo casing to handle this, and modify the blowgun's code to load that projectile. I tried many ways of using the is_mouth_covered proc, but none of them worked because that proc is BROKEN. I instead coded it to check if you're wearing any kind of facewear or not, or if you're wearing a helmet that covers the face. If you're wearing either one, the pill will not transfer its reagents and be lost, otherwise, you will ingest whatever's in the pill. As a fun little side feature, the pill launched from the blowgun will inherit the sprite of the pill that was loaded into it.

## Changelog

:cl:
add: Added ammo casing and bullet support to handle the new blowgun feature
code: Added a function to the blowfun's loading proc to let it load and fire pills like a spitball
/:cl:

2023-07-16 10:49 UTC, projectkepler-ru commented
@DerFlammenwerfer  how common are blowgun exactly?

2023-07-16 11:15 UTC, DerFlammenwerfer commented
> @DerFlammenwerfer how common are blowgun exactly?

Blowguns aren't exactly common, you need someone to grow bamboo, and the downside of using them is 20 stamina damage and 20 oxygen damage per firing, which is not insignificant.

2023-07-17 03:25 UTC, nevimer commented
make this more modular or document your edits

2023-07-18 01:13 UTC, BurgerLUA requested changes

2023-07-18 01:13 UTC, BurgerLUA commented on code/modules/projectiles/guns/special/syringe_gun.dm
> +	..()
This should be ``. = ..()``

2023-09-13 05:22 UTC, closed without merging

2023-09-13 05:22 UTC, nevimer commented
victim of the great rebase, but this is worth it to remake