The Aerostatic Ace
Bubberstation/Bubberstation pull request #404
Opened 2023-07-30 01:47 UTC by NotMergot

## About The Pull Request

Adds the rest of the aerostatic outfit to the loadout menu. Follows suit with the aerostatic bomber jacket already available wherein the items are separate from the detective versions.

Already tested, should hopefully pass all the tests.

## Why It's Good For The Game

Why go half way with an amazing looking outfit that hardly anyone gets to see as is? Part of it is already in loadouts for everyone to use, no reason not to add the rest.

## Changelog

:cl:
add: Aerostatic Boots loadout item
add: Aerostatic Gloves loadout item
add: Binoclard Lenses loadout item
/:cl:

2023-07-30 08:03 UTC, nevimer commented on modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_shoes.dm
> +datum/loadout_item/shoes/aerostatic_boots
```suggestion
/datum/loadout_item/shoes/aerostatic_boots
```

2023-07-30 19:44 UTC, NotMergot commented on modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_shoes.dm
> +datum/loadout_item/shoes/aerostatic_boots
knew my headass was gonna forget something simple thanks

2023-07-31 00:56 UTC, nevimer requested changes

2023-07-31 00:56 UTC, nevimer commented on tgstation.dme
> +#include "modular_zubbers\code\modules\clothing\outfits\kim.dm"
don't manually edit this file

2023-07-31 00:56 UTC, nevimer commented on modular_zubbers/code/modules/clothing/outfits/kim.dm
> +/obj/item/clothing/glasses/binoclardlenses
underscorethenamesbetweenwords_please

2023-07-31 00:56 UTC, nevimer commented on modular_zubbers/code/modules/clothing/outfits/kim.dm
> +/obj/item/clothing/gloves/aerostaticgloves
ditto

2023-07-31 00:56 UTC, nevimer commented on modular_zubbers/code/modules/clothing/outfits/kim.dm
> +/obj/item/clothing/shoes/boots/aerostaticboots
ditto

2023-07-31 00:56 UTC, nevimer commented on modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_glasses.dm
> +	item_path = /obj/item/clothing/glasses/binoclardlenses
same here, has to be consistent

2023-07-31 00:56 UTC, nevimer commented on modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_gloves.dm
> +	item_path = /obj/item/clothing/gloves/aerostaticgloves
and here

2023-07-31 00:56 UTC, nevimer commented on modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_shoes.dm
> +	item_path = /obj/item/clothing/shoes/boots/aerostaticboots
and here

2023-07-31 01:06 UTC, NotMergot commented on tgstation.dme
> +#include "modular_zubbers\code\modules\clothing\outfits\kim.dm"
ah right sorry just tick it right?

2023-07-31 03:13 UTC, NotMergot commented
GOOD LORD

2023-09-13 05:28 UTC, closed without merging

2023-09-13 05:28 UTC, nevimer commented
bap, must be finished up and rebased