Adds a bit of QoL to the monophobia quirk
Bubberstation/Bubberstation pull request #494
Opened 2023-08-29 06:57 UTC by NithaIsTired

## About The Pull Request
Checks for plushies nearby so they also count as a friend, hug them away!
fixes it not looking at pets when picked up in hands.
Makes the price more in pair with RDS, as it does have hallucinations symptoms and heart attacks included.

## Why It's Good For The Game
Makes the quirk more tolerable to the few poor souls that decides to play with it. Encourages RP while giving it a unique way to
do so.

Now you have an excuse to just be holding a shark plushie all the time!
![dreamseeker_j3rDCTCW12](https://github.com/Bubberstation/Bubberstation/assets/132854285/25b37acc-9f67-47e9-a428-1e8f95083bfb)
![dreamseeker_Y3S9PHfLHI](https://github.com/Bubberstation/Bubberstation/assets/132854285/62170d76-71c5-4f4a-8668-ebba4ffcd9d7)

## Changelog

:cl:
add: Added a bit of QoL to the monophobia quirk
/:cl:

2023-08-29 07:17 UTC, Majkl-J requested changes

2023-08-29 07:17 UTC, Majkl-J commented on code/datums/brain_damage/severe.dm
> +
```suggestion
	for(var/mob/M in owner.held_items) //makes sure to check hands for your tiny friends!
		if(!isliving(M)) //ghosts ain't people
			continue
		if(istype(M, /mob/living/simple_animal/pet) || istype(M, /mob/living/basic/pet) || M.ckey)
			return FALSE

```

2023-08-29 07:17 UTC, Majkl-J commented on code/game/objects/items/plushes.dm
> +			to_chat(user, span_warning("A reminder that even stitched companions can't stop the solitude building up inside your heart..."))
```suggestion
			to_chat(user, span_warning("You remember that even stitched companions can't stop the solitude building up inside your heart..."))
```

2023-08-29 12:01 UTC, YakumoChen commented
Doesn't thus generally just invalidate the quirk?

Anyway these edits aren't modular so they won't work.

2023-08-29 12:36 UTC, NithaIsTired commented
> Doesn't thus generally just invalidate the quirk?
> 
> Anyway these edits aren't modular so they won't work.

It doesn't really invalidate the quirk, it depends a lot on rns so this should make it less annoying if you do want/need to do something alone for some time or maybe even afk urgently, given the chance of just having a heart attack because you walked away from people for a minute and you got bad rng.

You were always able to just bring a pet and it would completely invalidade the quirk anyways if you weren't roleplaying it out. I just aim to add a bit more options to the quirk to make it more fun, giving it another unique way to roleplay it.

As for modularity I can take a look at it later today.

2023-08-29 22:52 UTC, YakumoChen commented
> > Doesn't thus generally just invalidate the quirk?
> > Anyway these edits aren't modular so they won't work.
> 
> It doesn't really invalidate the quirk, it depends a lot on rns so this should make it less annoying if you do want/need to do something alone for some time or maybe even afk urgently, given the chance of just having a heart attack because you walked away from people for a minute and you got bad rng.
> 
> You were always able to just bring a pet and it would completely invalidade the quirk anyways if you weren't roleplaying it out. I just aim to add a bit more options to the quirk to make it more fun, giving it another unique way to roleplay it.
> 
> As for modularity I can take a look at it later today.

I feel like there is a profound difference between holding an animal that you have to go out of your way to find, is noisy, and dies in a hostile environment compared to a toy you spawn with. If anything, the responsibility of caring for the pet is more interesting using it to bypass the quirk. 

I don't see how replacing it with a boring roundstart item is good for the qame in comparison.

2023-08-31 08:47 UTC, NithaIsTired commented
> I feel like there is a profound difference between holding an animal that you have to go out of your way to find, is noisy, and dies in a hostile environment compared to a toy you spawn with. If anything, the responsibility of caring for the pet is more interesting using it to bypass the quirk.
> 
> I don't see how replacing it with a boring roundstart item is good for the qame in comparison.

It is not replacing it. You can leave pets anywhere in your vision and they will count as a companion. With this you need to hold a plushie to make it count as a companion. Plushies are way more easy to steal, get caught on fire or rip their stuffing and you can't really get another one with the same name after you lose the roundstart one, making them more unique than a random generic pet you got from cargo and is there just because you don't want to randomly get a heart attack.
This is aimed at giving the quirk a bit more freedom to be roleplayed in more ways without being punished by death that is simply RNG. I don't think completely relying on mechanical parts of the game is good.

2023-08-31 10:13 UTC, NithaIsTired commented
aaauuugh I'll need to do this PR again... Probably should sleep before I do it this time

2023-08-31 10:13 UTC, closed without merging