Adds hereprisoner
Bubberstation/Bubberstation pull request #538
Opened 2023-09-11 06:35 UTC by BoundCNapalm

## About The Pull Request

Allows heretic prisoner by removing JOB_PRISONER from protected roles.

## Why It's Good For The Game

Prisoners are already being monitored to begin with, so you can pretty easily get rid of heretic then. Heretic prisoner has cool roleplay opportunities. Especially if a chaplain comes in to exorcise the prisoner. 

## Changelog

All this does is allow heretic prisoner spawns by removing them from the protected roles list. 

:cl:
code: Removes two of the same entries in the heretic spawns, JOB_PRISONER.
config: Adds natural heretic prisoner spawns.
/:cl:

2023-09-13 05:01 UTC, nevimer commented
nonmodular undocumented remove, please comment it out instead

2023-09-15 03:19 UTC, BoundCNapalm commented
Will add commits soon to revert it

2023-10-24 11:10 UTC, BurgerLUA requested changes

2023-10-24 11:10 UTC, BurgerLUA commented on code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
> +		//JOB_PRISONER,
This needs to be indicated that it is a modular change.

2023-10-27 23:13 UTC, StrangeWeirdKitten commented on code/game/gamemodes/dynamic/dynamic_rulesets_roundstart.dm
> +		//JOB_PRISONER,
```suggestion
		//JOB_PRISONER, - BUBBERSTATION REMOVAL
```

2023-10-27 23:14 UTC, StrangeWeirdKitten commented on code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
> +		//JOB_PRISONER, ## BUBBER EDIT REMOVAL
```suggestion
		//JOB_PRISONER, - BUBBERSTATION REMOVAL
```

2023-10-27 23:16 UTC, StrangeWeirdKitten commented
Basic edits aside, this can be test merged.

2023-11-20 07:26 UTC, projectkepler-ru commented
Stale

2023-11-23 05:11 UTC, closed without merging