Restores Changeling Objectives
Bubberstation/Bubberstation pull request #542
Opened 2023-09-13 03:26 UTC by BoundCNapalm

## About The Pull Request

Deletes the override intended to nix changeling objectives.

## Why It's Good For The Game

Out of all of my PRs, this one should be the most obvious. Gives changelings without gimmicks or purpose something to do. If they want to greentext, that is.

## Changelog

Restores Changeling Objectives via deleting code.

:cl:
change: Lings should spawn with objectives now.
code: Deleted the skyrat changeling directory. Keep an eye on the folders incase something like this happens again.
staff: This should prevent changelings asking what to do.
/:cl:

2023-09-13 04:23 UTC, nevimer commented
you must build and commit the dme

2023-09-15 17:10 UTC, nevimer commented
I'd rather just comment the file out.

2023-10-24 11:09 UTC, BurgerLUA requested changes
The file should be commented out instead of deleted to ensure maximum compatibility with upstreams.

2023-10-28 06:51 UTC, StrangeWeirdKitten requested changes
As said above, don't delete the file. Comment it out completely.

2023-11-02 07:00 UTC, closed without merging