Add plant dna manipulator board to wild mutation experiment reward
Bubberstation/Bubberstation pull request #564
Opened 2023-09-21 06:15 UTC by yorii

## About The Pull Request

Adds the Plant DNA Manipulator circuit board to the tech node rewarded from the wild mutation experiment.

## Why It's Good For The Game

Since the plant manipulator is only available on Metastation, I think it should at least be added as a science reward to be constructed later in the round on the other maps too. 
Plus allows you to reconstruct it in case it gets destroyed on Metastation.

## Changelog

:cl:
add: Added Plant DNA Manipulator circuit board to techweb node.
/:cl:

2023-10-24 11:08 UTC, BurgerLUA approved these changes

2023-10-28 01:32 UTC, StrangeWeirdKitten commented
This PR is redundant, specifically with ``modular_zubbers\code\modules\research\techweb\all_nodes.dm`` already having the techweb things necessary, though uncommented out. ``C:\Users\gotnu\Documents\GitHub\Bubberstation\modular_zubbers\code\modules\research\designs\misc_designs.dm`` is also unticked for whatever reason. 

All that has to happen for everything to get into the techweb is for the code to be enabled. Uncomment the techweb node I pointed out and tick ```misc_designs.dm``` so it's included in the compile.

2023-10-28 01:33 UTC, StrangeWeirdKitten requested changes

2023-10-28 01:33 UTC, StrangeWeirdKitten commented on code/modules/research/techweb/all_nodes.dm
> +		"plantgene",
Go look at ``modular_zubbers\code\modules\research\techweb\all_nodes.dm`` and remove this.

2023-10-28 01:35 UTC, StrangeWeirdKitten commented on code/modules/research/techweb/all_nodes.dm
> +		"plantgene",
Also in the future make sure you document Bubberstation edits with a comment

2023-12-01 07:46 UTC, Majkl-J commented
Stale. Ask for a reopen when work on this begins again

2023-12-11 00:07 UTC, yorii commented
> This PR is redundant, specifically with `modular_zubbers\code\modules\research\techweb\all_nodes.dm` already having the techweb things necessary, though commented out. `modular_zubbers\code\modules\research\designs\misc_designs.dm` is also unticked for whatever reason.
> 
> All that has to happen for everything to get into the techweb is for the code to be enabled. Uncomment the techweb node I pointed out and tick `misc_designs.dm` so it's included in the compile.

Thank you very much! And I'm sorry for forgetting this PR and letting it go stale, I'll get it up to par right away :)

2023-12-11 05:25 UTC, yorii commented
Please re-open when anyone sees this

2023-12-15 09:48 UTC, Majkl-J approved these changes
Looks fine

2023-12-16 22:50 UTC, merged