Adds a very small healing buff to the high complexity food mood
Bubberstation/Bubberstation pull request #603
Opened 2023-10-11 06:40 UTC by Majkl-J

## About The Pull Request

Provides a very minor buff to eating high quality and high liking foods.

The heal has a pretty small chance to happen every tick (~5-10%) and heals a single point of damage (Two if the food was godlike), so it isn't in any way game winning.

## Why It's Good For The Game

Adds a reason for people to cook actually good foods, for people to request said foods, etc.
Moffy asked me to do this and I obey our great leader and his every request he deems good.

## Changelog

:cl:
add: Added a minor healing effect to excellent foods
/:cl:

2023-10-20 00:05 UTC, nevimer commented
not sure if i want more food bypassing medical

2023-10-20 05:55 UTC, Majkl-J commented
> not sure if i want more food bypassing medical

It already takes quite an effort to get a godlike food, and the rest of the healing is so disappointingly minor a botanist with an ambrosia could heal it faster

2023-10-24 11:02 UTC, BurgerLUA requested changes

2023-10-24 11:02 UTC, BurgerLUA commented on modular_zubbers/code/datums/mood_events/food_events.dm
> +			O.apply_status_effect(/datum/status_effect/food/quality_healing, effect_strength)
``. = ..()`` should be added at the start to guarantee full compatibility

2023-11-02 11:04 UTC, merged