Hypospray & hypokit added to the cargo company listings.
Bubberstation/Bubberstation pull request #632
Opened 2023-10-20 23:23 UTC by shellspeed1

## About The Pull Request

Adds hypospray kits and hyposprays to cargo.

## Why It's Good For The Game

While looking at the cargo offerings, I just had a thought. Why the heck aren't hyposprays buyable but you can get a full set of surgical tools for 200 credits. Anyway, adds something else for medical to spend money on that isn't a gun. Also flavor.

## Changelog

:cl:
add: Hyposprays and empty Hypospray kits can now be bought from Deforest.
/:cl:

2023-10-24 10:36 UTC, BurgerLUA requested changes

2023-10-24 10:36 UTC, BurgerLUA commented on modular_skyrat/modules/hyposprays/code/hypospray_kits.dm
> +
These two lines should be removed. Blank commits are bad.

2023-10-24 10:36 UTC, BurgerLUA commented on modular_skyrat/modules/company_imports/code/armament_datums/deforest_medical.dm
> +
``//Bubber changes end`` should be at the bottom of this

2023-10-25 12:37 UTC, projectkepler-ru approved these changes

2023-10-25 22:46 UTC, merged