Icebox changes
Bubberstation/Bubberstation pull request #644
Opened 2023-10-24 18:04 UTC by Ldip999

## About The Pull Request

Moves botany next to kitchen like it was in old box and puts a little picnic area to where level 3 botany was. Also adds a lustwish to dorms.

## Why It's Good For The Game

Botany being in a shame basement is not only bad for gameplay but just plain awkward and antisocial. This should promote interaction and hopefullyencourage  more people to play botany on icebox like on delta where botany also isn't hidden away but nicely next to kitchen. Also our lustwish got taken away when we merged from upstream so here it is back. Picnic area great for hanging out/renovate into social spaces, since the map lacks a neutral hangout place that doesn't belong to any job other than dorms which is tiny here relatively unlike the coffee shops in a bunch of other maps.

## Changelog

:cl:
add: Picnic/Hangout area to icebox
add: Added missing lustwish to dorms on icebox
del: Level 2 botanyon icebox
qol: Moved botany next to kitchen on icebox
/:cl:

2023-10-24 19:57 UTC, StrangeWeirdKitten commented
This looks nice and all, but it's going to get immediately overridden by upstream.

2023-10-24 23:02 UTC, nevimer commented
> This looks nice and all, but it's going to get immediately overridden by upstream.

Yeah, automapper or it can't survive here.

2023-10-25 23:34 UTC, StrangeWeirdKitten requested changes
Either take it upstream to TG, or use Skyrat's automapper. These changes are not going to survive here since the next upstream will override them.

2023-10-30 06:03 UTC, StrangeWeirdKitten commented
Closing. Feel free to reopen again if you get it automapped.

2023-10-30 06:03 UTC, closed without merging