Allow Antag names on spawn for ghost roles and antagonists
Bubberstation/Bubberstation pull request #685
Opened 2023-11-03 06:14 UTC by ReturnToZender

## About The Pull Request
This pull request intends to make it so that players, when spawning as an antagonist or a ghost role, will use their alternate preference, allowing players to set an alt name for when they spawn as an antagonist.

Currently, this does not work, the preference does show up, but does not apply on either type of spawn. I'll need help to do the rest.

## Why It's Good For The Game
This prevents situations where John Medical from last round is the Lone Operative this round.
![image](https://github.com/Bubberstation/Bubberstation/assets/110273561/654fcea1-40af-48cd-a992-7067475a84e0)
Progress so far.

## Changelog

:cl:
add: Antag names
/:cl:

2023-11-11 06:51 UTC, ReturnToZender commented
Progress update: Syndicate names now function properly
![image](https://github.com/Bubberstation/Bubberstation/assets/110273561/aaef9eef-15e8-4670-84cd-da25ce62b269)

2023-11-17 17:23 UTC, nevimer requested changes

2023-11-17 17:23 UTC, nevimer commented on modular_skyrat/modules/contractor/code/datums/midround/antag_datum.dm
> +		person.dna.update_dna_identity()
```suggestion
		if(person.client)
			person.apply_pref_name(/datum/preference/name/syndicate, person.client)
		person.dna.update_dna_identity()
```

2023-11-17 17:24 UTC, nevimer commented on code/modules/antagonists/nukeop/nukeop.dm
> +		operative.dna.update_dna_identity()
```suggestion
	if(iscarbon(operative))
		if(operative.client)
			operative.apply_pref_name(/datum/preference/name/syndicate, operative.client)
		operative.dna.update_dna_identity()
```

2024-01-15 05:49 UTC, ReturnToZender commented
PR closed due to getting stale, I'll get back to this later.

2024-01-15 05:49 UTC, closed without merging