[Modular] Loads of cosmetics
Bubberstation/Bubberstation pull request #699
Opened 2023-11-09 01:11 UTC by ReturnToZender

## About The Pull Request
Adds a ton of donor cosmetics, as well as other sprites from across the game, to the loadout

## Why It's Good For The Game
More expression, more fun!

## Changelog

:cl:
add: 4 plushies to loadout, one works as a bar of soap (but cannot slip)
add: 2 unauthorized command uniforms (to loadout, will be added as contraband in the command vendor)
add: golden pinwheel hat for people who have referred at least 2 people to Bubberstation (ckey whitelist lists all people so far and will be updated)
add: Korve and Union cards (reskinned cardboard cards) for additional customization
add: green resprites of every major medical tool using advanced reskins (UNTESTED)
add: working runner jackets (they were improperly indented before)
add: fixes loadout jumpsuits for a randomhyena
add: adds trucker jacket
add: ports Cyberpunk 2077 Ronin jacket from Citadel
add: starwire wine bottle that contains wine
add: Glow shoes to loadout
add: Mech pilot costume to loadout
del: redundant _plush in icon names, moves sprites to the proper file
del: two redundant Syndicate turtlenecks, these are already available in proper balanced form in modular_skyrat's loadout_datum_under.dm folder.
/:cl:

2023-11-09 01:11 UTC, ReturnToZender commented
Had to make a new version after I renamed my branch

2023-11-09 01:59 UTC, BrandonSmith6 commented
**Patiently waiting for merge...**

2023-11-14 08:52 UTC, StrangeWeirdKitten requested changes

2023-11-14 08:52 UTC, StrangeWeirdKitten commented on modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_pocket.dm
> +	name = "Swtarwire wine bottle"
```suggestion
	name = "swtarwire wine bottle"
```

2023-11-14 08:52 UTC, StrangeWeirdKitten commented on modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_under.dm
>  	name = "Urban camouflage BDU"
```suggestion
	name = "urban camouflage BDU"
```

2023-11-14 08:52 UTC, StrangeWeirdKitten commented on modular_zubbers/code/modules/loadouts/loadout_items/loadout_datum_under.dm
> +	name = "Mech pilot's suit"
```suggestion
	name = "mech pilot's suit"
```

2023-11-14 08:53 UTC, StrangeWeirdKitten commented
Test merging

2023-11-14 09:03 UTC, merged