Australicus Slime Mutator buyable with TC once more
Bubberstation/Bubberstation pull request #709
Opened 2023-11-12 10:14 UTC by Elli-Skala

spooders

## About The Pull Request

removes a skyrat edit removing the Australicus Slime Mutator from the sci, robotics, and RD uplink

## Why It's Good For The Game

enables brilliant new traitor interaction with spider friends
## Changelog

:cl:
balance: Australicus Slime Mutator reported to be once more circulating on the syndicate black market
/:cl:

2023-11-22 04:31 UTC, projectkepler-ru approved these changes
This can only be good

2023-11-23 18:03 UTC, ReturnToZender commented
Update your branch using the button on Github and it'll give you the fabled green checkmark

2023-12-15 09:51 UTC, Majkl-J requested changes
Add Bubber edit comments

2023-12-25 15:08 UTC, projectkepler-ru requested changes

2023-12-25 15:08 UTC, projectkepler-ru commented on code/modules/uplink/uplink_items/job.dm
> -/* //SKYRAT REMOVAL START
//Bubber Edits

2023-12-25 15:08 UTC, projectkepler-ru commented on code/modules/uplink/uplink_items/job.dm
> -// SKYRAT EDIT END
//Bubber Edits end

2023-12-25 18:41 UTC, closed without merging