Ascii Healthhud
Bubberstation/Bubberstation pull request #712
Opened 2023-11-13 06:45 UTC by nevimer

## About The Pull Request

Bit of an experiment. I wanted to add numbers and make the healthhud look better.

https://github.com/Bubberstation/Bubberstation/assets/77420409/7f44418e-cc46-4915-92a3-a0f811fa7d6b

YES. I know it's kinda fugly with the gap. Yeah, I should tweak it more. 

## Why It's Good For The Game

Honestly, I might keep the numbers only. But I think it adds some uniqueness!

## Changelog

:cl:
code: Changed the healthhud to be entirely maptext.
add: You can now see a simple health readout on healthhud. 
/:cl:

2023-11-13 06:54 UTC, Majkl-J commented
This will terribly clog the screen and is not as readable as a single bar, I'd rather see this added to the healthud examine.

2023-11-13 07:03 UTC, nevimer commented
> This will terribly clog the screen and is not as readable as a single bar, I'd rather see this added to the healthud examine.

![kwFImkIY4m](https://github.com/Bubberstation/Bubberstation/assets/77420409/a7bd9cbd-1025-4691-bb22-753919d43603)
numbers alone don't look bad

2023-11-13 07:05 UTC, nevimer commented
![dreamseeker_xCbB5zBXpw](https://github.com/Bubberstation/Bubberstation/assets/77420409/36f4f662-cef3-49c9-b96f-85cf8a299327)
this is with the normal healthbar

2023-11-13 07:19 UTC, Majkl-J commented
> > This will terribly clog the screen and is not as readable as a single bar, I'd rather see this added to the healthud examine.
> 
> ![kwFImkIY4m](https://user-images.githubusercontent.com/77420409/282386218-a7bd9cbd-1025-4691-bb22-753919d43603.png) numbers alone don't look bad

They don't but they also aren't as readable as a bar which tells you exactly how critical that person is. The numbers usually aren't important, just the damage types and the overall amount of damage visualised by the bar. 

I would rather see small horizontal bars atop the regular bar to tell you the type of damage

2023-11-13 08:25 UTC, The-Sun-In-Splendour commented
Make it a toggle using one of those buttons in the top left so you can choose wether you use it or not. If it's on all the time it's going to be a chore wearing healthHUDs.

2023-11-13 16:43 UTC, zeroisthebiggay commented
i don't like it. that is my feedback
it's just not natural or intuitive to read

2023-11-13 16:45 UTC, nevimer commented
Current todo:
Make it a medhuds mode, somehow. Hud code is too simple right now, so I may have to make this an alternative hud that combines with the base medhuds object, like engineering scanner goggles.

2023-11-13 22:23 UTC, Cyprex commented on code/game/data_huds.dm
> +// BUBBER EDIT BEGIN
```suggestion
// BUBBER EDIT BEGIN- Health Hood with numbers
```

2023-11-13 22:24 UTC, Cyprex commented on code/game/data_huds.dm
> +// BUBBER EDIT BEGIN
Or something like that

2023-11-13 23:57 UTC, Cyprex commented
How performant is this? I understand Runechat isn't very performant.

As for the bars- I think they're unnecessary & better served by the current HUD. Being less in your face is the point there. I think the individual damage numbers do have a point though, but I don't know if this is better to play with or not. Also, how does this interact with runechat, does the text overlay or something?

2023-11-14 00:26 UTC, StrangeWeirdKitten requested changes
I've given my feedback. TD;LR make is a mode you can switch to off the basic default one. Use #717 for feedback please. I'll be looking at that too.

2023-11-14 00:36 UTC, nevimer commented
> How performant is this? I understand Runechat isn't very performant.
> 
> As for the bars- I think they're unnecessary & better served by the current HUD. Being less in your face is the point there. I think the individual damage numbers do have a point though, but I don't know if this is better to play with or not. Also, how does this interact with runechat, does the text overlay or something?

Runechat is not performance because it's overly complicated with a ton of expensive proc calls (measuretext), and it creates a new individualized, personalized, preference respecting, image object... for every single client in the game. So every single chat, emote, etc, can cause 50+ datums to be generated.

This just applies and sets variables on a single global image. Maptext is basically free as it's a clientside variable and rendered entirely client side.

2023-11-15 05:24 UTC, Shroopy commented
Doesn't work correctly on small models, the text is illegible. Also, it's very difficult to use on horizontal characters.

2023-11-15 05:29 UTC, YakumoChen commented
![image](https://github.com/Bubberstation/Bubberstation/assets/10399117/82f2da9b-6403-4ca0-9bc5-8636c0cefd5e)
in-game example (you can see run-off numbers and sideways text and large/varied damage types taking increasing amounts of screen real estate)

2023-11-15 07:13 UTC, Majkl-J commented
This unironically makes me not wanna play medbay. It has terrible readability and provides significantly less knowledge on how critical a patient is than the good old bar

2023-11-15 11:15 UTC, ReturnToZender commented
Medical doesn't need more information than just "how close is X to dying," and the existing system works more than well enough for it, while ALSO being small and intuitive. This system has its bugs, but more than that-- it's really unnecessary. Medical already receives more than enough information to know at a glance what is needed from the existing HUD, and the specific damage type can be inferred by a simple scan or by examining the patient.

Either way, this is really just unnecessary bloat. I appreciate the PRs for Medical but they don't need everything spoonfed to them to do their jobs, they have everything they need and then some.

2023-11-15 15:59 UTC, nevimer commented
use the forum to discuss and not the pr body.

2023-11-15 19:16 UTC, StrangeWeirdKitten commented
The testing of this PR is finished. The feedback thread can be found [here](https://github.com/Bubberstation/Bubberstation/discussions/723) I'll be unlocking the PR regarding code standards / bugs. But I've already provided my input and the necessary changes needed.

2023-11-15 19:33 UTC, BurgerLUA commented on code/game/data_huds.dm
> +		holder.maptext_width = 128
I recommend using the RESET_TRANSFORM appearance flag to ignore all size/rotation changes from the health hud so it's readable for larger/smaller mobs.

If that doesn't work, use KEEP_APART along with it.

2023-11-15 19:35 UTC, BurgerLUA commented on code/game/data_huds.dm
> +		holder.maptext_width = 128
``holder.appearance_flags = RESET_TRANSFORM | KEEP_APART``

2024-01-11 08:25 UTC, Majkl-J commented
Stale for a month, reopen when work continues

2024-01-11 08:25 UTC, closed without merging