[Nonmodular] Wear a condom
Bubberstation/Bubberstation pull request #713
Opened 2023-11-13 06:48 UTC by ReturnToZender

## About The Pull Request
Adds condoms to the luxury emergency box trait. Truly luxurious!

## Why It's Good For The Game
Less STDs on-station

## Changelog

:cl:
add: Condoms to the psych locker and emergency box
/:cl:

2023-11-13 06:59 UTC, ReturnToZender commented
This is mostly a joke PR however feel free to merge

2023-11-13 07:03 UTC, Majkl-J commented
All this can be modularised by extending PopulateContents()

2023-11-13 07:03 UTC, Majkl-J requested changes
All this can be modularised by extending the respective PopulateContents()

2023-11-15 02:56 UTC, nevimer requested changes

2023-11-15 02:56 UTC, nevimer commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	//BUBBER EDIT BEGIN: WEAR A CONDOM
```suggestion
	//BUBBER EDIT BEGIN: WEAR A CONDOM
	for(var/i in 1 to 6)
		new /obj/item/condom_pack(src)
	//BUBBER EDIT BEGIN: WEAR A CONDOM
```

2023-11-23 13:46 UTC, larentoun commented on code/game/objects/items/storage/boxes/job_boxes.dm
> +		new /obj/item/condom_pack(src) //BUBBER EDIT: WEAR A CONDOM
I believe this can be modular? Check `crafted` for early return and then check the trait

2023-11-23 13:47 UTC, larentoun commented on code/game/objects/structures/crates_lockers/closets/secure/medical.dm
> +	//BUBBER EDIT BEGIN: WEAR A CONDOM
This can be done modular too I believe?

2023-12-05 18:52 UTC, ReturnToZender commented
This was a joke PR, but now I wanna close it so maintainers don't have to review it on top of their existing workload. Might pull it up later if people _actually_ want it, but I doubt it matters that much.

2023-12-05 18:52 UTC, closed without merging