You can now dig through sofa pillows
Bubberstation/Bubberstation pull request #727
Opened 2023-11-15 13:31 UTC by Majkl-J

## About The Pull Request

Worthless coins galore, you can find iron coins (Or something special) under sofa pillows by rightclicking with an empty hand.

## Why It's Good For The Game

Fun interaction with no side effects whatsoever

## Changelog

:cl:
add: You can now rightclick with an empty hand to search sofa pillows for change
/:cl:

2023-11-15 19:54 UTC, StrangeWeirdKitten commented on modular_zubbers/code/game/objects/structures/beds_chairs/sofa.dm
> +					return
I'm going to discuss this. The main PR itself is fine as a minor fluff thing, but I don't really like adding random astronomically low meme chances to "find" a critical station item. While extremely funny, this is on the table and I'm going to grab other's opinions before merging it.

2023-11-15 20:08 UTC, StrangeWeirdKitten requested changes
I asked and the agreement was no.

2023-11-15 21:05 UTC, YakumoChen commented
Make it a fake disk

2023-11-17 17:50 UTC, StrangeWeirdKitten approved these changes

2023-11-18 13:35 UTC, StrangeWeirdKitten approved these changes

2023-11-18 13:35 UTC, StrangeWeirdKitten commented
Oh I already approved it, lol. I'll look at merging this later

2023-11-18 15:46 UTC, merged