adds cameras to dauntless
Bubberstation/Bubberstation pull request #732
Opened 2023-11-16 04:30 UTC by YakumoChen

## About The Pull Request

![image](https://github.com/Bubberstation/Bubberstation/assets/10399117/d1e69f13-0fd6-4d4a-8fc8-7ad218593cc6)
Adds cameras to Dauntless, as well as replacing the camera consoles in security with ones that actually use the dauntless camera network.
## Why It's Good For The Game

Having three different consoles for watching the station was a little strange, especially since the prison has no cameras to watch the prisoners with. For the sake of realism, I put cameras all over the station for the bored Master of Arms to scroll tthrough

## Changelog

:cl:
add: Dauntless now has a proper cameranet, and consoles to monitor it.
/:cl:

2023-11-16 08:59 UTC, Majkl-J requested changes
Feels like there are needlessly too many cameras. Would be fine to have a few blind tiles rather than having to click through several screens because of one

2023-11-16 10:22 UTC, YakumoChen commented
any area in particular? I figured I'd just be thorough,

2023-11-16 10:47 UTC, YakumoChen commented
![image](https://github.com/Bubberstation/Bubberstation/assets/10399117/3980035c-569e-49d0-8c0d-a9692423b8dd)
camera list is much more pruned now

2023-11-17 17:54 UTC, StrangeWeirdKitten approved these changes

2023-11-17 17:54 UTC, merged