Adds some emotes
Bubberstation/Bubberstation pull request #745
Opened 2023-11-21 15:57 UTC by pixelkitty286

## About The Pull Request

Adds some emotes

## Why It's Good For The Game

MRRP MRP MEOW! You play like a cat
As much as I loath Tesh I like Prbt

## Changelog

:cl:
add: emotes: mrrp, fpurr, gecker, and prbt
sound: mrrp.ogg, prbt.ogg, fox_purr.ogg, and foxgecker.ogg
/:cl:

2023-11-21 21:25 UTC, ReturnToZender commented
Emote code needs to go in the zubbers folder, not the skyrat folder

2023-11-21 23:59 UTC, StrangeWeirdKitten requested changes
Yup. What moth said.

2023-11-22 02:00 UTC, pixelkitty286 commented
OH LOL Hold on let me fix that

2023-11-22 11:39 UTC, theselfish commented on modular_zubbers/modules/emotes/code/emotes.dm
> +	message = "geckers."
```suggestion
	message = "geckers!"
```
Should make this an exclamation for consistency.

2023-11-23 02:47 UTC, pixelkitty286 commented
I love CI Suite failing with an error that is not my doing.

2023-11-23 02:51 UTC, StrangeWeirdKitten commented
> I love CI Suite failing with an error that is not my doing.

Sometimes it happens.

2023-11-23 02:57 UTC, StrangeWeirdKitten approved these changes

2023-11-23 03:13 UTC, StrangeWeirdKitten commented
@pixelkitty286 before I merge this, I need to know where you got these sounds.

2023-11-23 03:38 UTC, pixelkitty286 commented
> @pixelkitty286 before I merge this, I need to know where you got these sounds.
mrrp.ogg or cat_meow_after_jump_alt06.ogg is from the videogame Stray from B12 studios.
prbt.ogg unknown file is from CitRP under the misc sound folder. Where they got it from is unknown.
fox_purr.ogg & foxgecker.ogg from discord user izzyyess. Where they got it from is unknown.

2023-11-23 04:42 UTC, merged