energy revolver & laser changes
Bubberstation/Bubberstation pull request #75
Opened 2023-03-03 14:53 UTC by W0LF-101

Energy Revolver Changes:
No longer selfcharges 
Cell charge reduced from 1500 to 1000
Takes more power to fire lethal and taser shots (10% & 20% vs 5% and 13%) 

SC-1 Laser Gun Changes:
Takes less power to fire lethal shots (from 6% to 5%)

2023-03-09 17:16 UTC, W0LF-101 commented
Please testmerge this alongside PR #98 Energy Sec as this change buffs the SC-1s to encourage picking those when the nonlethal ability of the SC-2s is not desired.

2023-03-09 22:14 UTC, Cyprex requested changes
Looks good otherwise

2023-03-09 22:14 UTC, Cyprex commented on code/modules/projectiles/ammunition/energy/laser.dm
> +	projectile_type = /obj/projectile/beam/laser
```suggestion

```

2023-03-09 22:14 UTC, Cyprex commented on code/modules/projectiles/ammunition/energy/laser.dm
> +	select_name = "kill"
```suggestion
```

2023-03-09 22:14 UTC, Cyprex commented on code/modules/projectiles/ammunition/energy/laser.dm
> +	select_name = "kill"
Removing these takes the values from `/obj/item/ammo_casing/energy/laser` instead, which is what you want here.
Also this ought to be modularised, I can handle that if you wish.

2023-03-21 07:43 UTC, projectkepler-ru requested changes

2023-03-21 07:43 UTC, projectkepler-ru commented on modular_skyrat/modules/blueshield/code/special.dm
> +	maxcharge = 1000
keep the max charge at 1500

2023-03-25 09:01 UTC, projectkepler-ru requested changes
Scratch that, change it to 800 and reenable self charging, I'm reintroducing it as a blueshield sidearm then this is good to merge

2023-03-25 13:07 UTC, projectkepler-ru requested changes

2023-03-26 20:32 UTC, merged