[Modular] Adds mouse waddle
Bubberstation/Bubberstation pull request #783
Opened 2023-11-28 19:08 UTC by ReturnToZender

## About The Pull Request
Makes it so mice waddle

## Why It's Good For The Game
The mice need to waddle in sync with the rat king, and this provides that

## Changelog

:cl:
add: Mice waddle
/:cl:

2023-11-28 19:10 UTC, nevimer commented
may be laggy

2023-11-28 21:08 UTC, Majkl-J requested changes
Simple formatting changes

2023-11-28 21:08 UTC, Majkl-J commented on modular_zubbers/code/modules/mob/living/basic/vermin/mouse.dm
> +//Bubber Edit Addition: MICE WADDLE NOW.
```suggestion
//Bubber Edit Addition: MICE WADDLE NOW.
/mob/living/basic/mouse/Initialize(mapload, tame = FALSE, new_body_color)
	. = ..()
	AddElement(/datum/element/waddling)
```

2023-11-28 21:17 UTC, Majkl-J commented
As for performance, I'll run checks for how long the respective movement procs take with and without the waddle. I know you can do this somehow, and I like challenging myself, so

2023-11-29 07:30 UTC, Majkl-J commented
![image](https://github.com/Bubberstation/Bubberstation/assets/49160555/437f9858-1988-47c0-ae3a-c2b79725a9dc)

2023-11-29 07:31 UTC, Majkl-J approved these changes
Performance impact seems minor enough for me, Let's see what @nevimer says

2023-11-30 04:39 UTC, merged