Lit Cakes
Bubberstation/Bubberstation pull request #797
Opened 2023-12-01 10:21 UTC by Odairu

## About The Pull Request
Adds the ability for Birthday Cakes to emit light similar to a red candle via any fire source, as well as be extinguished via fire extinguisher

## Why It's Good For The Game
My birthday cake can now actually light up my dark room

## Changelog
add: Birthday Cakes are now able to be lit and emit light

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
sound: added/modified/removed audio or sound effects
image: added/modified/removed some icons or images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-12-01 10:58 UTC, projectkepler-ru approved these changes

2023-12-02 15:35 UTC, Majkl-J commented
As a note to headtainers: Keep this on hold for about 2-3 days, I want to try my shot at optimizing this

2023-12-04 08:18 UTC, Majkl-J requested changes
Less copy paste code

2023-12-04 08:18 UTC, Majkl-J commented on modular_zubbers/modules/modular_items/code/cake_light.dm
> +	return ..()
```suggestion
#define FAILURE 0
#define SUCCESS 1
#define ALREADY_LIT 3

/obj/item/flashlight/flare/candle/cake

/obj/item/food/cake/birthday
	var/obj/item/flashlight/flare/candle/cake/candle

/obj/item/food/cake/birthday/Initialize(mapload)
	. = ..()
	candle = new(src)

/obj/item/food/cake/birthday/extinguish()
	. = ..()
	candle.extinguish()

/obj/item/food/cake/birthday/fire_act(exposed_temperature, exposed_volume)
	candle.fire_act(exposed_temperature, exposed_volume)
	return ..()

/obj/item/food/cake/birthday/attackby(obj/item/attacking_item, mob/user, params)
	candle.attackby(attacking_item, user, params)
	return ..()

// allows lighting an unlit candle from some fire source by left clicking the source with the candle
/obj/item/food/cake/birthday/pre_attack(atom/target, mob/living/user, params)
	candle.pre_attack(target, user, params)
	return ..()
```

2023-12-04 08:55 UTC, Majkl-J commented on modular_zubbers/modules/modular_items/code/cake_light.dm
> +	return ..()
You can just click the commit suggestion

2023-12-04 09:35 UTC, Majkl-J approved these changes
Merge ready

2023-12-04 14:56 UTC, merged