[Modular] ACTUALLY Restores some Languages removed by our ball & chain.
Bubberstation/Bubberstation pull request #803
Opened 2023-12-03 00:15 UTC by theselfish

## About The Pull Request

Title.
Pirates/skeletons have gotten their themed language back.
![image](https://github.com/Bubberstation/Bubberstation/assets/102828457/b800a29f-d7f6-4ea8-8cf7-265c693bf330)

Nekomantic has been restored to Felinids because the removal reason was "gEnEmOdDeRs iN SkYrAt ""lOrE"" " 
![image](https://github.com/Bubberstation/Bubberstation/assets/102828457/d61d2cf8-ac9e-4b64-9752-b4456199b8ea)

As a result, the Japanese language has returned to simply being a choosable language. If you wish to use that instead, it's in the selectable thing. I might switch this around if requested. 

## Why It's Good For The Game

This is essentially a reversion back to TG. 
Pirates should speak like pirates, the players act like pirates already. If requested/required I might look into making the fun language exclusive to the skeletons.
Neko is a species language. I also dislike the Japanese language as a species language.
I am not a saleswoman, I am not good at pitching things. 

## Changelog

:cl:
add: Neko is now the default language of Felinids again.
add: Pirate has been restored to be Piratespeak.
/:cl:

2023-12-03 00:41 UTC, nevimer approved these changes

2023-12-03 16:16 UTC, Majkl-J requested changes

2023-12-03 16:16 UTC, Majkl-J commented on modular_zubbers/modules/customization/modules/language/_language_holder.dm
> +	)
```suggestion
/datum/language_holder/felinid/Initialize()
	. = ..()
	understood_languages |= list(
		/datum/language/common = list(LANGUAGE_ATOM),
		/datum/language/nekomimetic = list(LANGUAGE_ATOM)
	)
	spoken_languages |= list(
		/datum/language/common = list(LANGUAGE_ATOM),
		/datum/language/nekomimetic = list(LANGUAGE_ATOM)
	)
```

Doing something like this. Should make it compatible incase skyrat adds more languages to these.
Do mind this is just atop of my head and might not be entirely right, but it works as an example

2023-12-04 07:38 UTC, Majkl-J requested changes

2023-12-04 07:38 UTC, Majkl-J commented on modular_zubbers/modules/customization/modules/language/_language_holder.dm
> +	)
```suggestion
	understood_languages |= list(
		/datum/language/common = list(LANGUAGE_ATOM),
		/datum/language/nekomimetic = list(LANGUAGE_ATOM)
	)
	spoken_languages |= list(
		/datum/language/common = list(LANGUAGE_ATOM),
		/datum/language/nekomimetic = list(LANGUAGE_ATOM)
	)
```

2023-12-04 07:38 UTC, Majkl-J commented on modular_zubbers/modules/customization/modules/language/_language_holder.dm
> +	)
```suggestion
/datum/language_holder/golem/bone/New()
	. = ..()
	understood_languages |= list(
		/datum/language/common = list(LANGUAGE_ATOM),
		/datum/language/piratespeak = list(LANGUAGE_ATOM)
	)
	spoken_languages |= list(
		/datum/language/common = list(LANGUAGE_ATOM),
		/datum/language/piratespeak = list(LANGUAGE_ATOM)
	)
```

2023-12-04 07:38 UTC, Majkl-J commented on modular_zubbers/modules/customization/modules/language/_language_holder.dm
> +	)
```suggestion
/datum/language_holder/skeleton/New()
	. = ..()
	understood_languages |= list(
		/datum/language/common = list(LANGUAGE_ATOM),
		/datum/language/piratespeak = list(LANGUAGE_ATOM)
	)
	spoken_languages |= list(
		/datum/language/common = list(LANGUAGE_ATOM),
		/datum/language/piratespeak = list(LANGUAGE_ATOM)
	)
```

2023-12-13 14:03 UTC, merged