Grants the ability to open Clown slots once more.
Bubberstation/Bubberstation pull request #853
Opened 2023-12-15 14:41 UTC by theselfish

## About The Pull Request

Title. Skyrat disabled it because they hate fun. We don't.

## Why It's Good For The Game

Say a Clown dies. Is arrested, or is just a bit shit.
What can you do?
Jackshit.
Pray, fax Clown Planet, but why wait on God or the Clown in the High Castle when you can do it yourself?
This also let's Antags, or Clowns summon more friends. Assuming people in the lobby wanna be a clown.

P.S. I commented out and unticked the Skyrat file for double safety. Tried to just override it, didn't work. If you have a better idea for this. You have the floor.

## Changelog

:cl:
add: Clown slots are re-openable by royal decree. The incident between Nanotrasen and King Honkington has been resolved.
/:cl:

2023-12-15 14:51 UTC, Majkl-J reviewed
This should work hopefully

2023-12-15 14:51 UTC, Majkl-J commented on modular_skyrat/master_files/code/modules/jobs/job_types/clown.dm
>  	job_flags = STATION_JOB_FLAGS | JOB_CANNOT_OPEN_SLOTS
you can just remove the bitflag with

```
/datum/job/clown/New()
	job_flags -= JOB_CANNOT_OPEN_SLOTS
	return ..()
```

2023-12-15 14:56 UTC, theselfish commented on modular_skyrat/master_files/code/modules/jobs/job_types/clown.dm
>  	job_flags = STATION_JOB_FLAGS | JOB_CANNOT_OPEN_SLOTS
Thank you.

2023-12-15 15:32 UTC, Majkl-J requested changes

2023-12-15 15:32 UTC, Majkl-J commented on modular_zubbers/code/modules/jobs/job_types/clown.dm
> +	return ..()
Ok so I thought about this and this is a terrible way to do it if skyrat ever brings these back.

This however should work
```suggestion
/datum/job/clown/New()
	job_flags = job_flags & (~JOB_CANNOT_OPEN_SLOTS)
	return ..()
```

2023-12-16 12:51 UTC, Majkl-J approved these changes
We love bitflag operations. Anyhow, approved

2023-12-16 17:04 UTC, Cyprex commented on modular_zubbers/code/modules/jobs/job_types/clown.dm
> +	job_flags = job_flags & (~JOB_CANNOT_OPEN_SLOTS)
```suggestion
	//remove JOB_CANNOT_OPEN_SLOTS bitflag in a modular fashion.
	job_flags = job_flags & (~JOB_CANNOT_OPEN_SLOTS)
```

2023-12-16 17:04 UTC, Cyprex commented
ngl I would prefer this be not done modularly because you can read the base code and it will say JOB_CANNOT_OPEN_SLOTS and it is all just a big fat lie- making code unreadable like this isn't great imo- but I don't think I'm in the majority here

2023-12-16 18:26 UTC, merged

2023-12-16 18:27 UTC, nevimer commented
it is fine. not a big deal for a single line.