Ports Eris/Yogstation slime sprites
Bubberstation/Bubberstation pull request #861
Opened 2023-12-17 17:07 UTC by Erol509

## About The Pull Request

https://github.com/yogstation13/Yogstation/pull/16942

https://github.com/discordia-space/CEV-Eris/pull/6205

## Why It's Good For The Game

Old slimes are old, I belive they might never actually see any sprite reword from TG/Skyrat side. Cev Eris has nice sprice for them, they are brighter and they are more cute looking now.

## Changelog

:cl:
image: Ported slime sprites from Yog/Cev Eris. Slimes are now prettier.
/:cl:

2023-12-17 18:37 UTC, Elli-Skala commented
> Old slimes are old, I belive they might never actually see any sprite reword from TG/Skyrat side.

They were changed this year.

2023-12-18 09:48 UTC, Majkl-J requested changes
Place the slimes into their new modular file and override the icon on the mob

2023-12-18 23:26 UTC, Majkl-J approved these changes
I'm not one to exactly rate the sprites, but the code is solid apart from minor comment stuff

2023-12-18 23:26 UTC, Majkl-J commented on modular_zubbers/code/modules/mob/living/simple_animal/slime/slime_sprites_override.dm
> +// slimes section
```suggestion
// basic slime sprite overrides
```

2023-12-18 23:26 UTC, Majkl-J commented on modular_zubbers/code/modules/mob/living/simple_animal/slime/slime_sprites_override.dm
> +/obj/item/slimecross
```suggestion
// slime crossbreeding sprite overrides
/obj/item/slimecross
```

2023-12-19 03:34 UTC, StrangeWeirdKitten commented
I tested the slimes on the live server and we've come to a conclusion that we will not replace the sprites. 

While I like them, the yogstation / eris slimes are too bright and colorful. They mesh with our asthetic.

2023-12-19 03:34 UTC, closed without merging