Abductor and HFZ Changes
Bubberstation/Bubberstation pull request #875
Opened 2023-12-21 12:11 UTC by SarmentiCampbell

## About The Pull Request
Removed the immunity of Injuries and delimbs from Abductors and made it so Zombies[not the infectious one, the high functioning one] are no longer space-proof

Unfortunately, Since abductors are not only a round-start specie but  also a antag, they were also affected by the nerf and i cannot do a subtype due to the fact that round-start species are server-sided.

## Why It's Good For The Game
Maybe turning a antag specie to a round-start specie was a bad idea since y'know, It had no respiration, the inability to be dismembered or gutted, no bloods and immunity to injuries, but y'know. idk.
Also, I was told that HFZ could have a chance to be added in if their space-proof were removed since their other strength and weaknesses were fine, so here you go.

## Changelog

:cl:
balance: removed abductor's wounds immunity and delimbs.
balance: Normal Zombies, not infectious types are no longer immune to pressure.
/:cl:

2023-12-21 12:22 UTC, Majkl-J requested changes

2023-12-21 12:22 UTC, Majkl-J commented on code/modules/mob/living/carbon/human/species_types/abductors.dm
> +	Their chunky tridactyl hands make it hard to operate human equipment."
Override this modularly by redefining /datum/species/abductor/get_physical_attributes() in modular files

2023-12-21 12:22 UTC, Majkl-J commented on code/modules/mob/living/carbon/human/species_types/zombies.dm
> +		*/
```
/datum/species/zombie/New()
	inherent_traits -= list(
		TRAIT_RESISTHIGHPRESSURE,
		TRAIT_RESISTLOWPRESSURE,
	)
	. = ..()
```

2023-12-21 12:22 UTC, Majkl-J commented on code/modules/mob/living/carbon/human/species_types/abductors.dm
>  	)
Pretty sure this messes up with the actual abductors. Could you maybe make it its own inherited species datum and make this one not available for crew.

2023-12-21 18:58 UTC, Majkl-J approved these changes
Looks good, will need @StrangeWeirdKitten to update the configs to reflect this change as they merge this

2023-12-22 02:51 UTC, nevimer commented
> Looks good, will need @StrangeWeirdKitten to update the configs to reflect this change as they merge this

I handle config. This looks fine for now.

2023-12-22 02:51 UTC, nevimer approved these changes

2023-12-24 03:52 UTC, destrucktoid commented
I'd honestly rather you just remove abductors from roundstart species, they are rarely used and as cool as they are and as much as i enjoy playing Ayyde, i'd rather not see the antag get cucked because someone on skyrat who doesn't care about balance added them to roundstart. Either that or make a new version of the abductor species but this one with the nerfs suggested in this PR (assuming that's possible).

2023-12-24 21:04 UTC, destrucktoid commented
> > I'd honestly rather you just remove abductors from roundstart species, they are rarely used and as cool as they are and as much as i enjoy playing Ayyde, i'd rather not see the antag get cucked because someone on skyrat who doesn't care about balance added them to roundstart. Either that or make a new version of the abductor species but this one with the nerfs suggested in this PR (assuming that's possible).
> 
> it is already how it's gonna work.

So this already just affects roundstart abductors and not antag abductors?

2023-12-25 10:57 UTC, Majkl-J commented
> So this already just affects roundstart abductors and not antag abductors?

Yup, I even specifically requested it to be as such for this exact reason.

2023-12-25 14:04 UTC, destrucktoid commented
> > So this already just affects roundstart abductors and not antag abductors?
> 
> Yup, I even specifically requested it to be as such for this exact reason.

Ah my bad then, see you've got this well in hand

2024-01-13 07:23 UTC, merged