Add dominatrix borg module to lustwish
Bubberstation/Bubberstation pull request #964
Opened 2024-01-07 18:04 UTC by thegrb93

## About The Pull Request
Adds a dominatrix borg module to lustwish (unfortunately someone still has to purchase it for the borg)
The module, when installed, adds a kinky shocker, whip, paddle, and tickle feather to the borg's repertoire

## Why It's Good For The Game
Gives borgs some kinky items for erp

## Proof Of Testing
![image](https://github.com/Bubberstation/Bubberstation/assets/6713261/1b403d9a-75da-4352-83f8-c5ef96970214)

## Changelog

:cl:
add: Borg dominatrix module to lustwish that gives them some dominatrix toys
/:cl:

2024-01-07 18:42 UTC, theselfish commented
Encourages borgs to drop their jobs at best and encourages them to use fetish gear in combat at worst.

👎🏻

2024-01-07 19:37 UTC, YakumoChen commented
Another great module for borgs to pref break me with!

2024-01-07 19:59 UTC, ReturnToZender commented
Pretty sure these modules respect your preferences by default. If not, be sure they do.

Cool and all as an upgrade set but I wish it was a whole module with sprites. Would be cool as heck to see latex borgs.

2024-01-07 20:14 UTC, Majkl-J requested changes
Borgs already suffer from hilarious item bloat, please make this into one radial menu item if possible

2024-01-08 01:55 UTC, thegrb93 commented
> Borgs already suffer from hilarious item bloat, please make this into one radial menu item if possible

That would make using multiple toys a pain. Only borgs that want the module will have it so no harm done

2024-01-08 04:34 UTC, thegrb93 commented
Maybe I can do that, but I'm adding more toys if I do.

2024-01-08 04:52 UTC, thegrb93 commented
@Majkl-J I don't think this is possible actually, requires a bunch of work on TG's side to do. Nova merged it btw https://github.com/NovaSector/NovaSector/pull/359

2024-01-08 07:49 UTC, YakumoChen commented
Just because they instant-merged a PR and have no standards doesn't mean we can't have some

2024-01-08 08:20 UTC, thegrb93 commented
> Just because they instant-merged a PR and have no standards doesn't mean we can't have some

I don't know what you have against borgs but its pretty silly. Both your complaints apply to non-borg characters too y'know?


> Pretty sure these modules respect your preferences by default. If not, be sure they do.
> 
> Cool and all as an upgrade set but I wish it was a whole module with sprites. Would be cool as heck to see latex borgs.

Eventually :>, and yes the items contain the ERP interaction checks.

2024-01-08 14:18 UTC, StrangeWeirdKitten commented
The items respect your prefs, so it's not entirely an awful feature. But: 

- There's 5 borg slots open and posi-brains. There's plenty of borgs to go around, I'm not worried about their jobs
- People are not turning on and off their ERP pref. So yes, I can see a borg using these things in combat.
- Our playerbase loves to abuse any inch you give them. Nova and our server are very diffrent. 

If you can make these items a subtype, and remove the actual knockdowns / stamina, then there will be no further concerns.

2024-01-08 14:18 UTC, StrangeWeirdKitten requested changes
I had something written here, but I thought of something else. Ignore this, it's under discussion.

2024-01-08 14:23 UTC, StrangeWeirdKitten commented
Pref-breaking is not an issue with this PR, and I will be marking any posts that bring it up as off-topic.

2024-01-08 14:57 UTC, StrangeWeirdKitten requested changes

2024-01-08 14:57 UTC, StrangeWeirdKitten commented on modular_skyrat/modules/borgs/code/robot_upgrade.dm
This entire things needs to either go on Skyrat/skyrat PR (which is our upstream) or be modularized. We do not stay up to date with Nova.

2024-01-08 15:03 UTC, thegrb93 commented on modular_skyrat/modules/borgs/code/robot_upgrade.dm
The upstream needs to be updated, the community is playing on code from https://github.com/NovaSector/NovaSector now

2024-01-08 15:05 UTC, StrangeWeirdKitten commented on modular_skyrat/modules/borgs/code/robot_upgrade.dm
I'm telling you what our upstream currently is for the purposes of your PR. Either take it to skyrat/skyrat or modularize it.

2024-01-08 15:12 UTC, thegrb93 commented on modular_skyrat/modules/borgs/code/robot_upgrade.dm
I can open a PR there, but will be surprised if there any devs to look at it.

2024-01-08 18:44 UTC, theselfish commented on modular_skyrat/modules/borgs/code/robot_upgrade.dm
Huh. I thought we were disconnecting from Skyrat.

2024-01-12 07:14 UTC, thegrb93 commented on modular_skyrat/modules/borgs/code/robot_upgrade.dm
@StrangeWeirdKitten https://github.com/Skyrat-SS13/Skyrat-tg/pull/26100

2024-01-17 23:58 UTC, StrangeWeirdKitten commented
Merged upstream.

2024-01-17 23:58 UTC, merged