[Early Mirror] Tarkon Retarken, The great Atarkoining
Bubberstation/Bubberstation pull request #968
Opened 2024-01-08 10:25 UTC by Erol509

## About The Pull Request

Early Mirror from Upstream  https://github.com/Skyrat-SS13/Skyrat-tg/pull/26026

## Why It's Good For The Game

Redoes tarkon, gives it more people, I dont know. I'm tired, boss.

## Proof Of Testing

Works on upstream, then it will work here

## Changelog

:cl: Zenitheevee 
add: Adds Tarkon RCD: An RCD that can build at range, but not deconstruct R-walls. Has 300u capacity.
add: Adds A.R.C.S Resonator: A ranged version of the classic mining resonator. Be careful aiming it around your friends, though..
add: Adds the Tarkon MODsuit, I half engineering, half port-security modsuit, with enough mod capacity to fit each role comfortably.
add: Adds a uniform for all 7 departments in Tarkon, including a hat with a welding visor.
image: added 7 Uniform sprites and mobsprites with digitigrade support.
image: Added 1 tool sprite.
image: Added 1 gun sprite with inhand sprites.
image: Added 1 hat sprite, does not conflict with muzzles.
code: condensed most tarkon-specific code to one module.
map: Tarkon has been entirely redone. Check PR for more details
/:cl:

2024-01-08 14:52 UTC, StrangeWeirdKitten commented
In the future, remove the changelog or else it'll create duplicates.

2024-01-09 19:11 UTC, YakumoChen commented
Is the research servers and console on a seperate web? If its the default it'll affect the station techweb

2024-01-09 19:36 UTC, Erol509 commented
> Is the research servers and console on a seperate web? If its the default it'll affect the station techweb

You cant make separate techwebs, because they dont work. One on PR isnt separate.

2024-01-09 22:39 UTC, YakumoChen commented
They shouldn't have servers then...

2024-01-09 23:09 UTC, YakumoChen requested changes

2024-01-09 23:09 UTC, YakumoChen commented on modular_skyrat/modules/tarkon/code/misc-fluff/research.dm
They do have their own techweb????

Have you tested this?

2024-01-13 03:51 UTC, NargaInDisguise commented
All of these comments about nerfs are very confusing considering all of this gear is for an off-station ghost role. Literally none of this matters for the main game, do not nerf any of the shit, new tarkon is already considerably harder to clear than old tarkons simply because the mobs are constantly respawning.

2024-01-13 18:50 UTC, YakumoChen commented
None of my comments affect the difficulty, the suit is just unrealistically overturned / given cutting edge station tech for no reason

2024-01-26 22:09 UTC, JerryWester requested changes

2024-01-26 22:09 UTC, JerryWester commented on modular_skyrat/modules/tarkon/code/misc-fluff/research.dm
> +	build_path = /obj/item/mod/construction/plating/security
```suggestion
	build_path = /obj/item/mod/construction/plating/tarkon
```

2024-01-26 22:09 UTC, JerryWester commented on modular_skyrat/modules/tarkon/code/misc-fluff/research.dm
> +	build_path = /obj/item/mod/construction/plating/security
The build path is incorrect, should be `/obj/item/mod/construction/plating/tarkon`, or removed to avoid confusion.

2024-01-26 22:09 UTC, JerryWester commented on modular_skyrat/modules/tarkon/code/misc-fluff/research.dm
> +	research_icon_state = "standard-plating"
```suggestion
	research_icon_state = "tarkon-plating"
	research_icon = 'modular_skyrat/modules/tarkon/icons/obj/mod_construct.dmi'
```

2024-01-26 22:09 UTC, JerryWester commented on modular_skyrat/modules/tarkon/code/misc-fluff/research.dm
> +	research_icon_state = "standard-plating"
Why is `research_icon_state` set twice? And neither to the Tarkon plating?

2024-01-26 22:09 UTC, JerryWester commented on modular_skyrat/modules/tarkon/code/misc-fluff/research.dm
> +	build_path = /obj/item/construction/rcd/loaded
```suggestion
	build_path = /obj/item/construction/rcd/arcd/tarkon
```

2024-01-26 22:09 UTC, JerryWester commented on modular_skyrat/modules/tarkon/code/misc-fluff/research.dm
> +	build_path = /obj/item/construction/rcd/loaded
Also incorrect, should be `/obj/item/construction/rcd/arcd/tarkon` or removed

2024-01-28 19:54 UTC, Zenitheevee commented
Hey, Tarkon Dev here.

https://github.com/Skyrat-SS13/Skyrat-tg/pull/26271

An assortment of fixes that were caught and made on NovaSector's Tarkon PR.

If the Ranged Printable RCD is not desirable, One may wish to look at what was done with NovaSector's version.

And i'd like to just say: As much as SR lets "balance issues" or even technical issues slide through, They did lose a majority of their dev capabilities and cannot be blamed.

2024-01-28 19:56 UTC, Zenitheevee commented
> > Is the research servers and console on a seperate web? If its the default it'll affect the station techweb
> 
> You cant make separate techwebs, because they dont work. One on PR isnt separate.

it SHOULD be seperate, And they DO work, Given this place ported the TG support for Oldstation (AKA: Charliestation) to have their own.

I didn't read the PR for it thoroughly on my first time and forgot that you needed to write a small line in TG's Research file.

2024-01-28 20:51 UTC, Erol509 commented
> Hey, Tarkon Dev here.
> 
> [Skyrat-SS13/Skyrat-tg#26271](https://github.com/Skyrat-SS13/Skyrat-tg/pull/26271)
> 
> An assortment of fixes that were caught and made on NovaSector's Tarkon PR.
> 
> If the Ranged Printable RCD is not desirable, One may wish to look at what was done with NovaSector's version.
> 
> And i'd like to just say: As much as SR lets "balance issues" or even technical issues slide through, They did lose a majority of their dev capabilities and cannot be blamed.
> 
> Alternatively: It might be better to take [this PR](https://github.com/NovaSector/NovaSector/pull/358) and re-adapt it here, As this was shipped "Fixed"
> 
> edit: Might need to edit out the TEG boards in the engineering crate unless this place has TG's Fixed TEG's

I saw your PR, and Im going to apply fixes as soon as it gets merged, so I can cherry pick it fully. You dont need to look at that person complains, because they always complain under anything. Also, our place has indeed fixed and resprited TEG yet only as TM, but it works different than before and it requires different setups.

2024-01-28 20:53 UTC, Zenitheevee commented
> > Hey, Tarkon Dev here.
> > [Skyrat-SS13/Skyrat-tg#26271](https://github.com/Skyrat-SS13/Skyrat-tg/pull/26271)
> > An assortment of fixes that were caught and made on NovaSector's Tarkon PR.
> > If the Ranged Printable RCD is not desirable, One may wish to look at what was done with NovaSector's version.
> > And i'd like to just say: As much as SR lets "balance issues" or even technical issues slide through, They did lose a majority of their dev capabilities and cannot be blamed.
> > Alternatively: It might be better to take [this PR](https://github.com/NovaSector/NovaSector/pull/358) and re-adapt it here, As this was shipped "Fixed"
> > edit: Might need to edit out the TEG boards in the engineering crate unless this place has TG's Fixed TEG's
> 
> I saw your PR, and Im going to apply fixes as soon as it gets merged, so I can cherry pick it fully. You dont need to look at that person complains, because they always complain under anything. Also, our place has indeed fixed and resprited TEG yet only as TM, but it works different than before and it requires different setups.

Oh yeah i know about them, They were on SR and a constant opp for a good handful of coders on ""balance"".

Anyways, Aye, Cheers. Hope you the best of luck.

2024-02-13 04:23 UTC, closed without merging